package c64_pla_rev1

// Code generated by symphony-generator. DO NOT EDIT.

import (
	"errors"
	"github.com/markel1974/c64emu/src/references"
)

const (
	reflectCartManIntervalsId = "cartManIntervals"
	reflectMemoryConfigId     = "memoryConfig"
	reflectLabelId            = "label"
)

type PLAReflect struct {
	ref              *PLA
	outOfBoundsError error
	readOnlyError    error
}

func NewPLAReflect(r *PLA, factory references.IComponentFactory, parent references.IComponent, identifier string, instance int, hardwareId string) *PLAReflect {
	reflector := &PLAReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.BaseComponent.Register(factory, parent, identifier, instance, r, hardwareId)
	r.PropertyAdd(reflectCartManIntervalsId, "CartManIntervals", false, reflector.getCartManIntervals, reflector.setCartManIntervals)

	r.PropertyAdd(reflectMemoryConfigId, "MemoryConfig", false, reflector.getMemoryConfig, reflector.setMemoryConfig)

	_ = r.CommandAdd("getMemoryConfigEntry", "MemoryConfig", reflector.getMemoryConfigEntry)
	_ = r.CommandAdd("setMemoryConfigEntry", "MemoryConfig", reflector.setMemoryConfigEntry)

	r.PropertyAdd(reflectLabelId, "Label", false, reflector.getLabel, reflector.setLabel)

	_ = r.CommandAdd("Reset", "Reset() - Reset resets the internal state of the PLA, reinitializing ports, and triggering an update of the memory configuration.", r.Reset)
	_ = r.CommandAdd("Read", "Read(addr) uint8 - Read retrieves the value from the memory mapped by the given address.", r.Read)
	_ = r.CommandAdd("ExtWrite", "ExtWrite(memConfig, addr, data) - ExtWrite writes a byte to the specified address using the provided memory configuration, temporarily switching configurations.", r.ExtWrite)
	_ = r.CommandAdd("RemoveRamTrigger", "RemoveRamTrigger(addr, id) - RemoveRamTrigger removes a write-trigger by its unique ID for the specified memory address in the WriteTriggers collection.", r.RemoveRamTrigger)
	_ = r.CommandAdd("Emulate", "Emulate() - Emulate performs the main emulation step for the PLA, updating its state and processing associated logic.", r.Emulate)
	_ = r.CommandAdd("Write", "Write(addr, data) - Write writes a byte of data to a specific memory address based on the bank configuration and triggers write callbacks.", r.Write)
	_ = r.CommandAdd("ExtRead", "ExtRead(memConfig, addr) uint8 - ExtRead allows reading a specific memory address using a temporary memory configuration.", r.ExtRead)
	_ = r.CommandAdd("RebuildMemoryConfig", "RebuildMemoryConfig() - RebuildMemoryConfig recalculates and applies the current memory configuration based on cartridge and port settings.", r.RebuildMemoryConfig)

	return reflector
}

// getCartManIntervals is the generated getter for the cartManIntervals.
func (s *PLAReflect) getCartManIntervals() uint8 {
	return s.ref.cartManIntervals
}

// setCartManIntervals is the generated setter for the cartManIntervals field.
func (s *PLAReflect) setCartManIntervals(v uint8) error {
	s.ref.cartManIntervals = v
	return nil
}

// getMemoryConfig is the generated getter for the memoryConfig.
func (s *PLAReflect) getMemoryConfig() []uint8 {
	return s.ref.memoryConfig
}

// setMemoryConfig is the generated setter for the memoryConfig field.
func (s *PLAReflect) setMemoryConfig(v []uint8) error {
	copy(s.ref.memoryConfig, v)
	return nil
}

// getMemoryConfigEntry is the generated indexed getter for the memoryConfig.
func (s *PLAReflect) getMemoryConfigEntry(idx int) (uint8, error) {
	if idx >= 0 && idx < len(s.ref.memoryConfig) {
		return s.ref.memoryConfig[idx], nil
	}
	return *new(uint8), s.outOfBoundsError
}

// setMemoryConfigEntry is the generated indexed setter for the memoryConfig.
func (s *PLAReflect) setMemoryConfigEntry(idx int, v uint8) error {
	if idx >= 0 && idx < len(s.ref.memoryConfig) {
		s.ref.memoryConfig[idx] = v
		return nil
	}
	return errors.New("index out of bounds")
}

// getLabel is the generated getter for the label.
func (s *PLAReflect) getLabel() string {
	return s.ref.label
}

// setLabel is the generated setter for the label field.
func (s *PLAReflect) setLabel(v string) error {
	s.ref.label = v
	return nil
}
