package c64_pla_rev1

// Code generated by symphony-generator. DO NOT EDIT.

import (
	"errors"
	"github.com/markel1974/symphony/src/references"
)

const (
	reflectMaskId  = "mask"
	reflectIndexId = "index"
)

type BankSwitcherReflect struct {
	ref              *BankSwitcher
	outOfBoundsError error
	readOnlyError    error
}

func NewBankSwitcherReflect(r *BankSwitcher, factory references.IComponentFactory, parent references.IComponent, identifier string, instance int, hardwareId string) *BankSwitcherReflect {
	reflector := &BankSwitcherReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.BaseComponent.Register(factory, parent, identifier, instance, r, hardwareId)
	r.PropertyAdd(reflectMaskId, "Mask", false, reflector.getMask, reflector.setMask)

	r.PropertyAdd(reflectIndexId, "index", false, reflector.getIndex, reflector.setIndex)

	_ = r.CommandAdd("Reset", "Reset() - Reset restores the BankSwitcher instance to its initial state, clearing any previous configurations or settings.", r.Reset)
	_ = r.CommandAdd("Emulate", "Emulate() - Emulate performs the emulation logic associated with the BankSwitcher component during a processing cycle.", r.Emulate)
	_ = r.CommandAdd("ReadConfig", "ReadConfig() int - ReadConfig returns the current memory configuration index managed by the BankSwitcher instance.", r.ReadConfig)
	_ = r.CommandAdd("WriteConfig", "WriteConfig(memConfig) []byte,bool - WriteConfig updates the memory configuration index and returns the mode table entry and true if the index has changed.", r.WriteConfig)

	return reflector
}

// getMask is the generated getter for the mask.
func (s *BankSwitcherReflect) getMask() uint8 {
	return s.ref.mask
}

// setMask is the generated setter for the mask field.
func (s *BankSwitcherReflect) setMask(v uint8) error {
	s.ref.mask = v
	return nil
}

// getIndex is the generated getter for the index.
func (s *BankSwitcherReflect) getIndex() int {
	return s.ref.index
}

// setIndex is the generated setter for the index field.
func (s *BankSwitcherReflect) setIndex(v int) error {
	s.ref.index = v
	return nil
}
