package c64_pla_rev1

// Code generated by symphony-generator. DO NOT EDIT.

import (
	"errors"
	"github.com/markel1974/c64emu/src/references"
)

const (
	reflectDataOutId         = "dataOut"
	reflectDirId             = "dir"
	reflectDataId            = "data"
	reflectDataReadId        = "dataRead"
	reflectOldDataOutId      = "oldDataOut"
	reflectOldWriteBitId     = "oldWriteBit"
	reflectOldSenseOutId     = "oldSenseOut"
	reflectDataSetBit6Id     = "dataSetBit6"
	reflectDataSetBit7Id     = "dataSetBit7"
	reflectDataFalloffBit6Id = "dataFalloffBit6"
	reflectDataFalloffBit7Id = "dataFalloffBit7"
	reflectTapeSenseId       = "tapeSense"
	reflectTapeWriteInId     = "tapeWriteIn"
	reflectTapeMotorInId     = "tapeMotorIn"
	reflectCapsSenseId       = "capsSense"
	reflectPullUpId          = "pullUp"
)

type PortsReflect struct {
	ref              *Ports
	outOfBoundsError error
	readOnlyError    error
}

func NewPortsReflect(r *Ports, factory references.IComponentFactory, parent references.IComponent, identifier string, instance int, hardwareId string) *PortsReflect {
	reflector := &PortsReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.BaseComponent.Register(factory, parent, identifier, instance, r, hardwareId)
	r.PropertyAdd(reflectDataOutId, "DataOut", false, reflector.getDataOut, reflector.setDataOut)

	r.PropertyAdd(reflectDirId, "Dir", false, reflector.getDir, reflector.setDir)

	r.PropertyAdd(reflectDataId, "Data", false, reflector.getData, reflector.setData)

	r.PropertyAdd(reflectDataReadId, "DataRead", false, reflector.getDataRead, reflector.setDataRead)

	r.PropertyAdd(reflectOldDataOutId, "Tape motor status", false, reflector.getOldDataOut, reflector.setOldDataOut)

	r.PropertyAdd(reflectOldWriteBitId, "Tape write line status", false, reflector.getOldWriteBit, reflector.setOldWriteBit)

	r.PropertyAdd(reflectOldSenseOutId, "Tape sense line out status", false, reflector.getOldSenseOut, reflector.setOldSenseOut)

	r.PropertyAdd(reflectDataSetBit6Id, "DataSetBit6", false, reflector.getDataSetBit6, reflector.setDataSetBit6)

	r.PropertyAdd(reflectDataSetBit7Id, "DataSetBit7", false, reflector.getDataSetBit7, reflector.setDataSetBit7)

	r.PropertyAdd(reflectDataFalloffBit6Id, "DataFalloffBit6", false, reflector.getDataFalloffBit6, reflector.setDataFalloffBit6)

	r.PropertyAdd(reflectDataFalloffBit7Id, "DataFalloffBit7", false, reflector.getDataFalloffBit7, reflector.setDataFalloffBit7)

	r.PropertyAdd(reflectTapeSenseId, "TapeSense", false, reflector.getTapeSense, reflector.setTapeSense)

	r.PropertyAdd(reflectTapeWriteInId, "TapeWriteIn", false, reflector.getTapeWriteIn, reflector.setTapeWriteIn)

	r.PropertyAdd(reflectTapeMotorInId, "TapeMotorIn", false, reflector.getTapeMotorIn, reflector.setTapeMotorIn)

	r.PropertyAdd(reflectCapsSenseId, "CapsSense", false, reflector.getCapsSense, reflector.setCapsSense)

	r.PropertyAdd(reflectPullUpId, "PullUp", false, reflector.getPullUp, reflector.setPullUp)

	_ = r.CommandAdd("WriteDir", "WriteDir(data) - WriteDir sets the direction register of the Ports to the specified value.", r.WriteDir)
	_ = r.CommandAdd("WriteData", "WriteData(data) - WriteData sets the data property of the Ports instance to the specified value.", r.WriteData)
	_ = r.CommandAdd("Config", "Config() uint8,uint8 - Config calculates the memory configuration index based on port direction and data values.", r.Config)
	_ = r.CommandAdd("Reset", "Reset() - Reset resets all port-related variables in the Ports struct to their default state.", r.Reset)
	_ = r.CommandAdd("ReadDirection", "ReadDirection() uint8 - ReadDirection returns the current direction configuration of the port as an 8-bit unsigned integer.", r.ReadDirection)
	_ = r.CommandAdd("ReadDataRead", "ReadDataRead() uint8 - ReadDataRead retrieves the current value of the `dataRead` field from the Ports structure.", r.ReadDataRead)
	_ = r.CommandAdd("WriteTape", "WriteTape(tapeSense, tapeWriteIn, tapeMotorIn) - WriteTape sets the tape sense, tape write input, and tape motor input values for the Ports instance.", r.WriteTape)
	_ = r.CommandAdd("Update", "Update() - Update recalculates the state of the Ports structure based on current register values, adjusting outputs and data logic.", r.Update)
	_ = r.CommandAdd("Emulate", "Emulate() - ", r.Emulate)

	return reflector
}

// getDataOut is the generated getter for the dataOut.
func (s *PortsReflect) getDataOut() uint8 {
	return s.ref.dataOut
}

// setDataOut is the generated setter for the dataOut field.
func (s *PortsReflect) setDataOut(v uint8) error {
	s.ref.dataOut = v
	return nil
}

// getDir is the generated getter for the dir.
func (s *PortsReflect) getDir() uint8 {
	return s.ref.dir
}

// setDir is the generated setter for the dir field.
func (s *PortsReflect) setDir(v uint8) error {
	s.ref.dir = v
	return nil
}

// getData is the generated getter for the data.
func (s *PortsReflect) getData() uint8 {
	return s.ref.data
}

// setData is the generated setter for the data field.
func (s *PortsReflect) setData(v uint8) error {
	s.ref.data = v
	return nil
}

// getDataRead is the generated getter for the dataRead.
func (s *PortsReflect) getDataRead() uint8 {
	return s.ref.dataRead
}

// setDataRead is the generated setter for the dataRead field.
func (s *PortsReflect) setDataRead(v uint8) error {
	s.ref.dataRead = v
	return nil
}

// getOldDataOut is the generated getter for the oldDataOut.
func (s *PortsReflect) getOldDataOut() uint8 {
	return s.ref.oldDataOut
}

// setOldDataOut is the generated setter for the oldDataOut field.
func (s *PortsReflect) setOldDataOut(v uint8) error {
	s.ref.oldDataOut = v
	return nil
}

// getOldWriteBit is the generated getter for the oldWriteBit.
func (s *PortsReflect) getOldWriteBit() uint8 {
	return s.ref.oldWriteBit
}

// setOldWriteBit is the generated setter for the oldWriteBit field.
func (s *PortsReflect) setOldWriteBit(v uint8) error {
	s.ref.oldWriteBit = v
	return nil
}

// getOldSenseOut is the generated getter for the oldSenseOut.
func (s *PortsReflect) getOldSenseOut() uint8 {
	return s.ref.oldSenseOut
}

// setOldSenseOut is the generated setter for the oldSenseOut field.
func (s *PortsReflect) setOldSenseOut(v uint8) error {
	s.ref.oldSenseOut = v
	return nil
}

// getDataSetBit6 is the generated getter for the dataSetBit6.
func (s *PortsReflect) getDataSetBit6() uint8 {
	return s.ref.dataSetBit6
}

// setDataSetBit6 is the generated setter for the dataSetBit6 field.
func (s *PortsReflect) setDataSetBit6(v uint8) error {
	s.ref.dataSetBit6 = v
	return nil
}

// getDataSetBit7 is the generated getter for the dataSetBit7.
func (s *PortsReflect) getDataSetBit7() uint8 {
	return s.ref.dataSetBit7
}

// setDataSetBit7 is the generated setter for the dataSetBit7 field.
func (s *PortsReflect) setDataSetBit7(v uint8) error {
	s.ref.dataSetBit7 = v
	return nil
}

// getDataFalloffBit6 is the generated getter for the dataFalloffBit6.
func (s *PortsReflect) getDataFalloffBit6() uint8 {
	return s.ref.dataFalloffBit6
}

// setDataFalloffBit6 is the generated setter for the dataFalloffBit6 field.
func (s *PortsReflect) setDataFalloffBit6(v uint8) error {
	s.ref.dataFalloffBit6 = v
	return nil
}

// getDataFalloffBit7 is the generated getter for the dataFalloffBit7.
func (s *PortsReflect) getDataFalloffBit7() uint8 {
	return s.ref.dataFalloffBit7
}

// setDataFalloffBit7 is the generated setter for the dataFalloffBit7 field.
func (s *PortsReflect) setDataFalloffBit7(v uint8) error {
	s.ref.dataFalloffBit7 = v
	return nil
}

// getTapeSense is the generated getter for the tapeSense.
func (s *PortsReflect) getTapeSense() int {
	return s.ref.tapeSense
}

// setTapeSense is the generated setter for the tapeSense field.
func (s *PortsReflect) setTapeSense(v int) error {
	s.ref.tapeSense = v
	return nil
}

// getTapeWriteIn is the generated getter for the tapeWriteIn.
func (s *PortsReflect) getTapeWriteIn() int {
	return s.ref.tapeWriteIn
}

// setTapeWriteIn is the generated setter for the tapeWriteIn field.
func (s *PortsReflect) setTapeWriteIn(v int) error {
	s.ref.tapeWriteIn = v
	return nil
}

// getTapeMotorIn is the generated getter for the tapeMotorIn.
func (s *PortsReflect) getTapeMotorIn() int {
	return s.ref.tapeMotorIn
}

// setTapeMotorIn is the generated setter for the tapeMotorIn field.
func (s *PortsReflect) setTapeMotorIn(v int) error {
	s.ref.tapeMotorIn = v
	return nil
}

// getCapsSense is the generated getter for the capsSense.
func (s *PortsReflect) getCapsSense() int {
	return s.ref.capsSense
}

// setCapsSense is the generated setter for the capsSense field.
func (s *PortsReflect) setCapsSense(v int) error {
	s.ref.capsSense = v
	return nil
}

// getPullUp is the generated getter for the pullUp.
func (s *PortsReflect) getPullUp() uint8 {
	return s.ref.pullUp
}

// setPullUp is the generated setter for the pullUp field.
func (s *PortsReflect) setPullUp(v uint8) error {
	s.ref.pullUp = v
	return nil
}
