package mos6510_rev1

import "reflect"

var _opContainer = make(map[reflect.Value]string)

var _opReverseContainer = make(map[string]reflect.Value)

func init() {
	addOpId(InstOpPHA, "instOpPHA")
	addOpId(InstOpPHA1, "instOpPHA1")
	addOpId(InstOpPLA, "instOpPLA")
	addOpId(InstOpPLA1, "instOpPLA1")
	addOpId(InstOpPLA2, "instOpPLA2")
	addOpId(InstOpPHP, "instOpPHP")
	addOpId(InstOpPHP1, "instOpPHP1")
	addOpId(InstOpPLP, "instOpPLP")
	addOpId(InstOpPLP1, "instOpPLP1")
	addOpId(InstOpPLP2, "instOpPLP2")
	addOpId(InstOpNMI, "instOpNMI")
	addOpId(InstOpNMI1, "instOpNMI1")
	addOpId(InstOpNMI2, "instOpNMI2")
	addOpId(InstOpNMI3, "instOpNMI3")
	addOpId(InstOpNMI4, "instOpNMI4")
	addOpId(InstOpNMI5, "instOpNMI5")
	addOpId(InstOpNMI6, "instOpNMI6")
	addOpId(InstApZER, "instApZER")
	addOpId(InstApZERx, "instApZERx")
	addOpId(InstApZERx1, "instApZERx1")
	addOpId(InstApZERy, "instApZERy")
	addOpId(InstApZERy1, "instApZERy1")
	addOpId(InstApABS, "instApABS")
	addOpId(InstApABS1, "instApABS1")
	addOpId(InstApABSx, "instApABSx")
	addOpId(InstApABSx1, "instApABSx1")
	addOpId(InstApABSx2, "instApABSx2")
	addOpId(InstApABSx3, "instApABSx3")
	addOpId(InstApABSy, "instApABSy")
	addOpId(InstApABSy1, "instApABSy1")
	addOpId(InstApABSy2, "instApABSy2")
	addOpId(InstApABSy3, "instApABSy3")
	addOpId(InstApINDx, "instApINDx")
	addOpId(InstApINDx1, "instApINDx1")
	addOpId(InstApINDx2, "instApINDx2")
	addOpId(InstApINDx3, "instApINDx3")
	addOpId(InstApINDy, "instApINDy")
	addOpId(InstApINDy1, "instApINDy1")
	addOpId(InstApINDy2, "instApINDy2")
	addOpId(InstApINDy3, "instApINDy3")
	addOpId(InstApINDy4, "instApINDy4")
	addOpId(InstAeABSx, "instAeABSx")
	addOpId(InstAeABSx1, "instAeABSx1")
	addOpId(InstAeABSx2, "instAeABSx2")
	addOpId(InstAeABSy, "instAeABSy")
	addOpId(InstAeABSy1, "instAeABSy1")
	addOpId(InstAeABSy2, "instAeABSy2")
	addOpId(InstAeINDy, "instAeINDy")
	addOpId(InstAeINDy1, "instAeINDy1")
	addOpId(InstAeINDy2, "instAeINDy2")
	addOpId(InstAeINDy3, "instAeINDy3")
	addOpId(InstMpZER, "instMpZER")
	addOpId(InstMpZERx, "instMpZERx")
	addOpId(InstMpZERx1, "instMpZERx1")
	addOpId(InstMpABS, "instMpABS")
	addOpId(InstMpABS1, "instMpABS1")
	addOpId(InstMpABSx, "instMpABSx")
	addOpId(InstMpABSx1, "instMpABSx1")
	addOpId(InstMpABSx2, "instMpABSx2")
	addOpId(InstMpABSx3, "instMpABSx3")
	addOpId(InstMpABSy, "instMpABSy")
	addOpId(InstMpABSy1, "instMpABSy1")
	addOpId(InstMpABSy2, "instMpABSy2")
	addOpId(InstMpABSy3, "instMpABSy3")
	addOpId(InstMpINDx, "instMpINDx")
	addOpId(InstMpINDx1, "instMpINDx1")
	addOpId(InstMpINDx2, "instMpINDx2")
	addOpId(InstMpINDx3, "instMpINDx3")
	addOpId(InstMpINDy, "instMpINDy")
	addOpId(InstMpINDy1, "instMpINDy1")
	addOpId(InstMpINDy2, "instMpINDy2")
	addOpId(InstMpINDy3, "instMpINDy3")
	addOpId(InstMpINDy4, "instMpINDy4")
	addOpId(InstOpRMW, "instOpRMW")
	addOpId(InstOpRMW1, "instOpRMW1")
	addOpId(InstOpLDA, "instOpLDA")
	addOpId(InstOiLDA, "instOiLDA")
	addOpId(InstOpLDX, "instOpLDX")
	addOpId(InstOiLDX, "instOiLDX")
	addOpId(InstOpLDY, "instOpLDY")
	addOpId(InstOiLDY, "instOiLDY")
	addOpId(InstOpSTA, "instOpSTA")
	addOpId(InstOpSTX, "instOpSTX")
	addOpId(InstOpSTY, "instOpSTY")
	addOpId(InstOpIRQ, "instOpIRQ")
	addOpId(InstOpIRQ1, "instOpIRQ1")
	addOpId(InstOpIRQ2, "instOpIRQ2")
	addOpId(InstOpIRQ3, "instOpIRQ3")
	addOpId(InstOpIRQ4, "instOpIRQ4")
	addOpId(InstOpIRQ5, "instOpIRQ5")
	addOpId(InstOpIRQ6, "instOpIRQ6")
	addOpId(InstOiNOP, "instOiNOP")
	addOpId(InstOaNOP, "instOaNOP")
	addOpId(InstOpLAX, "instOpLAX")
	addOpId(InstOpSAX, "instOpSAX")
	addOpId(InstOpSLO, "instOpSLO")
	addOpId(InstOpRLA, "instOpRLA")
	addOpId(InstOpSRE, "instOpSRE")
	addOpId(InstOpRRA, "instOpRRA")
	addOpId(InstOpDCP, "instOpDCP")
	addOpId(InstOpISB, "instOpISB")
	addOpId(InstOiANC, "instOiANC")
	addOpId(InstOiASR, "instOiASR")
	addOpId(InstOiARR, "instOiARR")
	addOpId(InstOiANE, "instOiANE")
	addOpId(InstOiLXA, "instOiLXA")
	addOpId(InstOiSBX, "instOiSBX")
	addOpId(InstOpLAS, "instOpLAS")
	addOpId(InstOpSHS, "instOpSHS")
	addOpId(InstOpSHY, "instOpSHY")
	addOpId(InstOpSHX, "instOpSHX")
	addOpId(InstOpSHA, "instOpSHA")
	addOpId(InstOpJAM, "instOpJAM")
	addOpId(InstOpTAX, "instOpTAX")
	addOpId(InstOpTXA, "instOpTXA")
	addOpId(InstOpTAY, "instOpTAY")
	addOpId(InstOpTYA, "instOpTYA")
	addOpId(InstOpTSX, "instOpTSX")
	addOpId(InstOpTXS, "instOpTXS")
	addOpId(InstOpSEC, "instOpSEC")
	addOpId(InstOpCLC, "instOpCLC")
	addOpId(InstOpSED, "instOpSED")
	addOpId(InstOpCLD, "instOpCLD")
	addOpId(InstOpSEI, "instOpSEI")
	addOpId(InstOpCLI, "instOpCLI")
	addOpId(InstOpCLV, "instOpCLV")
	addOpId(InstOpNOP, "instOpNOP")
	addOpId(InstOpADC, "instOpADC")
	addOpId(InstOiADC, "instOiADC")
	addOpId(InstOpSBC, "instOpSBC")
	addOpId(InstOiSBC, "instOiSBC")
	addOpId(InstOpINX, "instOpINX")
	addOpId(InstOpDEX, "instOpDEX")
	addOpId(InstOpINY, "instOpINY")
	addOpId(InstOpDEY, "instOpDEY")
	addOpId(InstOpINC, "instOpINC")
	addOpId(InstOpDEC, "instOpDEC")
	addOpId(InstOpAND, "instOpAND")
	addOpId(InstOiAND, "instOiAND")
	addOpId(InstOpORA, "instOpORA")
	addOpId(InstOiOPA, "instOiOPA")
	addOpId(InstOpEOR, "instOpEOR")
	addOpId(InstOiEOR, "instOiEOR")
	addOpId(InstOpCMP, "instOpCMP")
	addOpId(InstOiCMP, "instOiCMP")
	addOpId(InstOpCPX, "instOpCPX")
	addOpId(InstOiCPX, "instOiCPX")
	addOpId(InstOpCPY, "instOpCPY")
	addOpId(InstOiCPY, "instOiCPY")
	addOpId(InstOpBIT, "instOpBIT")
	addOpId(InstOpASL, "instOpASL")
	addOpId(InstOaASL, "instOaASL")
	addOpId(InstOpLSR, "instOpLSR")
	addOpId(InstOaLSR, "instOaLSR")
	addOpId(InstOpROL, "instOpROL")
	addOpId(InstOaROL, "instOaROL")
	addOpId(InstOpROR, "instOpROR")
	addOpId(InstOaROR, "instOaROR")
	addOpId(InstOpJMP, "instOpJMP")
	addOpId(InstOpJMP1, "instOpJMP1")
	addOpId(InstOiJMP, "instOiJMP")
	addOpId(InstOiJMP1, "instOiJMP1")
	addOpId(InstOpJSR, "instOpJSR")
	addOpId(InstOpJSR1, "instOpJSR1")
	addOpId(InstOpJSR2, "instOpJSR2")
	addOpId(InstOpJSR3, "instOpJSR3")
	addOpId(InstOpJSR4, "instOpJSR4")
	addOpId(InstOpRTS, "instOpRTS")
	addOpId(InstOpRTS1, "instOpRTS1")
	addOpId(InstOpRTS2, "instOpRTS2")
	addOpId(InstOpRTS3, "instOpRTS3")
	addOpId(InstOpRTS4, "instOpRTS4")
	addOpId(InstOpRTI, "instOpRTI")
	addOpId(InstOpRTI1, "instOpRTI1")
	addOpId(InstOpRTI2, "instOpRTI2")
	addOpId(InstOpRTI3, "instOpRTI3")
	addOpId(InstOpRTI4, "instOpRTI4")
	addOpId(InstOpBRK, "instOpBRK")
	addOpId(InstOpBRK1, "instOpBRK1")
	addOpId(InstOpBRK2, "instOpBRK2")
	addOpId(InstOpBRK3, "instOpBRK3")
	addOpId(InstOpBRK4, "instOpBRK4")
	addOpId(InstOpBRK5, "instOpBRK5")
	addOpId(InstOpBCS, "instOpBCS")
	addOpId(InstOpBCC, "instOpBCC")
	addOpId(InstOpBEQ, "instOpBEQ")
	addOpId(InstOpBNE, "instOpBNE")
	addOpId(InstOpBVS, "instOpBVS")
	addOpId(InstOpBVC, "instOpBVC")
	addOpId(InstOpBMI, "instOpBMI")
	addOpId(InstOpBPL, "instOpBPL")
	addOpId(InstOpBRAnp, "instOpBRAnp")
	addOpId(InstOpBRAbp, "instOpBRAbp")
	addOpId(InstOpBRAbp1, "instOpBRAbp1")
	addOpId(InstOpBRAfp, "instOpBRAfp")
	addOpId(InstOpBRAfp1, "instOpBRAfp1")
}

func addOpId(v func(cpu *CPU), id string) {
	r := reflect.ValueOf(v)
	_opContainer[r] = id
	_opReverseContainer[id] = r
}

func GetOpId(v func(cpu *CPU)) (string, bool) {
	if v == nil {
		return "", false
	}
	r := reflect.ValueOf(v)
	ret, ok := _opContainer[r]
	if !ok {
		return "", false
	}
	return ret, true
}

func GetOpFn(v string) (func(cpu *CPU), bool) {
	r, ok := _opReverseContainer[v]
	if !ok {
		return nil, false
	}
	ret, ok := r.Interface().(func(cpu *CPU))
	if !ok {
		return nil, false
	}
	return ret, true
}
