package mos6510_rev1

// Code generated by symphony-generator. DO NOT EDIT.

import (
	"errors"
	"github.com/markel1974/c64emu/src/references"
)

const (
	reflectNFlagId   = "nFlag"
	reflectZFlagId   = "zFlag"
	reflectVFlagId   = "vFlag"
	reflectDFlagId   = "dFlag"
	reflectIFlagId   = "iFlag"
	reflectCFlagId   = "cFlag"
	reflectAId       = "a"
	reflectXId       = "x"
	reflectYId       = "y"
	reflectSpId      = "sp"
	reflectPcId      = "pc"
	reflectOpId      = "op"
	reflectArId      = "ar"
	reflectAr2Id     = "ar2"
	reflectRmwId     = "rmw"
	reflectRdyLowId  = "rdyLow"
	reflectAecLowId  = "aecLow"
	reflectOpFlagsId = "opFlags"
	reflectLabelId   = "label"
)

type CPUReflect struct {
	ref              *CPU
	outOfBoundsError error
	readOnlyError    error
}

func NewCPUReflect(r *CPU, factory references.IComponentFactory, parent references.IComponent, identifier string, instance int, hardwareId string) *CPUReflect {
	reflector := &CPUReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.BaseComponent.Register(factory, parent, identifier, instance, r, hardwareId)
	r.PropertyAdd(reflectNFlagId, "nFlag Negative flag - Only the highest bit of the nFlag variable is used", false, reflector.getNFlag, reflector.setNFlag)

	r.PropertyAdd(reflectZFlagId, "zFlag Zero flag - The zFlag variable has the inverse meaning of the 6510 Z flag", false, reflector.getZFlag, reflector.setZFlag)

	r.PropertyAdd(reflectVFlagId, "vFlag Overflow flag", false, reflector.getVFlag, reflector.setVFlag)

	r.PropertyAdd(reflectDFlagId, "dFlag Decimal mode flag", false, reflector.getDFlag, reflector.setDFlag)

	r.PropertyAdd(reflectIFlagId, "iFlag Interrupt disable flag", false, reflector.getIFlag, reflector.setIFlag)

	r.PropertyAdd(reflectCFlagId, "cFlag Carry flag", false, reflector.getCFlag, reflector.setCFlag)

	r.PropertyAdd(reflectAId, "a Register", false, reflector.getA, reflector.setA)

	r.PropertyAdd(reflectXId, "x Register", false, reflector.getX, reflector.setX)

	r.PropertyAdd(reflectYId, "y Register", false, reflector.getY, reflector.setY)

	r.PropertyAdd(reflectSpId, "sp Stack pointer", false, reflector.getSp, reflector.setSp)

	r.PropertyAdd(reflectPcId, "pc Program counter", false, reflector.getPc, reflector.setPc)

	r.PropertyAdd(reflectOpId, "op Current opcode", false, reflector.getOp, reflector.setOp)

	r.PropertyAdd(reflectArId, "ar Address register", false, reflector.getAr, reflector.setAr)

	r.PropertyAdd(reflectAr2Id, "ar2 Address register 2", false, reflector.getAr2, reflector.setAr2)

	r.PropertyAdd(reflectRmwId, "rmw Data buffer for RMW instructions", false, reflector.getRmw, reflector.setRmw)

	r.PropertyAdd(reflectRdyLowId, "rdyLow current RDY state", false, reflector.getRdyLow, reflector.setRdyLow)

	r.PropertyAdd(reflectAecLowId, "aecLow current AEC state", false, reflector.getAecLow, reflector.setAecLow)

	r.PropertyAdd(reflectOpFlagsId, "opFlags is a uint8 value used to store operational flags for the CPU's current instruction state.", false, reflector.getOpFlags, reflector.setOpFlags)

	r.PropertyAdd(reflectLabelId, "Label", false, reflector.getLabel, reflector.setLabel)

	_ = r.CommandAdd("ClearIRQ", "ClearIRQ(v) - ClearIRQ clears the interrupt request (IRQ) for the given IRQ vector by invoking the associated PIC method.", r.ClearIRQ)
	_ = r.CommandAdd("TriggerNMI", "TriggerNMI() - TriggerNMI forces a Non-Maskable Interrupt (NMI) to occur on the CPU by signaling the programmable interrupt controller.", r.TriggerNMI)
	_ = r.CommandAdd("SetRDYLow", "SetRDYLow(rdyLow) - SetRDYLow sets the RDY line state to low or high based on the provided boolean value and updates the CPU stop state accordingly.", r.SetRDYLow)
	_ = r.CommandAdd("Reset", "Reset() - Reset initializes or restores the CPU to a default state by resetting internal flags, registers, and setting the program counter.", r.Reset)
	_ = r.CommandAdd("ClearNMI", "ClearNMI() - ClearNMI clears the Non-Maskable Interrupt (NMI) state by delegating the operation to the programmable interrupt controller.", r.ClearNMI)
	_ = r.CommandAdd("SetAECLow", "SetAECLow(aecLow) - SetAECLow sets the AEC line state to low or high based on the provided boolean value and updates the CPU stop state accordingly.", r.SetAECLow)
	_ = r.CommandAdd("IRQ", "IRQ() - go:nosplit", r.IRQ)
	_ = r.CommandAdd("TriggerReset", "TriggerReset() - TriggerReset initiates a reset operation on the CPU by activating the corresponding reset mechanism in the PIC.", r.TriggerReset)
	_ = r.CommandAdd("TriggerIRQ", "TriggerIRQ(v) - TriggerIRQ triggers an interrupt request (IRQ) by delegating the request to the programmable interrupt controller (PIC).", r.TriggerIRQ)
	_ = r.CommandAdd("Emulate", "Emulate() - Emulate processes one CPU cycle by invoking the next instruction handler unless the CPU is stopped.  go:nosplit", r.Emulate)
	_ = r.CommandAdd("NMI", "NMI() - go:nosplit", r.NMI)

	return reflector
}

// getNFlag is the generated getter for the nFlag.
func (s *CPUReflect) getNFlag() uint8 {
	return s.ref.nFlag
}

// setNFlag is the generated setter for the nFlag field.
func (s *CPUReflect) setNFlag(v uint8) error {
	s.ref.nFlag = v
	return nil
}

// getZFlag is the generated getter for the zFlag.
func (s *CPUReflect) getZFlag() uint8 {
	return s.ref.zFlag
}

// setZFlag is the generated setter for the zFlag field.
func (s *CPUReflect) setZFlag(v uint8) error {
	s.ref.zFlag = v
	return nil
}

// getVFlag is the generated getter for the vFlag.
func (s *CPUReflect) getVFlag() uint8 {
	return s.ref.vFlag
}

// setVFlag is the generated setter for the vFlag field.
func (s *CPUReflect) setVFlag(v uint8) error {
	s.ref.vFlag = v
	return nil
}

// getDFlag is the generated getter for the dFlag.
func (s *CPUReflect) getDFlag() uint8 {
	return s.ref.dFlag
}

// setDFlag is the generated setter for the dFlag field.
func (s *CPUReflect) setDFlag(v uint8) error {
	s.ref.dFlag = v
	return nil
}

// getIFlag is the generated getter for the iFlag.
func (s *CPUReflect) getIFlag() uint8 {
	return s.ref.iFlag
}

// setIFlag is the generated setter for the iFlag field.
func (s *CPUReflect) setIFlag(v uint8) error {
	s.ref.iFlag = v
	return nil
}

// getCFlag is the generated getter for the cFlag.
func (s *CPUReflect) getCFlag() uint8 {
	return s.ref.cFlag
}

// setCFlag is the generated setter for the cFlag field.
func (s *CPUReflect) setCFlag(v uint8) error {
	s.ref.cFlag = v
	return nil
}

// getA is the generated getter for the a.
func (s *CPUReflect) getA() uint8 {
	return s.ref.a
}

// setA is the generated setter for the a field.
func (s *CPUReflect) setA(v uint8) error {
	s.ref.a = v
	return nil
}

// getX is the generated getter for the x.
func (s *CPUReflect) getX() uint8 {
	return s.ref.x
}

// setX is the generated setter for the x field.
func (s *CPUReflect) setX(v uint8) error {
	s.ref.x = v
	return nil
}

// getY is the generated getter for the y.
func (s *CPUReflect) getY() uint8 {
	return s.ref.y
}

// setY is the generated setter for the y field.
func (s *CPUReflect) setY(v uint8) error {
	s.ref.y = v
	return nil
}

// getSp is the generated getter for the sp.
func (s *CPUReflect) getSp() uint8 {
	return s.ref.sp
}

// setSp is the generated setter for the sp field.
func (s *CPUReflect) setSp(v uint8) error {
	s.ref.sp = v
	return nil
}

// getPc is the generated getter for the pc.
func (s *CPUReflect) getPc() uint16 {
	return s.ref.pc
}

// setPc is the generated setter for the pc field.
func (s *CPUReflect) setPc(v uint16) error {
	s.ref.pc = v
	return nil
}

// getOp is the generated getter for the op.
func (s *CPUReflect) getOp() uint8 {
	return s.ref.op
}

// setOp is the generated setter for the op field.
func (s *CPUReflect) setOp(v uint8) error {
	s.ref.op = v
	return nil
}

// getAr is the generated getter for the ar.
func (s *CPUReflect) getAr() uint16 {
	return s.ref.ar
}

// setAr is the generated setter for the ar field.
func (s *CPUReflect) setAr(v uint16) error {
	s.ref.ar = v
	return nil
}

// getAr2 is the generated getter for the ar2.
func (s *CPUReflect) getAr2() uint16 {
	return s.ref.ar2
}

// setAr2 is the generated setter for the ar2 field.
func (s *CPUReflect) setAr2(v uint16) error {
	s.ref.ar2 = v
	return nil
}

// getRmw is the generated getter for the rmw.
func (s *CPUReflect) getRmw() uint8 {
	return s.ref.rmw
}

// setRmw is the generated setter for the rmw field.
func (s *CPUReflect) setRmw(v uint8) error {
	s.ref.rmw = v
	return nil
}

// getRdyLow is the generated getter for the rdyLow.
func (s *CPUReflect) getRdyLow() bool {
	return s.ref.rdyLow
}

// setRdyLow is the generated setter for the rdyLow field.
func (s *CPUReflect) setRdyLow(v bool) error {
	s.ref.rdyLow = v
	return nil
}

// getAecLow is the generated getter for the aecLow.
func (s *CPUReflect) getAecLow() bool {
	return s.ref.aecLow
}

// setAecLow is the generated setter for the aecLow field.
func (s *CPUReflect) setAecLow(v bool) error {
	s.ref.aecLow = v
	return nil
}

// getOpFlags is the generated getter for the opFlags.
func (s *CPUReflect) getOpFlags() uint8 {
	return s.ref.opFlags
}

// setOpFlags is the generated setter for the opFlags field.
func (s *CPUReflect) setOpFlags(v uint8) error {
	s.ref.opFlags = v
	return nil
}

// getLabel is the generated getter for the label.
func (s *CPUReflect) getLabel() string {
	return s.ref.label
}

// setLabel is the generated setter for the label field.
func (s *CPUReflect) setLabel(v string) error {
	s.ref.label = v
	return nil
}
