package mos6510_rev1

// Code generated by symphony-generator. DO NOT EDIT.

import (
	"errors"
	"github.com/markel1974/c64emu/src/references"
)

const (
	reflectFirstIrqCycleId = "firstIrqCycle"
	reflectFirstNMICycleId = "firstNMICycle"
	reflectNmiExecId       = "nmiExec"
	reflectIrqBreakerId    = "irqBreaker"
)

type InterruptsReflect struct {
	ref              *Interrupts
	outOfBoundsError error
	readOnlyError    error
}

func NewInterruptsReflect(r *Interrupts, factory references.IComponentFactory, parent references.IComponent, identifier string, instance int, hardwareId string) *InterruptsReflect {
	reflector := &InterruptsReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.BaseComponent.Register(factory, parent, identifier, instance, r, hardwareId)
	r.PropertyAdd(reflectFirstIrqCycleId, "FirstIrqCycle", false, reflector.getFirstIrqCycle, reflector.setFirstIrqCycle)

	r.PropertyAdd(reflectFirstNMICycleId, "FirstNMICycle", false, reflector.getFirstNMICycle, reflector.setFirstNMICycle)

	r.PropertyAdd(reflectNmiExecId, "NmiExec", false, reflector.getNmiExec, reflector.setNmiExec)

	r.PropertyAdd(reflectIrqBreakerId, "irqBreaker indicates whether the CPU's interrupt request is currently blocked.", false, reflector.getIrqBreaker, reflector.setIrqBreaker)

	_ = r.CommandAdd("HasNMI", "HasNMI() bool - HasNMI checks if the Non-Maskable Interrupt (NMI) bit is set and returns true if active, otherwise false.", r.HasNMI)
	_ = r.CommandAdd("TriggerIRQ", "TriggerIRQ(intr) - TriggerIRQ sets the specified IRQ bit and records the cycle if no IRQ has been set previously. It also updates interrupt flags.", r.TriggerIRQ)
	_ = r.CommandAdd("TriggerNMI", "TriggerNMI() - TriggerNMI sets the NMI (Non-Maskable Interrupt) bit and captures the cycle when the NMI was triggered if not already set.", r.TriggerNMI)
	_ = r.CommandAdd("TriggerReset", "TriggerReset() - TriggerReset sets the reset interrupt flag in the internal bitfield to signal a reset condition.", r.TriggerReset)
	_ = r.CommandAdd("ClearReset", "ClearReset() - ClearReset clears the reset interrupt bit by resetting the bit at the position defined by intrRstBit in i.all.", r.ClearReset)
	_ = r.CommandAdd("Emulate", "Emulate() - Emulate processes the internal state of the Interrupts instance during an emulation cycle.", r.Emulate)
	_ = r.CommandAdd("Reset", "Reset() - Reset reinitializes the Interrupts by clearing all internal state and resetting signals to their default values.", r.Reset)
	_ = r.CommandAdd("ClearNMI", "ClearNMI() - ClearNMI clears the NMI (Non-Maskable Interrupt) state, disabling its execution and clearing the associated bit.", r.ClearNMI)
	_ = r.CommandAdd("ClearIRQ", "ClearIRQ(intr) - ClearIRQ clears the specified interrupt request (IRQ) bit and updates related signals if necessary.", r.ClearIRQ)
	_ = r.CommandAdd("Compute", "Compute(iFlag, opFlags) bool - Compute evaluates and handles interrupt requests (IRQ, NMI, RESET) based on internal state and input flags.", r.Compute)
	_ = r.CommandAdd("HasIrqBreaker", "HasIrqBreaker() bool - HasIrqBreaker checks if the interrupt breaker is currently enabled, returning true if active, otherwise false.", r.HasIrqBreaker)

	return reflector
}

// getFirstIrqCycle is the generated getter for the firstIrqCycle.
func (s *InterruptsReflect) getFirstIrqCycle() uint64 {
	return s.ref.firstIrqCycle
}

// setFirstIrqCycle is the generated setter for the firstIrqCycle field.
func (s *InterruptsReflect) setFirstIrqCycle(v uint64) error {
	s.ref.firstIrqCycle = v
	return nil
}

// getFirstNMICycle is the generated getter for the firstNMICycle.
func (s *InterruptsReflect) getFirstNMICycle() uint64 {
	return s.ref.firstNMICycle
}

// setFirstNMICycle is the generated setter for the firstNMICycle field.
func (s *InterruptsReflect) setFirstNMICycle(v uint64) error {
	s.ref.firstNMICycle = v
	return nil
}

// getNmiExec is the generated getter for the nmiExec.
func (s *InterruptsReflect) getNmiExec() bool {
	return s.ref.nmiExec
}

// setNmiExec is the generated setter for the nmiExec field.
func (s *InterruptsReflect) setNmiExec(v bool) error {
	s.ref.nmiExec = v
	return nil
}

// getIrqBreaker is the generated getter for the irqBreaker.
func (s *InterruptsReflect) getIrqBreaker() bool {
	return s.ref.irqBreaker
}

// setIrqBreaker is the generated setter for the irqBreaker field.
func (s *InterruptsReflect) setIrqBreaker(v bool) error {
	s.ref.irqBreaker = v
	return nil
}
