package mos6510_rev1

// Code generated by symphony-generator. DO NOT EDIT.

import (
	"errors"
	"github.com/markel1974/symphony/src/references"
)

const (
	reflectStatusId = "status"
)

type BusReflect struct {
	ref              *Bus
	outOfBoundsError error
	readOnlyError    error
}

func NewBusReflect(r *Bus, factory references.IComponentFactory, parent references.IComponent, identifier string, instance int, hardwareId string) *BusReflect {
	reflector := &BusReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.BaseComponent.Register(factory, parent, identifier, instance, r, hardwareId)
	r.PropertyAdd(reflectStatusId, "Status", false, reflector.getStatus, reflector.setStatus)

	_ = r.CommandAdd("Emulate", "Emulate() - Emulate processes the internal state of the Interrupts instance during an emulation cycle.", r.Emulate)
	_ = r.CommandAdd("ReadDirect", "ReadDirect(addr) uint8 - ", r.ReadDirect)
	_ = r.CommandAdd("SetRDYLowMode", "SetRDYLowMode() - ", r.SetRDYLowMode)
	_ = r.CommandAdd("SetAECLowMode", "SetAECLowMode() - ", r.SetAECLowMode)
	_ = r.CommandAdd("SetNormalMode", "SetNormalMode() - ", r.SetNormalMode)
	_ = r.CommandAdd("Reset", "Reset() - Reset reinitializes the Interrupts by clearing all internal state and resetting signals to their default values.", r.Reset)

	return reflector
}

// getStatus is the generated getter for the status.
func (s *BusReflect) getStatus() uint8 {
	return s.ref.status
}

// setStatus is the generated setter for the status field.
func (s *BusReflect) setStatus(v uint8) error {
	s.ref.status = v
	return nil
}
