package c64_ram_rev1

// Code generated by symphony-generator. DO NOT EDIT.

import "errors"

const (
	ramId = "ram"
)

type RamReflect struct {
	ref *Ram
}

func NewRamReflect(r *Ram) *RamReflect {
	reflector := &RamReflect{ref: r}
	r.PropertyAdd(ramId, "ram is a byte slice representing the memory storage of the RAM component.", false, reflector.getRam, reflector.setRam)
	_ = r.CommandAdd("setRamEntry", "ram is a byte slice representing the memory storage of the RAM component.", reflector.setRamEntry)
	_ = r.CommandAdd("getRamEntry", "ram is a byte slice representing the memory storage of the RAM component.", reflector.getRamEntry)
	return reflector
}

// getRam is the generated getter for the ram.
func (s *RamReflect) getRam() []uint8 {
	return s.ref.ram
}

// setRam is the generated setter for the ram field.
func (s *RamReflect) setRam(v []uint8) error {
	copy(s.ref.ram, v)
	return nil
}

// getRamEntry is the generated indexed getter for the ram.
func (s *RamReflect) getRamEntry(idx int) uint8 {
	if idx >= 0 && idx < len(s.ref.ram) {
		return s.ref.ram[idx]
	}
	return *new(uint8)
}

// setRamEntry is the generated indexed setter for the ram.
func (s *RamReflect) setRamEntry(idx int, v uint8) error {
	if idx >= 0 && idx < len(s.ref.ram) {
		s.ref.ram[idx] = v
		return nil
	}
	return errors.New("index out of bounds")
}
