package c64_ram_rev1

// Code generated by symphony-generator. DO NOT EDIT.

import "errors"

const (
	ramId = "ram"
)

type RamReflect struct {
	ref *Ram
	err error
}

func NewRamReflect(r *Ram) *RamReflect {
	reflector := &RamReflect{ref: r}
	r.PropertyAdd(ramId, "ram is a byte slice representing the memory storage of the RAM component.", false, reflector.getRam, reflector.setRam)

	_ = r.CommandAdd("getRamEntry", "ram is a byte slice representing the memory storage of the RAM component.", reflector.getRamEntry)
	_ = r.CommandAdd("setRamEntry", "ram is a byte slice representing the memory storage of the RAM component.", reflector.setRamEntry)

	_ = r.CommandAdd("Emulate", "Emulate() Emulate performs the main emulation logic for the Ram component during a simulation cycle.", r.Emulate)
	_ = r.CommandAdd("Read", "Read(addr) Read retrieves a byte from the RAM at the specified memory address.", r.Read)
	_ = r.CommandAdd("Size", "Size() Size returns the length of the `ram` slice, representing the total size of the RAM in bytes.", r.Size)
	_ = r.CommandAdd("Reset", "Reset() Reset clears and reinitializes the RAM to its default state as defined during setup.", r.Reset)
	_ = r.CommandAdd("Write", "Write(addr, data) Write stores the provided data byte at the specified memory address in the RAM.", r.Write)

	return reflector
}

// getRam is the generated getter for the ram.
func (s *RamReflect) getRam() []uint8 {
	return s.ref.ram
}

// setRam is the generated setter for the ram field.
func (s *RamReflect) setRam(v []uint8) error {
	copy(s.ref.ram, v)
	return nil
}

// getRamEntry is the generated indexed getter for the ram.
func (s *RamReflect) getRamEntry(idx int) (uint8, error) {
	if idx >= 0 && idx < len(s.ref.ram) {
		return s.ref.ram[idx], nil
	}
	return *new(uint8), errors.New("index out of bounds")
}

// setRamEntry is the generated indexed setter for the ram.
func (s *RamReflect) setRamEntry(idx int, v uint8) error {
	if idx >= 0 && idx < len(s.ref.ram) {
		s.ref.ram[idx] = v
		return nil
	}
	return errors.New("index out of bounds")
}
