package mos6581

// Code generated by symphony-generator. DO NOT EDIT.

import (
	"errors"
	"github.com/markel1974/c64emu/src/references"
)

const (
	reflectVoiceNumberId = "voiceNumber"
)

type VoicesReflect struct {
	ref              *Voices
	outOfBoundsError error
	readOnlyError    error
}

func NewVoicesReflect(r *Voices, factory references.IComponentFactory, parent references.IComponent, identifier string, instance int, hardwareId string) *VoicesReflect {
	reflector := &VoicesReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.BaseComponent.Register(factory, parent, identifier, instance, r, hardwareId)
	r.PropertyAdd(reflectVoiceNumberId, "VoiceNumber", false, reflector.getVoiceNumber, reflector.setVoiceNumber)

	_ = r.CommandAdd("WriteVoice0UpdateFreqA", "WriteVoice0UpdateFreqA(_, data) - WriteVoice0UpdateFreqA updates the frequency parameter A for voice 0 using the provided 8-bit data value.", r.WriteVoice0UpdateFreqA)
	_ = r.CommandAdd("WriteVoice2UpdatePulseWidthB", "WriteVoice2UpdatePulseWidthB(_, data) - WriteVoice2UpdatePulseWidthB updates the pulse width parameter B for voice 2 with the provided data.", r.WriteVoice2UpdatePulseWidthB)
	_ = r.CommandAdd("WriteVoice0UpdateFreqB", "WriteVoice0UpdateFreqB(_, data) - WriteVoice0UpdateFreqB updates the frequency parameter B for voice 0 using the provided data value.", r.WriteVoice0UpdateFreqB)
	_ = r.CommandAdd("WriteVoice0UpdateWaveForm", "WriteVoice0UpdateWaveForm(_, data) - WriteVoice0UpdateWaveForm updates the waveform data for voice 0 by delegating the operation to its UpdateWaveForm method.", r.WriteVoice0UpdateWaveForm)
	_ = r.CommandAdd("WriteVoice0UpdatePulseWidthA", "WriteVoice0UpdatePulseWidthA(_, data) - WriteVoice0UpdatePulseWidthA updates the pulse width A parameter for voice 0 using the provided 8-bit data.", r.WriteVoice0UpdatePulseWidthA)
	_ = r.CommandAdd("WriteVoice1UpdateFreqB", "WriteVoice1UpdateFreqB(_, data) - WriteVoice1UpdateFreqB updates the frequency parameter B for voice 1 using the provided data value.", r.WriteVoice1UpdateFreqB)
	_ = r.CommandAdd("WriteVoice1UpdatePulseWidthA", "WriteVoice1UpdatePulseWidthA(_, data) - WriteVoice1UpdatePulseWidthA updates the pulse width parameter A for voice 1 with the provided data.", r.WriteVoice1UpdatePulseWidthA)
	_ = r.CommandAdd("SetFilterVoice0", "SetFilterVoice0(f0) - SetFilterVoice0 modifies the filter setting for voice 0 using the specified filter value f0.", r.SetFilterVoice0)
	_ = r.CommandAdd("SetMuteVoice2", "SetMuteVoice2(data) - SetMuteVoice2 sets the mute state of voice 2 based on the boolean parameter m.", r.SetMuteVoice2)
	_ = r.CommandAdd("Emulate", "Emulate() - Emulate generates a simulated behavior or operation based on the current state of the Voices instance.", r.Emulate)
	_ = r.CommandAdd("WriteVoice1UpdateFreqA", "WriteVoice1UpdateFreqA(_, data) - WriteVoice1UpdateFreqA updates the frequency A of voice 1 using the provided 8-bit data value.", r.WriteVoice1UpdateFreqA)
	_ = r.CommandAdd("WriteVoice1UpdateWaveForm", "WriteVoice1UpdateWaveForm(_, data) - WriteVoice1UpdateWaveForm updates the waveform configuration for voice 1 using the provided data value.", r.WriteVoice1UpdateWaveForm)
	_ = r.CommandAdd("WriteVoice1UpdateSustainLevel", "WriteVoice1UpdateSustainLevel(_, data) - WriteVoice1UpdateSustainLevel updates the sustain level of voice 1 using the provided data.", r.WriteVoice1UpdateSustainLevel)
	_ = r.CommandAdd("Compute", "Compute() int32,int32 - Compute calculates and returns the summed output of filtered and non-filtered voices in int32 format.", r.Compute)
	_ = r.CommandAdd("WriteVoice0UpdatePulseWidthB", "WriteVoice0UpdatePulseWidthB(_, data) - WriteVoice0UpdatePulseWidthB updates the pulse width B parameter for voice 0 with the provided data.", r.WriteVoice0UpdatePulseWidthB)
	_ = r.CommandAdd("WriteVoice1UpdatePulseWidthB", "WriteVoice1UpdatePulseWidthB(_, data) - WriteVoice1UpdatePulseWidthB updates the pulse width parameter B of voice 1 with the specified data value.", r.WriteVoice1UpdatePulseWidthB)
	_ = r.CommandAdd("WriteVoice2UpdateFreqA", "WriteVoice2UpdateFreqA(_, data) - WriteVoice2UpdateFreqA updates the frequency parameter A for voice 2 with the provided data.", r.WriteVoice2UpdateFreqA)
	_ = r.CommandAdd("SetFilters", "SetFilters(data) - SetFilters sets the filter values for all three voices using the provided parameters f1, f2, and f3 respectively.", r.SetFilters)
	_ = r.CommandAdd("WriteVoice0UpdateSustainLevel", "WriteVoice0UpdateSustainLevel(_, data) - WriteVoice0UpdateSustainLevel updates the sustain level of the first voice (voice 0) with the given data value.", r.WriteVoice0UpdateSustainLevel)
	_ = r.CommandAdd("SetFilterVoice1", "SetFilterVoice1(f1) - SetFilterVoice1 configures the filter state for voice 1 using the provided filter value f1.", r.SetFilterVoice1)
	_ = r.CommandAdd("SetFilterVoice2", "SetFilterVoice2(f2) - SetFilterVoice2 sets the filter state for voice 2 using the specified filter value.", r.SetFilterVoice2)
	_ = r.CommandAdd("WriteVoice1UpdateEnvelopeGenerators", "WriteVoice1UpdateEnvelopeGenerators(_, data) - WriteVoice1UpdateEnvelopeGenerators updates the envelope generators for voice 1 using the provided data.", r.WriteVoice1UpdateEnvelopeGenerators)
	_ = r.CommandAdd("WriteVoice2UpdatePulseWidthA", "WriteVoice2UpdatePulseWidthA(_, data) - WriteVoice2UpdatePulseWidthA updates the pulse width A register of voice 2 with the specified data.", r.WriteVoice2UpdatePulseWidthA)
	_ = r.CommandAdd("WriteVoice2UpdateWaveForm", "WriteVoice2UpdateWaveForm(_, data) - WriteVoice2UpdateWaveForm updates the waveform of the second voice using the provided data value.", r.WriteVoice2UpdateWaveForm)
	_ = r.CommandAdd("WriteVoice2UpdateEnvelopeGenerators", "WriteVoice2UpdateEnvelopeGenerators(_, data) - WriteVoice2UpdateEnvelopeGenerators updates the envelope generator state for the third voice with the provided data.", r.WriteVoice2UpdateEnvelopeGenerators)
	_ = r.CommandAdd("ReadVoice2Waveform", "ReadVoice2Waveform(_) uint8 - ReadVoice2Waveform retrieves the MSB of the current oscillator output (waveform) for voice 2, derived from ComputeWaveForm.", r.ReadVoice2Waveform)
	_ = r.CommandAdd("ReadVoice2EgLevel", "ReadVoice2EgLevel(_) uint8 - ReadVoice2EgLevel reads the most significant byte (MSB) of the current envelope generator level for voice 2.", r.ReadVoice2EgLevel)
	_ = r.CommandAdd("Reset", "Reset() - Reset resets the state of all voices in the collection by calling their individual Reset methods.", r.Reset)
	_ = r.CommandAdd("WriteVoice2UpdateFreqB", "WriteVoice2UpdateFreqB(_, data) - WriteVoice2UpdateFreqB updates the frequency parameter B for the third voice using the provided data byte.", r.WriteVoice2UpdateFreqB)
	_ = r.CommandAdd("WriteVoice2UpdateSustainLevel", "WriteVoice2UpdateSustainLevel(_, data) - WriteVoice2UpdateSustainLevel updates the sustain level parameter for voice 2 using the provided data.", r.WriteVoice2UpdateSustainLevel)

	return reflector
}

// getVoiceNumber is the generated getter for the voiceNumber.
func (s *VoicesReflect) getVoiceNumber() int {
	return s.ref.voiceNumber
}

// setVoiceNumber is the generated setter for the voiceNumber field.
func (s *VoicesReflect) setVoiceNumber(v int) error {
	s.ref.voiceNumber = v
	return nil
}
