package mos6581

// Code generated by symphony-generator. DO NOT EDIT.

import (
	"errors"
	"github.com/markel1974/symphony/src/references"
)

const (
	reflectLabelId                     = "label"
	reflectRegistersId                 = "registers"
	reflectVolumeId                    = "volume"
	reflectSampleBufId                 = "sampleBuf"
	reflectSampleBufIdxId              = "sampleBufIdx"
	reflectAudioSamplesPerVolumeStepId = "audioSamplesPerVolumeStep"
)

type SIDReflect struct {
	ref              *SID
	outOfBoundsError error
	readOnlyError    error
}

func NewSIDReflect(r *SID, factory references.IComponentFactory, parent references.IComponent, identifier string, instance int, hardwareId string) *SIDReflect {
	reflector := &SIDReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.BaseComponent.Register(factory, parent, identifier, instance, r, hardwareId)
	r.PropertyAdd(reflectLabelId, "Label", false, reflector.getLabel, reflector.setLabel)

	r.PropertyAdd(reflectRegistersId, "Registers", false, reflector.getRegisters, reflector.setRegisters)

	_ = r.CommandAdd("getRegistersEntry", "Registers", reflector.getRegistersEntry)
	_ = r.CommandAdd("setRegistersEntry", "Registers", reflector.setRegistersEntry)

	r.PropertyAdd(reflectVolumeId, "Master volume", false, reflector.getVolume, reflector.setVolume)

	r.PropertyAdd(reflectSampleBufId, "Buffer for sampled voices", false, reflector.getSampleBuf, reflector.setSampleBuf)

	_ = r.CommandAdd("getSampleBufEntry", "Buffer for sampled voices", reflector.getSampleBufEntry)
	_ = r.CommandAdd("setSampleBufEntry", "Buffer for sampled voices", reflector.setSampleBufEntry)

	r.PropertyAdd(reflectSampleBufIdxId, "index in sample_buf for writing", false, reflector.getSampleBufIdx, reflector.setSampleBufIdx)

	r.PropertyAdd(reflectAudioSamplesPerVolumeStepId, "AudioSamplesPerVolumeStep", false, reflector.getAudioSamplesPerVolumeStep, reflector.setAudioSamplesPerVolumeStep)

	_ = r.CommandAdd("Reset", "Reset() - Reset reinitializes the SID object by clearing its registers, buffers, and resetting all internal components to defaults.", r.Reset)
	_ = r.CommandAdd("Prepare", "Prepare() - Prepare updates the sample buffer with the current volume and increments the buffer index circularly.", r.Prepare)
	_ = r.CommandAdd("SetPotY", "SetPotY(pot) - SetPotY sets the pot value for the Y-axis register of the SID. This value updates the corresponding SID register directly.", r.SetPotY)
	_ = r.CommandAdd("Update", "Update() - Update processes the sound buffer and writes updated sound data to the audio player.", r.Update)
	_ = r.CommandAdd("SetPotX", "SetPotX(pot) - SetPotX sets the value of the POTX (paddle) register to control the position of the X-axis paddle input.", r.SetPotX)
	_ = r.CommandAdd("WriteMasterVolumeAndFilterType", "WriteMasterVolumeAndFilterType(_, data) - WriteMasterVolumeAndFilterType updates 'master' volume, filter type, and mute state based on the given input data.", r.WriteMasterVolumeAndFilterType)
	_ = r.CommandAdd("Emulate", "Emulate() - Emulate executes the emulation process for the SID object, simulating its behavior according to the defined parameters.", r.Emulate)
	_ = r.CommandAdd("ReadDefault", "ReadDefault(reg) uint8 - ReadDefault reads the value from the specified SID register address, normalized within the valid register range.", r.ReadDefault)
	_ = r.CommandAdd("WriteDefault", "WriteDefault(_, _) - WriteDefault is a default writing handler for SID registers that performs no operation when invoked.", r.WriteDefault)
	_ = r.CommandAdd("WriteFiltersRegister", "WriteFiltersRegister(_, data) - WriteFiltersRegister configures filter settings for the SID voices based on the provided data value.", r.WriteFiltersRegister)
	_ = r.CommandAdd("ReadRegister", "ReadRegister(addr) uint8 - ReadRegister reads the value of a specified SID register identified by the provided address.", r.ReadRegister)
	_ = r.CommandAdd("WriteRegister", "WriteRegister(addr, data) - WriteRegister writes a value to a specific register within the range of the SID's addressable space.", r.WriteRegister)

	return reflector
}

// getLabel is the generated getter for the label.
func (s *SIDReflect) getLabel() string {
	return s.ref.label
}

// setLabel is the generated setter for the label field.
func (s *SIDReflect) setLabel(v string) error {
	s.ref.label = v
	return nil
}

// getRegisters is the generated getter for the registers.
func (s *SIDReflect) getRegisters() []uint8 {
	return s.ref.registers
}

// setRegisters is the generated setter for the registers field.
func (s *SIDReflect) setRegisters(v []uint8) error {
	copy(s.ref.registers, v)
	return nil
}

// getRegistersEntry is the generated indexed getter for the registers.
func (s *SIDReflect) getRegistersEntry(idx int) (uint8, error) {
	if idx >= 0 && idx < len(s.ref.registers) {
		return s.ref.registers[idx], nil
	}
	return *new(uint8), s.outOfBoundsError
}

// setRegistersEntry is the generated indexed setter for the registers.
func (s *SIDReflect) setRegistersEntry(idx int, v uint8) error {
	if idx >= 0 && idx < len(s.ref.registers) {
		s.ref.registers[idx] = v
		return nil
	}
	return errors.New("index out of bounds")
}

// getVolume is the generated getter for the volume.
func (s *SIDReflect) getVolume() uint8 {
	return s.ref.volume
}

// setVolume is the generated setter for the volume field.
func (s *SIDReflect) setVolume(v uint8) error {
	s.ref.volume = v
	return nil
}

// getSampleBuf is the generated getter for the sampleBuf.
func (s *SIDReflect) getSampleBuf() []uint8 {
	return s.ref.sampleBuf
}

// setSampleBuf is the generated setter for the sampleBuf field.
func (s *SIDReflect) setSampleBuf(v []uint8) error {
	copy(s.ref.sampleBuf, v)
	return nil
}

// getSampleBufEntry is the generated indexed getter for the sampleBuf.
func (s *SIDReflect) getSampleBufEntry(idx int) (uint8, error) {
	if idx >= 0 && idx < len(s.ref.sampleBuf) {
		return s.ref.sampleBuf[idx], nil
	}
	return *new(uint8), s.outOfBoundsError
}

// setSampleBufEntry is the generated indexed setter for the sampleBuf.
func (s *SIDReflect) setSampleBufEntry(idx int, v uint8) error {
	if idx >= 0 && idx < len(s.ref.sampleBuf) {
		s.ref.sampleBuf[idx] = v
		return nil
	}
	return errors.New("index out of bounds")
}

// getSampleBufIdx is the generated getter for the sampleBufIdx.
func (s *SIDReflect) getSampleBufIdx() int {
	return s.ref.sampleBufIdx
}

// setSampleBufIdx is the generated setter for the sampleBufIdx field.
func (s *SIDReflect) setSampleBufIdx(v int) error {
	s.ref.sampleBufIdx = v
	return nil
}

// getAudioSamplesPerVolumeStep is the generated getter for the audioSamplesPerVolumeStep.
func (s *SIDReflect) getAudioSamplesPerVolumeStep() float64 {
	return s.ref.audioSamplesPerVolumeStep
}

// setAudioSamplesPerVolumeStep is the generated setter for the audioSamplesPerVolumeStep field.
func (s *SIDReflect) setAudioSamplesPerVolumeStep(v float64) error {
	s.ref.audioSamplesPerVolumeStep = v
	return nil
}
