package mos6581

// Code generated by symphony-generator. DO NOT EDIT.

import (
	"errors"
	"github.com/markel1974/symphony/src/references"
)

const (
	reflectNumberId    = "number"
	reflectWaveId      = "wave"
	reflectEgStateId   = "egState"
	reflectCountId     = "count"
	reflectAddId       = "add"
	reflectFreqId      = "freq"
	reflectPwId        = "pw"
	reflectAAddId      = "aAdd"
	reflectDSubId      = "dSub"
	reflectSLevelId    = "sLevel"
	reflectRSubId      = "rSub"
	reflectEgLevelId   = "egLevel"
	reflectGateId      = "gate"
	reflectRingId      = "ring"
	reflectTestId      = "test"
	reflectFilterId    = "filter"
	reflectSyncId      = "sync"
	reflectNoiseLFSRId = "noiseLFSR"
	reflectMuteId      = "mute"
)

type VoiceReflect struct {
	ref              *Voice
	outOfBoundsError error
	readOnlyError    error
}

func NewVoiceReflect(r *Voice, factory references.IComponentFactory, parent references.IComponent, identifier string, instance int, hardwareId string) *VoiceReflect {
	reflector := &VoiceReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.BaseComponent.Register(factory, parent, identifier, instance, r, hardwareId)
	r.PropertyAdd(reflectNumberId, "number represents the numerical identifier of the voice in the synthesizer.", false, reflector.getNumber, reflector.setNumber)

	r.PropertyAdd(reflectWaveId, "Selected waveform", false, reflector.getWave, reflector.setWave)

	r.PropertyAdd(reflectEgStateId, "Current state of EG", false, reflector.getEgState, reflector.setEgState)

	r.PropertyAdd(reflectCountId, "Counter for waveform generator, 8.16 fixed", false, reflector.getCount, reflector.setCount)

	r.PropertyAdd(reflectAddId, "Added to the counter in every frame", false, reflector.getAdd, reflector.setAdd)

	r.PropertyAdd(reflectFreqId, "SID frequency value", false, reflector.getFreq, reflector.setFreq)

	r.PropertyAdd(reflectPwId, "SID pulse-width value", false, reflector.getPw, reflector.setPw)

	r.PropertyAdd(reflectAAddId, "EG parameters", false, reflector.getAAdd, reflector.setAAdd)

	r.PropertyAdd(reflectDSubId, "dSub is the decrement value for the decay phase of the envelope generator.", false, reflector.getDSub, reflector.setDSub)

	r.PropertyAdd(reflectSLevelId, "sLevel represents the sustain level of the envelope generator.", false, reflector.getSLevel, reflector.setSLevel)

	r.PropertyAdd(reflectRSubId, "rSub is the decrement value for the release phase of the envelope generator.", false, reflector.getRSub, reflector.setRSub)

	r.PropertyAdd(reflectEgLevelId, "Current EG level, 8.16 fixed", false, reflector.getEgLevel, reflector.setEgLevel)

	r.PropertyAdd(reflectGateId, "EG gate bit", false, reflector.getGate, reflector.setGate)

	r.PropertyAdd(reflectRingId, "Ring modulation bit", false, reflector.getRing, reflector.setRing)

	r.PropertyAdd(reflectTestId, "Test bit", false, reflector.getTest, reflector.setTest)

	r.PropertyAdd(reflectFilterId, "Flag: Voice filtered", false, reflector.getFilter, reflector.setFilter)

	r.PropertyAdd(reflectSyncId, "The following bit is set for the modulating voices, not for the modulated one (as the SID bits)", false, reflector.getSync, reflector.setSync)

	r.PropertyAdd(reflectNoiseLFSRId, "NoiseLFSR", false, reflector.getNoiseLFSR, reflector.setNoiseLFSR)

	r.PropertyAdd(reflectMuteId, "Mute", false, reflector.getMute, reflector.setMute)

	_ = r.CommandAdd("ReadFilter", "ReadFilter() uint8 - ReadFilter returns the filter value associated with the Voice instance as an unsigned 8-bit integer.", r.ReadFilter)
	_ = r.CommandAdd("WriteMute", "WriteMute(m) - ", r.WriteMute)
	_ = r.CommandAdd("WriteEnvelopeGenerators", "WriteEnvelopeGenerators(data) - WriteEnvelopeGenerators updates the envelope generator parameters based on the provided data.  The method computes attack and decay values using the egLut function and updates the relevant fields.", r.WriteEnvelopeGenerators)
	_ = r.CommandAdd("ReadEgLevel", "ReadEgLevel() uint32 - ReadEgLevel returns the current envelope generator level of the Voice as uint32.", r.ReadEgLevel)
	_ = r.CommandAdd("WriteFreqB", "WriteFreqB(data) - WriteFreqB updates the high byte of the frequency value and recalculates the added value based on the updated frequency.", r.WriteFreqB)
	_ = r.CommandAdd("WriteSustainLevel", "WriteSustainLevel(data) - WriteSustainLevel adjusts the sustain level and release sublevel of the voice based on the provided data value.", r.WriteSustainLevel)
	_ = r.CommandAdd("Reset", "Reset() - Reset reinitializes all properties of the Voice object to their default states.", r.Reset)
	_ = r.CommandAdd("ComputeWaveForm", "ComputeWaveForm() uint16 - ComputeWaveForm generates and returns a waveform value based on the current wave index and test mode of the voice.", r.ComputeWaveForm)
	_ = r.CommandAdd("WriteFilter", "WriteFilter(f) - WriteFilter sets the filter value for the Voice instance.", r.WriteFilter)
	_ = r.CommandAdd("WriteWaveForm", "WriteWaveForm(data) - WriteWaveForm updates the waveform type and state flags based on the provided data byte.  It adjusts gate, sync, ring, and test flags and manages the envelope generator's state accordingly.", r.WriteWaveForm)
	_ = r.CommandAdd("Emulate", "Emulate() - Emulate triggers the simulated behavior or action specific to the Voice instance.", r.Emulate)
	_ = r.CommandAdd("WriteFreqA", "WriteFreqA(data) - WriteFreqA updates the lower 8 bits of the frequency value and recalculates the additive frequency increment.", r.WriteFreqA)
	_ = r.CommandAdd("WritePulseWidthB", "WritePulseWidthB(data) - WritePulseWidthB updates the high nibble of the pulse width value using the provided 8-bit data.", r.WritePulseWidthB)
	_ = r.CommandAdd("ComputeCount", "ComputeCount() - ComputeCount updates the count value for a Voice instance based on specific conditions related to test, sync, and max value.", r.ComputeCount)
	_ = r.CommandAdd("ComputeEnvelopeGenerators", "ComputeEnvelopeGenerators() - ComputeEnvelopeGenerators evaluates and progresses the envelope generators based on the current state or freezes them if TEST is active.", r.ComputeEnvelopeGenerators)
	_ = r.CommandAdd("ReadIsMuted", "ReadIsMuted() bool - ReadIsMuted checks if the voice is currently in a muted state and returns true if muted, otherwise false.", r.ReadIsMuted)
	_ = r.CommandAdd("WritePulseWidthA", "WritePulseWidthA(data) - WritePulseWidthA updates the lower 8 bits of the pulse width (pw) with the provided 8-bit data value.", r.WritePulseWidthA)

	return reflector
}

// getNumber is the generated getter for the number.
func (s *VoiceReflect) getNumber() uint8 {
	return s.ref.number
}

// setNumber is the generated setter for the number field.
func (s *VoiceReflect) setNumber(v uint8) error {
	s.ref.number = v
	return nil
}

// getWave is the generated getter for the wave.
func (s *VoiceReflect) getWave() int {
	return s.ref.wave
}

// setWave is the generated setter for the wave field.
func (s *VoiceReflect) setWave(v int) error {
	s.ref.wave = v
	return nil
}

// getEgState is the generated getter for the egState.
func (s *VoiceReflect) getEgState() int {
	return s.ref.egState
}

// setEgState is the generated setter for the egState field.
func (s *VoiceReflect) setEgState(v int) error {
	s.ref.egState = v
	return nil
}

// getCount is the generated getter for the count.
func (s *VoiceReflect) getCount() uint32 {
	return s.ref.count
}

// setCount is the generated setter for the count field.
func (s *VoiceReflect) setCount(v uint32) error {
	s.ref.count = v
	return nil
}

// getAdd is the generated getter for the add.
func (s *VoiceReflect) getAdd() uint32 {
	return s.ref.add
}

// setAdd is the generated setter for the add field.
func (s *VoiceReflect) setAdd(v uint32) error {
	s.ref.add = v
	return nil
}

// getFreq is the generated getter for the freq.
func (s *VoiceReflect) getFreq() uint16 {
	return s.ref.freq
}

// setFreq is the generated setter for the freq field.
func (s *VoiceReflect) setFreq(v uint16) error {
	s.ref.freq = v
	return nil
}

// getPw is the generated getter for the pw.
func (s *VoiceReflect) getPw() uint16 {
	return s.ref.pw
}

// setPw is the generated setter for the pw field.
func (s *VoiceReflect) setPw(v uint16) error {
	s.ref.pw = v
	return nil
}

// getAAdd is the generated getter for the aAdd.
func (s *VoiceReflect) getAAdd() uint32 {
	return s.ref.aAdd
}

// setAAdd is the generated setter for the aAdd field.
func (s *VoiceReflect) setAAdd(v uint32) error {
	s.ref.aAdd = v
	return nil
}

// getDSub is the generated getter for the dSub.
func (s *VoiceReflect) getDSub() uint32 {
	return s.ref.dSub
}

// setDSub is the generated setter for the dSub field.
func (s *VoiceReflect) setDSub(v uint32) error {
	s.ref.dSub = v
	return nil
}

// getSLevel is the generated getter for the sLevel.
func (s *VoiceReflect) getSLevel() uint32 {
	return s.ref.sLevel
}

// setSLevel is the generated setter for the sLevel field.
func (s *VoiceReflect) setSLevel(v uint32) error {
	s.ref.sLevel = v
	return nil
}

// getRSub is the generated getter for the rSub.
func (s *VoiceReflect) getRSub() uint32 {
	return s.ref.rSub
}

// setRSub is the generated setter for the rSub field.
func (s *VoiceReflect) setRSub(v uint32) error {
	s.ref.rSub = v
	return nil
}

// getEgLevel is the generated getter for the egLevel.
func (s *VoiceReflect) getEgLevel() uint32 {
	return s.ref.egLevel
}

// setEgLevel is the generated setter for the egLevel field.
func (s *VoiceReflect) setEgLevel(v uint32) error {
	s.ref.egLevel = v
	return nil
}

// getGate is the generated getter for the gate.
func (s *VoiceReflect) getGate() uint8 {
	return s.ref.gate
}

// setGate is the generated setter for the gate field.
func (s *VoiceReflect) setGate(v uint8) error {
	s.ref.gate = v
	return nil
}

// getRing is the generated getter for the ring.
func (s *VoiceReflect) getRing() uint8 {
	return s.ref.ring
}

// setRing is the generated setter for the ring field.
func (s *VoiceReflect) setRing(v uint8) error {
	s.ref.ring = v
	return nil
}

// getTest is the generated getter for the test.
func (s *VoiceReflect) getTest() uint8 {
	return s.ref.test
}

// setTest is the generated setter for the test field.
func (s *VoiceReflect) setTest(v uint8) error {
	s.ref.test = v
	return nil
}

// getFilter is the generated getter for the filter.
func (s *VoiceReflect) getFilter() uint8 {
	return s.ref.filter
}

// setFilter is the generated setter for the filter field.
func (s *VoiceReflect) setFilter(v uint8) error {
	s.ref.filter = v
	return nil
}

// getSync is the generated getter for the sync.
func (s *VoiceReflect) getSync() uint8 {
	return s.ref.sync
}

// setSync is the generated setter for the sync field.
func (s *VoiceReflect) setSync(v uint8) error {
	s.ref.sync = v
	return nil
}

// getNoiseLFSR is the generated getter for the noiseLFSR.
func (s *VoiceReflect) getNoiseLFSR() uint32 {
	return s.ref.noiseLFSR
}

// setNoiseLFSR is the generated setter for the noiseLFSR field.
func (s *VoiceReflect) setNoiseLFSR(v uint32) error {
	s.ref.noiseLFSR = v
	return nil
}

// getMute is the generated getter for the mute.
func (s *VoiceReflect) getMute() bool {
	return s.ref.mute
}

// setMute is the generated setter for the mute field.
func (s *VoiceReflect) setMute(v bool) error {
	s.ref.mute = v
	return nil
}
