package stdlib

import (
	"math"

	"github.com/markel1974/c64emu/src/kernel/vm/objects"
)

var mathModule = map[string]objects.IObject{
	"e":         objects.NewFloat(math.E),
	"pi":        objects.NewFloat(math.Pi),
	"phi":       objects.NewFloat(math.Phi),
	"sqrt2":     objects.NewFloat(math.Sqrt2),
	"sqrtE":     objects.NewFloat(math.SqrtE),
	"sqrtPi":    objects.NewFloat(math.SqrtPi),
	"sqrtPhi":   objects.NewFloat(math.SqrtPhi),
	"ln2":       objects.NewFloat(math.Ln2),
	"log2E":     objects.NewFloat(math.Log2E),
	"ln10":      objects.NewFloat(math.Ln10),
	"log10E":    objects.NewFloat(math.Log10E),
	"abs":       objects.NewUserFunction("abs", objects.FuncAFRF(math.Abs)),
	"acos":      objects.NewUserFunction("acos", objects.FuncAFRF(math.Acos)),
	"acosh":     objects.NewUserFunction("acosh", objects.FuncAFRF(math.Acosh)),
	"asin":      objects.NewUserFunction("asin", objects.FuncAFRF(math.Asin)),
	"asinh":     objects.NewUserFunction("asinh", objects.FuncAFRF(math.Asinh)),
	"atan":      objects.NewUserFunction("atan", objects.FuncAFRF(math.Atan)),
	"atan2":     objects.NewUserFunction("atan2", objects.FuncAFFRF(math.Atan2)),
	"atanh":     objects.NewUserFunction("atanh", objects.FuncAFRF(math.Atanh)),
	"cbrt":      objects.NewUserFunction("cbrt", objects.FuncAFRF(math.Cbrt)),
	"ceil":      objects.NewUserFunction("ceil", objects.FuncAFRF(math.Ceil)),
	"copysign":  objects.NewUserFunction("copysign", objects.FuncAFFRF(math.Copysign)),
	"cos":       objects.NewUserFunction("cos", objects.FuncAFRF(math.Cos)),
	"cosh":      objects.NewUserFunction("cosh", objects.FuncAFRF(math.Cosh)),
	"dim":       objects.NewUserFunction("dim", objects.FuncAFFRF(math.Dim)),
	"erf":       objects.NewUserFunction("erf", objects.FuncAFRF(math.Erf)),
	"erfc":      objects.NewUserFunction("erfc", objects.FuncAFRF(math.Erfc)),
	"exp":       objects.NewUserFunction("exp", objects.FuncAFRF(math.Exp)),
	"exp2":      objects.NewUserFunction("exp2", objects.FuncAFRF(math.Exp2)),
	"expm1":     objects.NewUserFunction("expm1", objects.FuncAFRF(math.Expm1)),
	"floor":     objects.NewUserFunction("floor", objects.FuncAFRF(math.Floor)),
	"gamma":     objects.NewUserFunction("gamma", objects.FuncAFRF(math.Gamma)),
	"hypot":     objects.NewUserFunction("hypot", objects.FuncAFFRF(math.Hypot)),
	"ilogb":     objects.NewUserFunction("ilogb", objects.FuncAFRI(math.Ilogb)),
	"inf":       objects.NewUserFunction("inf", objects.FuncAIRF(math.Inf)),
	"is_inf":    objects.NewUserFunction("is_inf", objects.FuncAFIRB(math.IsInf)),
	"is_nan":    objects.NewUserFunction("is_nan", objects.FuncAFRB(math.IsNaN)),
	"j0":        objects.NewUserFunction("j0", objects.FuncAFRF(math.J0)),
	"j1":        objects.NewUserFunction("j1", objects.FuncAFRF(math.J1)),
	"jn":        objects.NewUserFunction("jn", objects.FuncAIFRF(math.Jn)),
	"ldexp":     objects.NewUserFunction("ldexp", objects.FuncAFIRF(math.Ldexp)),
	"log":       objects.NewUserFunction("log", objects.FuncAFRF(math.Log)),
	"log10":     objects.NewUserFunction("log10", objects.FuncAFRF(math.Log10)),
	"log1p":     objects.NewUserFunction("log1p", objects.FuncAFRF(math.Log1p)),
	"log2":      objects.NewUserFunction("log2", objects.FuncAFRF(math.Log2)),
	"logb":      objects.NewUserFunction("logb", objects.FuncAFRF(math.Logb)),
	"max":       objects.NewUserFunction("max", objects.FuncAFFRF(math.Max)),
	"min":       objects.NewUserFunction("min", objects.FuncAFFRF(math.Min)),
	"mod":       objects.NewUserFunction("mod", objects.FuncAFFRF(math.Mod)),
	"nan":       objects.NewUserFunction("nan", objects.FuncARF(math.NaN)),
	"nextafter": objects.NewUserFunction("nextafter", objects.FuncAFFRF(math.Nextafter)),
	"pow":       objects.NewUserFunction("pow", objects.FuncAFFRF(math.Pow)),
	"pow10":     objects.NewUserFunction("pow10", objects.FuncAIRF(math.Pow10)),
	"remainder": objects.NewUserFunction("remainder", objects.FuncAFFRF(math.Remainder)),
	"signbit":   objects.NewUserFunction("signbit", objects.FuncAFRB(math.Signbit)),
	"sin":       objects.NewUserFunction("sin", objects.FuncAFRF(math.Sin)),
	"sinh":      objects.NewUserFunction("sinh", objects.FuncAFRF(math.Sinh)),
	"sqrt":      objects.NewUserFunction("sqrt", objects.FuncAFRF(math.Sqrt)),
	"tan":       objects.NewUserFunction("tan", objects.FuncAFRF(math.Tan)),
	"tanh":      objects.NewUserFunction("tanh", objects.FuncAFRF(math.Tanh)),
	"trunc":     objects.NewUserFunction("trunc", objects.FuncAFRF(math.Trunc)),
	"y0":        objects.NewUserFunction("y0", objects.FuncAFRF(math.Y0)),
	"y1":        objects.NewUserFunction("y1", objects.FuncAFRF(math.Y1)),
	"yn":        objects.NewUserFunction("yn", objects.FuncAIFRF(math.Yn)),
}
