package stdlib

import (
	"math"

	"github.com/markel1974/c64emu/src/kernel/vm/objects"
)

var mathModule = map[string]objects.IObject{
	"e":         objects.NewFloat(math.E),
	"pi":        objects.NewFloat(math.Pi),
	"phi":       objects.NewFloat(math.Phi),
	"sqrt2":     objects.NewFloat(math.Sqrt2),
	"sqrtE":     objects.NewFloat(math.SqrtE),
	"sqrtPi":    objects.NewFloat(math.SqrtPi),
	"sqrtPhi":   objects.NewFloat(math.SqrtPhi),
	"ln2":       objects.NewFloat(math.Ln2),
	"log2E":     objects.NewFloat(math.Log2E),
	"ln10":      objects.NewFloat(math.Ln10),
	"log10E":    objects.NewFloat(math.Log10E),
	"abs":       objects.NewUserFunction("abs", FuncAFRF(math.Abs)),
	"acos":      objects.NewUserFunction("acos", FuncAFRF(math.Acos)),
	"acosh":     objects.NewUserFunction("acosh", FuncAFRF(math.Acosh)),
	"asin":      objects.NewUserFunction("asin", FuncAFRF(math.Asin)),
	"asinh":     objects.NewUserFunction("asinh", FuncAFRF(math.Asinh)),
	"atan":      objects.NewUserFunction("atan", FuncAFRF(math.Atan)),
	"atan2":     objects.NewUserFunction("atan2", FuncAFFRF(math.Atan2)),
	"atanh":     objects.NewUserFunction("atanh", FuncAFRF(math.Atanh)),
	"cbrt":      objects.NewUserFunction("cbrt", FuncAFRF(math.Cbrt)),
	"ceil":      objects.NewUserFunction("ceil", FuncAFRF(math.Ceil)),
	"copysign":  objects.NewUserFunction("copysign", FuncAFFRF(math.Copysign)),
	"cos":       objects.NewUserFunction("cos", FuncAFRF(math.Cos)),
	"cosh":      objects.NewUserFunction("cosh", FuncAFRF(math.Cosh)),
	"dim":       objects.NewUserFunction("dim", FuncAFFRF(math.Dim)),
	"erf":       objects.NewUserFunction("erf", FuncAFRF(math.Erf)),
	"erfc":      objects.NewUserFunction("erfc", FuncAFRF(math.Erfc)),
	"exp":       objects.NewUserFunction("exp", FuncAFRF(math.Exp)),
	"exp2":      objects.NewUserFunction("exp2", FuncAFRF(math.Exp2)),
	"expm1":     objects.NewUserFunction("expm1", FuncAFRF(math.Expm1)),
	"floor":     objects.NewUserFunction("floor", FuncAFRF(math.Floor)),
	"gamma":     objects.NewUserFunction("gamma", FuncAFRF(math.Gamma)),
	"hypot":     objects.NewUserFunction("hypot", FuncAFFRF(math.Hypot)),
	"ilogb":     objects.NewUserFunction("ilogb", FuncAFRI(math.Ilogb)),
	"inf":       objects.NewUserFunction("inf", FuncAIRF(math.Inf)),
	"is_inf":    objects.NewUserFunction("is_inf", FuncAFIRB(math.IsInf)),
	"is_nan":    objects.NewUserFunction("is_nan", FuncAFRB(math.IsNaN)),
	"j0":        objects.NewUserFunction("j0", FuncAFRF(math.J0)),
	"j1":        objects.NewUserFunction("j1", FuncAFRF(math.J1)),
	"jn":        objects.NewUserFunction("jn", FuncAIFRF(math.Jn)),
	"ldexp":     objects.NewUserFunction("ldexp", FuncAFIRF(math.Ldexp)),
	"log":       objects.NewUserFunction("log", FuncAFRF(math.Log)),
	"log10":     objects.NewUserFunction("log10", FuncAFRF(math.Log10)),
	"log1p":     objects.NewUserFunction("log1p", FuncAFRF(math.Log1p)),
	"log2":      objects.NewUserFunction("log2", FuncAFRF(math.Log2)),
	"logb":      objects.NewUserFunction("logb", FuncAFRF(math.Logb)),
	"max":       objects.NewUserFunction("max", FuncAFFRF(math.Max)),
	"min":       objects.NewUserFunction("min", FuncAFFRF(math.Min)),
	"mod":       objects.NewUserFunction("mod", FuncAFFRF(math.Mod)),
	"nan":       objects.NewUserFunction("nan", FuncARF(math.NaN)),
	"nextafter": objects.NewUserFunction("nextafter", FuncAFFRF(math.Nextafter)),
	"pow":       objects.NewUserFunction("pow", FuncAFFRF(math.Pow)),
	"pow10":     objects.NewUserFunction("pow10", FuncAIRF(math.Pow10)),
	"remainder": objects.NewUserFunction("remainder", FuncAFFRF(math.Remainder)),
	"signbit":   objects.NewUserFunction("signbit", FuncAFRB(math.Signbit)),
	"sin":       objects.NewUserFunction("sin", FuncAFRF(math.Sin)),
	"sinh":      objects.NewUserFunction("sinh", FuncAFRF(math.Sinh)),
	"sqrt":      objects.NewUserFunction("sqrt", FuncAFRF(math.Sqrt)),
	"tan":       objects.NewUserFunction("tan", FuncAFRF(math.Tan)),
	"tanh":      objects.NewUserFunction("tanh", FuncAFRF(math.Tanh)),
	"trunc":     objects.NewUserFunction("trunc", FuncAFRF(math.Trunc)),
	"y0":        objects.NewUserFunction("y0", FuncAFRF(math.Y0)),
	"y1":        objects.NewUserFunction("y1", FuncAFRF(math.Y1)),
	"yn":        objects.NewUserFunction("yn", FuncAIFRF(math.Yn)),
}
