package _510

// States for addressing modes/operations

// Read effective address no extra cycles

const (
	STATE_LAST = 0x0 + iota

	U_UNK_1
	U_UNK_2
	U_UNK_3
	U_UNK_4
	U_UNK_5
	U_UNK_6
	U_UNK_7

	I_IRQ_8
	I_IRQ_9
	I_IRQ_A
	I_IRQ_B
	I_IRQ_C
	I_IRQ_D
	I_IRQ_E

	U_UNK_F

	I_NMI_10
	I_NMI_11
	I_NMI_12
	I_NMI_13
	I_NMI_14
	I_NMI_15
	I_NMI_16

	U_UNK_17

	A_ZERO
	A_ZEROX
	A_ZEROX1
	A_ZEROY
	A_ZEROY1
	A_ABS
	A_ABS1
	A_ABSX
	A_ABSX1
	A_ABSX2
	A_ABSX3
	A_ABSY
	A_ABSY1
	A_ABSY2
	A_ABSY3
	A_INDX
	A_INDX1
	A_INDX2
	A_INDX3
	A_INDY
	A_INDY1
	A_INDY2
	A_INDY3
	A_INDY4

	//Read effective address extra cycle on page crossing

	AE_ABSX
	AE_ABSX1
	AE_ABSX2

	AE_ABSY
	AE_ABSY1
	AE_ABSY2

	AE_INDY
	AE_INDY1
	AE_INDY2
	AE_INDY3

	// Read operand and write it back (for RMW instructions) no extra cycles

	M_ZERO
	M_ZEROX
	M_ZEROX1
	M_ZEROY
	M_ZEROY1

	M_ABS
	M_ABS1

	M_ABSX
	M_ABSX1
	M_ABSX2
	M_ABSX3

	M_ABSY
	M_ABSY1
	M_ABSY2
	M_ABSY3

	M_INDX
	M_INDX1
	M_INDX2
	M_INDX3

	M_INDY
	M_INDY1
	M_INDY2
	M_INDY3
	M_INDY4

	RMW_DO_IT
	RMW_DO_IT1

	// Operations (I = Immediate/Indirect A = Accumulator)

	O_LDA

	O_LDA_I

	O_LDX

	O_LDX_I

	O_LDY

	O_LDY_I

	O_STA
	O_STX
	O_STY
	O_TAX
	O_TXA
	O_TAY
	O_TYA
	O_TSX
	O_TXS
	O_ADC
	O_ADC_I
	O_SBC
	O_SBC_I
	O_INX
	O_DEX
	O_INY
	O_DEY
	O_INC
	O_DEC
	O_AND
	O_AND_I
	O_ORA
	O_ORA_I
	O_EOR
	O_EOR_I
	O_CMP
	O_CMP_I
	O_CPX
	O_CPX_I
	O_CPY
	O_CPY_I
	O_BIT
	O_ASL
	O_ASL_A
	O_LSR
	O_LSR_A
	O_ROL
	O_ROL_A
	O_ROR
	O_ROR_A

	O_PHA
	O_PHA1

	O_PLA
	O_PLA1
	O_PLA2

	O_PHP
	O_PHP1

	O_PLP
	O_PLP1
	O_PLP2

	O_JMP
	O_JMP1

	O_JMP_I
	O_JMP_I1

	O_JSR
	O_JSR1
	O_JSR2
	O_JSR3
	O_JSR4

	O_RTS
	O_RTS1
	O_RTS2
	O_RTS3
	O_RTS4

	O_RTI
	O_RTI1
	O_RTI2
	O_RTI3
	O_RTI4

	O_BRK
	O_BRK1
	O_BRK2
	O_BRK3
	O_BRK4
	O_BRK5
	O_BRK5NMI

	O_BCS
	O_BCC
	O_BEQ
	O_BNE
	O_BVS
	O_BVC
	O_BMI
	O_BPL
	O_BRANCH_NP
	O_BRANCH_BP
	O_BRANCH_BP1
	O_BRANCH_FP
	O_BRANCH_FP1
	O_SEC
	O_CLC
	O_SED
	O_CLD
	O_SEI
	O_CLI
	O_CLV
	O_NOP

	O_NOP_I
	O_NOP_A
	O_LAX
	O_SAX
	O_SLO
	O_RLA
	O_SRE
	O_RRA
	O_DCP
	O_ISB
	O_ANC_I
	O_ASR_I
	O_ARR_I
	O_ANE_I
	O_LXA_I
	O_SBX_I
	O_LAS
	O_SHS
	O_SHY
	O_SHX
	O_SHA
	O_EXT
)

// _modeTable Addressing mode for each opcode (first part of execution)
var _modeTable = [256]byte{
	O_BRK, A_INDX, 1, M_INDX, A_ZERO, A_ZERO, M_ZERO, M_ZERO, // 00
	O_PHP, O_ORA_I, O_ASL_A, O_ANC_I, A_ABS, A_ABS, M_ABS, M_ABS,
	O_BPL, AE_INDY, 1, M_INDY, A_ZEROX, A_ZEROX, M_ZEROX, M_ZEROX, // 10
	O_CLC, AE_ABSY, O_NOP, M_ABSY, AE_ABSX, AE_ABSX, M_ABSX, M_ABSX,
	O_JSR, A_INDX, 1, M_INDX, A_ZERO, A_ZERO, M_ZERO, M_ZERO, // 20
	O_PLP, O_AND_I, O_ROL_A, O_ANC_I, A_ABS, A_ABS, M_ABS, M_ABS,
	O_BMI, AE_INDY, 1, M_INDY, A_ZEROX, A_ZEROX, M_ZEROX, M_ZEROX, // 30
	O_SEC, AE_ABSY, O_NOP, M_ABSY, AE_ABSX, AE_ABSX, M_ABSX, M_ABSX,
	O_RTI, A_INDX, 1, M_INDX, A_ZERO, A_ZERO, M_ZERO, M_ZERO, // 40
	O_PHA, O_EOR_I, O_LSR_A, O_ASR_I, O_JMP, A_ABS, M_ABS, M_ABS,
	O_BVC, AE_INDY, 1, M_INDY, A_ZEROX, A_ZEROX, M_ZEROX, M_ZEROX, // 50
	O_CLI, AE_ABSY, O_NOP, M_ABSY, AE_ABSX, AE_ABSX, M_ABSX, M_ABSX,
	O_RTS, A_INDX, 1, M_INDX, A_ZERO, A_ZERO, M_ZERO, M_ZERO, // 60
	O_PLA, O_ADC_I, O_ROR_A, O_ARR_I, A_ABS, A_ABS, M_ABS, M_ABS,
	O_BVS, AE_INDY, 1, M_INDY, A_ZEROX, A_ZEROX, M_ZEROX, M_ZEROX, // 70
	O_SEI, AE_ABSY, O_NOP, M_ABSY, AE_ABSX, AE_ABSX, M_ABSX, M_ABSX,
	O_NOP_I, A_INDX, O_NOP_I, A_INDX, A_ZERO, A_ZERO, A_ZERO, A_ZERO, // 80
	O_DEY, O_NOP_I, O_TXA, O_ANE_I, A_ABS, A_ABS, A_ABS, A_ABS,
	O_BCC, A_INDY, 1, A_INDY, A_ZEROX, A_ZEROX, A_ZEROY, A_ZEROY, // 90
	O_TYA, A_ABSY, O_TXS, A_ABSY, A_ABSX, A_ABSX, A_ABSY, A_ABSY,
	O_LDY_I, A_INDX, O_LDX_I, A_INDX, A_ZERO, A_ZERO, A_ZERO, A_ZERO, // a0
	O_TAY, O_LDA_I, O_TAX, O_LXA_I, A_ABS, A_ABS, A_ABS, A_ABS,
	O_BCS, AE_INDY, 1, AE_INDY, A_ZEROX, A_ZEROX, A_ZEROY, A_ZEROY, // b0
	O_CLV, AE_ABSY, O_TSX, AE_ABSY, AE_ABSX, AE_ABSX, AE_ABSY, AE_ABSY,
	O_CPY_I, A_INDX, O_NOP_I, M_INDX, A_ZERO, A_ZERO, M_ZERO, M_ZERO, // c0
	O_INY, O_CMP_I, O_DEX, O_SBX_I, A_ABS, A_ABS, M_ABS, M_ABS,
	O_BNE, AE_INDY, 1, M_INDY, A_ZEROX, A_ZEROX, M_ZEROX, M_ZEROX, // d0
	O_CLD, AE_ABSY, O_NOP, M_ABSY, AE_ABSX, AE_ABSX, M_ABSX, M_ABSX,
	O_CPX_I, A_INDX, O_NOP_I, M_INDX, A_ZERO, A_ZERO, M_ZERO, M_ZERO, // e0
	O_INX, O_SBC_I, O_NOP, O_SBC_I, A_ABS, A_ABS, M_ABS, M_ABS,
	O_BEQ, AE_INDY, O_EXT, M_INDY, A_ZEROX, A_ZEROX, M_ZEROX, M_ZEROX, // f0
	O_SED, AE_ABSY, O_NOP, M_ABSY, AE_ABSX, AE_ABSX, M_ABSX, M_ABSX,
}

// _opTable Operation for each opcode (second part of execution)
var _opTable = [256]byte{
	1, O_ORA, 1, O_SLO, O_NOP_A, O_ORA, O_ASL, O_SLO, // 00
	1, 1, 1, 1, O_NOP_A, O_ORA, O_ASL, O_SLO,
	1, O_ORA, 1, O_SLO, O_NOP_A, O_ORA, O_ASL, O_SLO, // 10
	1, O_ORA, 1, O_SLO, O_NOP_A, O_ORA, O_ASL, O_SLO,
	1, O_AND, 1, O_RLA, O_BIT, O_AND, O_ROL, O_RLA, // 20
	1, 1, 1, 1, O_BIT, O_AND, O_ROL, O_RLA,
	1, O_AND, 1, O_RLA, O_NOP_A, O_AND, O_ROL, O_RLA, // 30
	1, O_AND, 1, O_RLA, O_NOP_A, O_AND, O_ROL, O_RLA,
	1, O_EOR, 1, O_SRE, O_NOP_A, O_EOR, O_LSR, O_SRE, // 40
	1, 1, 1, 1, 1, O_EOR, O_LSR, O_SRE,
	1, O_EOR, 1, O_SRE, O_NOP_A, O_EOR, O_LSR, O_SRE, // 50
	1, O_EOR, 1, O_SRE, O_NOP_A, O_EOR, O_LSR, O_SRE,
	1, O_ADC, 1, O_RRA, O_NOP_A, O_ADC, O_ROR, O_RRA, // 60
	1, 1, 1, 1, O_JMP_I, O_ADC, O_ROR, O_RRA,
	1, O_ADC, 1, O_RRA, O_NOP_A, O_ADC, O_ROR, O_RRA, // 70
	1, O_ADC, 1, O_RRA, O_NOP_A, O_ADC, O_ROR, O_RRA,
	1, O_STA, 1, O_SAX, O_STY, O_STA, O_STX, O_SAX, // 80
	1, 1, 1, 1, O_STY, O_STA, O_STX, O_SAX,
	1, O_STA, 1, O_SHA, O_STY, O_STA, O_STX, O_SAX, // 90
	1, O_STA, 1, O_SHS, O_SHY, O_STA, O_SHX, O_SHA,
	1, O_LDA, 1, O_LAX, O_LDY, O_LDA, O_LDX, O_LAX, // a0
	1, 1, 1, 1, O_LDY, O_LDA, O_LDX, O_LAX,
	1, O_LDA, 1, O_LAX, O_LDY, O_LDA, O_LDX, O_LAX, // b0
	1, O_LDA, 1, O_LAS, O_LDY, O_LDA, O_LDX, O_LAX,
	1, O_CMP, 1, O_DCP, O_CPY, O_CMP, O_DEC, O_DCP, // c0
	1, 1, 1, 1, O_CPY, O_CMP, O_DEC, O_DCP,
	1, O_CMP, 1, O_DCP, O_NOP_A, O_CMP, O_DEC, O_DCP, // d0
	1, O_CMP, 1, O_DCP, O_NOP_A, O_CMP, O_DEC, O_DCP,
	1, O_SBC, 1, O_ISB, O_CPX, O_SBC, O_INC, O_ISB, // e0
	1, 1, 1, 1, O_CPX, O_SBC, O_INC, O_ISB,
	1, O_SBC, 1, O_ISB, O_NOP_A, O_SBC, O_INC, O_ISB, // f0
	1, O_SBC, 1, O_ISB, O_NOP_A, O_SBC, O_INC, O_ISB,
}

const (
	OpFlagIrqDisabled = 0x01
	OpFlagIrqEnabled  = 0x02
	OpFlagIntDelayed  = 0x04
)
