package reu

// Code generated by symphony-generator. DO NOT EDIT.

import "errors"

const (
	reflectRamId  = "ram"
	reflectMaskId = "mask"
	reflectRegsId = "regs"
)

type REUReflect struct {
	ref              *REU
	outOfBoundsError error
	readOnlyError    error
}

func NewREUReflect(r *REU) *REUReflect {
	reflector := &REUReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.PropertyAdd(reflectRamId, "REU RAM", false, reflector.getRam, reflector.setRam)

	_ = r.CommandAdd("getRamEntry", "REU RAM", reflector.getRamEntry)
	_ = r.CommandAdd("setRamEntry", "REU RAM", reflector.setRamEntry)

	r.PropertyAdd(reflectMaskId, "REU RAM address bit mask", false, reflector.getMask, reflector.setMask)

	r.PropertyAdd(reflectRegsId, "REU registers", false, reflector.getRegs, reflector.setRegs)

	_ = r.CommandAdd("getRegsEntry", "REU registers", reflector.getRegsEntry)
	_ = r.CommandAdd("setRegsEntry", "REU registers", reflector.setRegsEntry)

	_ = r.CommandAdd("HardwareButton", "HardwareButton(pressed, value) - HardwareButton handles the system response to a physical button press event, updating cartridge state as necessary.", r.HardwareButton)
	_ = r.CommandAdd("Detach", "Detach() error - Detach releases resources or connections held by the REU instance and prepares it for a safe disconnection.", r.Detach)
	_ = r.CommandAdd("IORead", "IORead(addr) uint8,bool - IORead reads data from the specified REU address. Returns the read value and a boolean indicating success or failure.  The address range is restricted to specific REU registers: $DF00-$DF0A, $DF20-$DF2A, and so on, up to $DFE0-$DFEA.  Returns the value of the register or a modified value based on the accessed register type.", r.IORead)
	_ = r.CommandAdd("GetLoaderId", "GetLoaderId() string - GetLoaderId returns the identifier string of the REU instance.", r.GetLoaderId)
	_ = r.CommandAdd("Emulate", "Emulate() - Emulate performs the main emulation logic for the REU device, handling internal operations and DMA processing.", r.Emulate)
	_ = r.CommandAdd("Config", "Config() uint8,uint8,bool - Config retrieves the cartridge configuration, including game state, EXROM value, and a boolean indicating success.", r.Config)
	_ = r.CommandAdd("IOWrite", "IOWrite(addr, data) bool - IOWrite processes a write operation to the REU's I/O registers based on the provided address and data.  It validates the address range, updates the REU's internal registers, and triggers DMA execution if necessary.  Returns true if the write operation is valid, otherwise false.", r.IOWrite)
	_ = r.CommandAdd("Operand", "Operand(_) uint8 - Operand retrieves data from the specified ROM interval and memory address. Returns the data and a boolean indicating success.", r.Read)
	_ = r.CommandAdd("Reset", "Reset() - Reset initializes the REU's registers and status based on its RAM size.", r.Reset)
	_ = r.CommandAdd("IRQ", "IRQ(_) - ", r.IRQ)
	_ = r.CommandAdd("IRQCLear", "IRQCLear(_) - ", r.IRQCLear)

	return reflector
}

// getRam is the generated getter for the ram.
func (s *REUReflect) getRam() []uint8 {
	return s.ref.ram
}

// setRam is the generated setter for the ram field.
func (s *REUReflect) setRam(v []uint8) error {
	copy(s.ref.ram, v)
	return nil
}

// getRamEntry is the generated indexed getter for the ram.
func (s *REUReflect) getRamEntry(idx int) (uint8, error) {
	if idx >= 0 && idx < len(s.ref.ram) {
		return s.ref.ram[idx], nil
	}
	return *new(uint8), s.outOfBoundsError
}

// setRamEntry is the generated indexed setter for the ram.
func (s *REUReflect) setRamEntry(idx int, v uint8) error {
	if idx >= 0 && idx < len(s.ref.ram) {
		s.ref.ram[idx] = v
		return nil
	}
	return errors.New("index out of bounds")
}

// getMask is the generated getter for the mask.
func (s *REUReflect) getMask() uint32 {
	return s.ref.mask
}

// setMask is the generated setter for the mask field.
func (s *REUReflect) setMask(v uint32) error {
	s.ref.mask = v
	return nil
}

// getRegs is the generated getter for the regs.
func (s *REUReflect) getRegs() []uint8 {
	return s.ref.regs
}

// setRegs is the generated setter for the regs field.
func (s *REUReflect) setRegs(v []uint8) error {
	copy(s.ref.regs, v)
	return nil
}

// getRegsEntry is the generated indexed getter for the regs.
func (s *REUReflect) getRegsEntry(idx int) (uint8, error) {
	if idx >= 0 && idx < len(s.ref.regs) {
		return s.ref.regs[idx], nil
	}
	return *new(uint8), s.outOfBoundsError
}

// setRegsEntry is the generated indexed setter for the regs.
func (s *REUReflect) setRegsEntry(idx int, v uint8) error {
	if idx >= 0 && idx < len(s.ref.regs) {
		s.ref.regs[idx] = v
		return nil
	}
	return errors.New("index out of bounds")
}
