package stdlib

import (
	"math"

	"github.com/markel1974/c64emu/src/kernel/vm/objects"
)

var _mathModule = map[string]objects.IObject{
	"E":         objects.NewFloat(math.E),
	"Pi":        objects.NewFloat(math.Pi),
	"Phi":       objects.NewFloat(math.Phi),
	"Sqrt2":     objects.NewFloat(math.Sqrt2),
	"SqrtE":     objects.NewFloat(math.SqrtE),
	"SqrtPi":    objects.NewFloat(math.SqrtPi),
	"SqrtPhi":   objects.NewFloat(math.SqrtPhi),
	"Ln2":       objects.NewFloat(math.Ln2),
	"Log2E":     objects.NewFloat(math.Log2E),
	"Ln10":      objects.NewFloat(math.Ln10),
	"Log10E":    objects.NewFloat(math.Log10E),
	"Abs":       objects.NewFunctionModule("Abs", objects.FuncIf64Of64(math.Abs)),
	"Acos":      objects.NewFunctionModule("Acos", objects.FuncIf64Of64(math.Acos)),
	"Acosh":     objects.NewFunctionModule("Acosh", objects.FuncIf64Of64(math.Acosh)),
	"Asin":      objects.NewFunctionModule("Asin", objects.FuncIf64Of64(math.Asin)),
	"Asinh":     objects.NewFunctionModule("Asinh", objects.FuncIf64Of64(math.Asinh)),
	"Atan":      objects.NewFunctionModule("Atan", objects.FuncIf64Of64(math.Atan)),
	"Atan2":     objects.NewFunctionModule("Atan2", objects.FuncIf64f64Of64(math.Atan2)),
	"Atanh":     objects.NewFunctionModule("Atanh", objects.FuncIf64Of64(math.Atanh)),
	"Cbrt":      objects.NewFunctionModule("Cbrt", objects.FuncIf64Of64(math.Cbrt)),
	"Ceil":      objects.NewFunctionModule("Ceil", objects.FuncIf64Of64(math.Ceil)),
	"Copysign":  objects.NewFunctionModule("Copysign", objects.FuncIf64f64Of64(math.Copysign)),
	"Cos":       objects.NewFunctionModule("Cos", objects.FuncIf64Of64(math.Cos)),
	"Cosh":      objects.NewFunctionModule("Cosh", objects.FuncIf64Of64(math.Cosh)),
	"Dim":       objects.NewFunctionModule("Dim", objects.FuncIf64f64Of64(math.Dim)),
	"Erf":       objects.NewFunctionModule("Erf", objects.FuncIf64Of64(math.Erf)),
	"Erfc":      objects.NewFunctionModule("Erfc", objects.FuncIf64Of64(math.Erfc)),
	"Exp":       objects.NewFunctionModule("Exp", objects.FuncIf64Of64(math.Exp)),
	"Exp2":      objects.NewFunctionModule("Exp2", objects.FuncIf64Of64(math.Exp2)),
	"Expm1":     objects.NewFunctionModule("Expm1", objects.FuncIf64Of64(math.Expm1)),
	"Floor":     objects.NewFunctionModule("Floor", objects.FuncIf64Of64(math.Floor)),
	"Gamma":     objects.NewFunctionModule("Gamma", objects.FuncIf64Of64(math.Gamma)),
	"Hypot":     objects.NewFunctionModule("Hypot", objects.FuncIf64f64Of64(math.Hypot)),
	"Ilogb":     objects.NewFunctionModule("Ilogb", objects.FuncIf64Oi(math.Ilogb)),
	"Inf":       objects.NewFunctionModule("Inf", objects.FuncIiOf64(math.Inf)),
	"IsInf":     objects.NewFunctionModule("IsInf", objects.FuncIf64iOb(math.IsInf)),
	"IsNaN":     objects.NewFunctionModule("IsNaN", objects.FuncIf64Ob(math.IsNaN)),
	"J0":        objects.NewFunctionModule("J0", objects.FuncIf64Of64(math.J0)),
	"J1":        objects.NewFunctionModule("J1", objects.FuncIf64Of64(math.J1)),
	"Jn":        objects.NewFunctionModule("Jn", objects.FuncIif64Of64(math.Jn)),
	"Ldexp":     objects.NewFunctionModule("Ldexp", objects.FuncIf64iOf64(math.Ldexp)),
	"Log":       objects.NewFunctionModule("Log", objects.FuncIf64Of64(math.Log)),
	"Log10":     objects.NewFunctionModule("Log10", objects.FuncIf64Of64(math.Log10)),
	"Log1p":     objects.NewFunctionModule("Log1p", objects.FuncIf64Of64(math.Log1p)),
	"Log2":      objects.NewFunctionModule("Log2", objects.FuncIf64Of64(math.Log2)),
	"Logb":      objects.NewFunctionModule("Logb", objects.FuncIf64Of64(math.Logb)),
	"Max":       objects.NewFunctionModule("Max", objects.FuncIf64f64Of64(math.Max)),
	"Min":       objects.NewFunctionModule("Min", objects.FuncIf64f64Of64(math.Min)),
	"Mod":       objects.NewFunctionModule("Mod", objects.FuncIf64f64Of64(math.Mod)),
	"NaN":       objects.NewFunctionModule("NaN", objects.FuncInOf64(math.NaN)),
	"Nextafter": objects.NewFunctionModule("Nextafter", objects.FuncIf64f64Of64(math.Nextafter)),
	"Pow":       objects.NewFunctionModule("Pow", objects.FuncIf64f64Of64(math.Pow)),
	"Pow10":     objects.NewFunctionModule("Pow10", objects.FuncIiOf64(math.Pow10)),
	"Remainder": objects.NewFunctionModule("Remainder", objects.FuncIf64f64Of64(math.Remainder)),
	"Signbit":   objects.NewFunctionModule("Signbit", objects.FuncIf64Ob(math.Signbit)),
	"Sin":       objects.NewFunctionModule("Sin", objects.FuncIf64Of64(math.Sin)),
	"Sinh":      objects.NewFunctionModule("Sinh", objects.FuncIf64Of64(math.Sinh)),
	"Sqrt":      objects.NewFunctionModule("Sqrt", objects.FuncIf64Of64(math.Sqrt)),
	"Tan":       objects.NewFunctionModule("Tan", objects.FuncIf64Of64(math.Tan)),
	"Tanh":      objects.NewFunctionModule("Tanh", objects.FuncIf64Of64(math.Tanh)),
	"Trunc":     objects.NewFunctionModule("Trunc", objects.FuncIf64Of64(math.Trunc)),
	"Y0":        objects.NewFunctionModule("Y0", objects.FuncIf64Of64(math.Y0)),
	"Y1":        objects.NewFunctionModule("Y1", objects.FuncIf64Of64(math.Y1)),
	"Yn":        objects.NewFunctionModule("Yn", objects.FuncIif64Of64(math.Yn)),
}
