package stdlib

import (
	"math"

	"github.com/markel1974/c64emu/src/kernel/vm/objects"
)

var _mathModule = map[string]objects.IObject{
	"e":         objects.NewFloat(math.E),
	"pi":        objects.NewFloat(math.Pi),
	"phi":       objects.NewFloat(math.Phi),
	"sqrt2":     objects.NewFloat(math.Sqrt2),
	"sqrtE":     objects.NewFloat(math.SqrtE),
	"sqrtPi":    objects.NewFloat(math.SqrtPi),
	"sqrtPhi":   objects.NewFloat(math.SqrtPhi),
	"ln2":       objects.NewFloat(math.Ln2),
	"log2E":     objects.NewFloat(math.Log2E),
	"ln10":      objects.NewFloat(math.Ln10),
	"log10E":    objects.NewFloat(math.Log10E),
	"abs":       objects.NewFunctionUser("abs", objects.FuncIf64Of64(math.Abs)),
	"acos":      objects.NewFunctionUser("acos", objects.FuncIf64Of64(math.Acos)),
	"acosh":     objects.NewFunctionUser("acosh", objects.FuncIf64Of64(math.Acosh)),
	"asin":      objects.NewFunctionUser("asin", objects.FuncIf64Of64(math.Asin)),
	"asinh":     objects.NewFunctionUser("asinh", objects.FuncIf64Of64(math.Asinh)),
	"atan":      objects.NewFunctionUser("atan", objects.FuncIf64Of64(math.Atan)),
	"atan2":     objects.NewFunctionUser("atan2", objects.FuncIf64f64Of64(math.Atan2)),
	"atanh":     objects.NewFunctionUser("atanh", objects.FuncIf64Of64(math.Atanh)),
	"cbrt":      objects.NewFunctionUser("cbrt", objects.FuncIf64Of64(math.Cbrt)),
	"ceil":      objects.NewFunctionUser("ceil", objects.FuncIf64Of64(math.Ceil)),
	"copysign":  objects.NewFunctionUser("copysign", objects.FuncIf64f64Of64(math.Copysign)),
	"cos":       objects.NewFunctionUser("cos", objects.FuncIf64Of64(math.Cos)),
	"cosh":      objects.NewFunctionUser("cosh", objects.FuncIf64Of64(math.Cosh)),
	"dim":       objects.NewFunctionUser("dim", objects.FuncIf64f64Of64(math.Dim)),
	"erf":       objects.NewFunctionUser("erf", objects.FuncIf64Of64(math.Erf)),
	"erfc":      objects.NewFunctionUser("erfc", objects.FuncIf64Of64(math.Erfc)),
	"exp":       objects.NewFunctionUser("exp", objects.FuncIf64Of64(math.Exp)),
	"exp2":      objects.NewFunctionUser("exp2", objects.FuncIf64Of64(math.Exp2)),
	"expm1":     objects.NewFunctionUser("expm1", objects.FuncIf64Of64(math.Expm1)),
	"floor":     objects.NewFunctionUser("floor", objects.FuncIf64Of64(math.Floor)),
	"gamma":     objects.NewFunctionUser("gamma", objects.FuncIf64Of64(math.Gamma)),
	"hypot":     objects.NewFunctionUser("hypot", objects.FuncIf64f64Of64(math.Hypot)),
	"ilogb":     objects.NewFunctionUser("ilogb", objects.FuncIf64Oi(math.Ilogb)),
	"inf":       objects.NewFunctionUser("inf", objects.FuncIiOf64(math.Inf)),
	"is_inf":    objects.NewFunctionUser("is_inf", objects.FuncIf64iOb(math.IsInf)),
	"is_nan":    objects.NewFunctionUser("is_nan", objects.FuncIf64Ob(math.IsNaN)),
	"j0":        objects.NewFunctionUser("j0", objects.FuncIf64Of64(math.J0)),
	"j1":        objects.NewFunctionUser("j1", objects.FuncIf64Of64(math.J1)),
	"jn":        objects.NewFunctionUser("jn", objects.FuncIif64Of64(math.Jn)),
	"ldexp":     objects.NewFunctionUser("ldexp", objects.FuncIf64iOf64(math.Ldexp)),
	"log":       objects.NewFunctionUser("log", objects.FuncIf64Of64(math.Log)),
	"log10":     objects.NewFunctionUser("log10", objects.FuncIf64Of64(math.Log10)),
	"log1p":     objects.NewFunctionUser("log1p", objects.FuncIf64Of64(math.Log1p)),
	"log2":      objects.NewFunctionUser("log2", objects.FuncIf64Of64(math.Log2)),
	"logb":      objects.NewFunctionUser("logb", objects.FuncIf64Of64(math.Logb)),
	"max":       objects.NewFunctionUser("max", objects.FuncIf64f64Of64(math.Max)),
	"min":       objects.NewFunctionUser("min", objects.FuncIf64f64Of64(math.Min)),
	"mod":       objects.NewFunctionUser("mod", objects.FuncIf64f64Of64(math.Mod)),
	"nan":       objects.NewFunctionUser("nan", objects.FuncInOf64(math.NaN)),
	"nextafter": objects.NewFunctionUser("nextafter", objects.FuncIf64f64Of64(math.Nextafter)),
	"pow":       objects.NewFunctionUser("pow", objects.FuncIf64f64Of64(math.Pow)),
	"pow10":     objects.NewFunctionUser("pow10", objects.FuncIiOf64(math.Pow10)),
	"remainder": objects.NewFunctionUser("remainder", objects.FuncIf64f64Of64(math.Remainder)),
	"signbit":   objects.NewFunctionUser("signbit", objects.FuncIf64Ob(math.Signbit)),
	"sin":       objects.NewFunctionUser("sin", objects.FuncIf64Of64(math.Sin)),
	"sinh":      objects.NewFunctionUser("sinh", objects.FuncIf64Of64(math.Sinh)),
	"sqrt":      objects.NewFunctionUser("sqrt", objects.FuncIf64Of64(math.Sqrt)),
	"tan":       objects.NewFunctionUser("tan", objects.FuncIf64Of64(math.Tan)),
	"tanh":      objects.NewFunctionUser("tanh", objects.FuncIf64Of64(math.Tanh)),
	"trunc":     objects.NewFunctionUser("trunc", objects.FuncIf64Of64(math.Trunc)),
	"y0":        objects.NewFunctionUser("y0", objects.FuncIf64Of64(math.Y0)),
	"y1":        objects.NewFunctionUser("y1", objects.FuncIf64Of64(math.Y1)),
	"yn":        objects.NewFunctionUser("yn", objects.FuncIif64Of64(math.Yn)),
}
