package sdk

import (
	"math"

	"github.com/markel1974/c64emu/src/kernel/vm/objects"
)

var _mathModule = map[string]objects.IObject{
	"E":         objects.NewFloat(math.E),
	"Pi":        objects.NewFloat(math.Pi),
	"Phi":       objects.NewFloat(math.Phi),
	"Sqrt2":     objects.NewFloat(math.Sqrt2),
	"SqrtE":     objects.NewFloat(math.SqrtE),
	"SqrtPi":    objects.NewFloat(math.SqrtPi),
	"SqrtPhi":   objects.NewFloat(math.SqrtPhi),
	"Ln2":       objects.NewFloat(math.Ln2),
	"Log2E":     objects.NewFloat(math.Log2E),
	"Ln10":      objects.NewFloat(math.Ln10),
	"Log10E":    objects.NewFloat(math.Log10E),
	"Abs":       objects.NewFunctionModule(objects.FunctionModuleDef, "Abs", objects.FuncIf64Of64(math.Abs)),
	"Acos":      objects.NewFunctionModule(objects.FunctionModuleDef, "Acos", objects.FuncIf64Of64(math.Acos)),
	"Acosh":     objects.NewFunctionModule(objects.FunctionModuleDef, "Acosh", objects.FuncIf64Of64(math.Acosh)),
	"Asin":      objects.NewFunctionModule(objects.FunctionModuleDef, "Asin", objects.FuncIf64Of64(math.Asin)),
	"Asinh":     objects.NewFunctionModule(objects.FunctionModuleDef, "Asinh", objects.FuncIf64Of64(math.Asinh)),
	"Atan":      objects.NewFunctionModule(objects.FunctionModuleDef, "Atan", objects.FuncIf64Of64(math.Atan)),
	"Atan2":     objects.NewFunctionModule(objects.FunctionModuleDef, "Atan2", objects.FuncIf64f64Of64(math.Atan2)),
	"Atanh":     objects.NewFunctionModule(objects.FunctionModuleDef, "Atanh", objects.FuncIf64Of64(math.Atanh)),
	"Cbrt":      objects.NewFunctionModule(objects.FunctionModuleDef, "Cbrt", objects.FuncIf64Of64(math.Cbrt)),
	"Ceil":      objects.NewFunctionModule(objects.FunctionModuleDef, "Ceil", objects.FuncIf64Of64(math.Ceil)),
	"Copysign":  objects.NewFunctionModule(objects.FunctionModuleDef, "Copysign", objects.FuncIf64f64Of64(math.Copysign)),
	"Cos":       objects.NewFunctionModule(objects.FunctionModuleDef, "Cos", objects.FuncIf64Of64(math.Cos)),
	"Cosh":      objects.NewFunctionModule(objects.FunctionModuleDef, "Cosh", objects.FuncIf64Of64(math.Cosh)),
	"Dim":       objects.NewFunctionModule(objects.FunctionModuleDef, "Dim", objects.FuncIf64f64Of64(math.Dim)),
	"Erf":       objects.NewFunctionModule(objects.FunctionModuleDef, "Erf", objects.FuncIf64Of64(math.Erf)),
	"Erfc":      objects.NewFunctionModule(objects.FunctionModuleDef, "Erfc", objects.FuncIf64Of64(math.Erfc)),
	"Exp":       objects.NewFunctionModule(objects.FunctionModuleDef, "Exp", objects.FuncIf64Of64(math.Exp)),
	"Exp2":      objects.NewFunctionModule(objects.FunctionModuleDef, "Exp2", objects.FuncIf64Of64(math.Exp2)),
	"Expm1":     objects.NewFunctionModule(objects.FunctionModuleDef, "Expm1", objects.FuncIf64Of64(math.Expm1)),
	"Floor":     objects.NewFunctionModule(objects.FunctionModuleDef, "Floor", objects.FuncIf64Of64(math.Floor)),
	"Gamma":     objects.NewFunctionModule(objects.FunctionModuleDef, "Gamma", objects.FuncIf64Of64(math.Gamma)),
	"Hypot":     objects.NewFunctionModule(objects.FunctionModuleDef, "Hypot", objects.FuncIf64f64Of64(math.Hypot)),
	"Ilogb":     objects.NewFunctionModule(objects.FunctionModuleDef, "Ilogb", objects.FuncIf64Oi(math.Ilogb)),
	"Inf":       objects.NewFunctionModule(objects.FunctionModuleDef, "Inf", objects.FuncIiOf64(math.Inf)),
	"IsInf":     objects.NewFunctionModule(objects.FunctionModuleDef, "IsInf", objects.FuncIf64iOb(math.IsInf)),
	"IsNaN":     objects.NewFunctionModule(objects.FunctionModuleDef, "IsNaN", objects.FuncIf64Ob(math.IsNaN)),
	"J0":        objects.NewFunctionModule(objects.FunctionModuleDef, "J0", objects.FuncIf64Of64(math.J0)),
	"J1":        objects.NewFunctionModule(objects.FunctionModuleDef, "J1", objects.FuncIf64Of64(math.J1)),
	"Jn":        objects.NewFunctionModule(objects.FunctionModuleDef, "Jn", objects.FuncIif64Of64(math.Jn)),
	"Ldexp":     objects.NewFunctionModule(objects.FunctionModuleDef, "Ldexp", objects.FuncIf64iOf64(math.Ldexp)),
	"Log":       objects.NewFunctionModule(objects.FunctionModuleDef, "Log", objects.FuncIf64Of64(math.Log)),
	"Log10":     objects.NewFunctionModule(objects.FunctionModuleDef, "Log10", objects.FuncIf64Of64(math.Log10)),
	"Log1p":     objects.NewFunctionModule(objects.FunctionModuleDef, "Log1p", objects.FuncIf64Of64(math.Log1p)),
	"Log2":      objects.NewFunctionModule(objects.FunctionModuleDef, "Log2", objects.FuncIf64Of64(math.Log2)),
	"Logb":      objects.NewFunctionModule(objects.FunctionModuleDef, "Logb", objects.FuncIf64Of64(math.Logb)),
	"Max":       objects.NewFunctionModule(objects.FunctionModuleDef, "Max", objects.FuncIf64f64Of64(math.Max)),
	"Min":       objects.NewFunctionModule(objects.FunctionModuleDef, "Min", objects.FuncIf64f64Of64(math.Min)),
	"Mod":       objects.NewFunctionModule(objects.FunctionModuleDef, "Mod", objects.FuncIf64f64Of64(math.Mod)),
	"NaN":       objects.NewFunctionModule(objects.FunctionModuleDef, "NaN", objects.FuncInOf64(math.NaN)),
	"Nextafter": objects.NewFunctionModule(objects.FunctionModuleDef, "Nextafter", objects.FuncIf64f64Of64(math.Nextafter)),
	"Pow":       objects.NewFunctionModule(objects.FunctionModuleDef, "Pow", objects.FuncIf64f64Of64(math.Pow)),
	"Pow10":     objects.NewFunctionModule(objects.FunctionModuleDef, "Pow10", objects.FuncIiOf64(math.Pow10)),
	"Remainder": objects.NewFunctionModule(objects.FunctionModuleDef, "Remainder", objects.FuncIf64f64Of64(math.Remainder)),
	"Signbit":   objects.NewFunctionModule(objects.FunctionModuleDef, "Signbit", objects.FuncIf64Ob(math.Signbit)),
	"Sin":       objects.NewFunctionModule(objects.FunctionModuleDef, "Sin", objects.FuncIf64Of64(math.Sin)),
	"Sinh":      objects.NewFunctionModule(objects.FunctionModuleDef, "Sinh", objects.FuncIf64Of64(math.Sinh)),
	"Sqrt":      objects.NewFunctionModule(objects.FunctionModuleDef, "Sqrt", objects.FuncIf64Of64(math.Sqrt)),
	"Tan":       objects.NewFunctionModule(objects.FunctionModuleDef, "Tan", objects.FuncIf64Of64(math.Tan)),
	"Tanh":      objects.NewFunctionModule(objects.FunctionModuleDef, "Tanh", objects.FuncIf64Of64(math.Tanh)),
	"Trunc":     objects.NewFunctionModule(objects.FunctionModuleDef, "Trunc", objects.FuncIf64Of64(math.Trunc)),
	"Y0":        objects.NewFunctionModule(objects.FunctionModuleDef, "Y0", objects.FuncIf64Of64(math.Y0)),
	"Y1":        objects.NewFunctionModule(objects.FunctionModuleDef, "Y1", objects.FuncIf64Of64(math.Y1)),
	"Yn":        objects.NewFunctionModule(objects.FunctionModuleDef, "Yn", objects.FuncIif64Of64(math.Yn)),
}
