package easyflash

// Code generated by symphony-generator. DO NOT EDIT.

import "errors"

const (
	reflectWriteEnabledId = "writeEnabled"
	reflectOptimizeId     = "optimize"
	reflectRegister00Id   = "register00"
	reflectRegister02Id   = "register02"
	reflectRamId          = "ram"
	reflectFilenameId     = "filename"
)

type CartridgeEasyFlashReflect struct {
	ref              *CartridgeEasyFlash
	outOfBoundsError error
	readOnlyError    error
}

func NewCartridgeEasyFlashReflect(r *CartridgeEasyFlash) *CartridgeEasyFlashReflect {
	reflector := &CartridgeEasyFlashReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.PropertyAdd(reflectWriteEnabledId, "/* writing back to crt enabled */", false, reflector.getWriteEnabled, reflector.setWriteEnabled)

	r.PropertyAdd(reflectOptimizeId, "/* optimizing crt enabled */", false, reflector.getOptimize, reflector.setOptimize)

	r.PropertyAdd(reflectRegister00Id, "/* backup of the registers */", false, reflector.getRegister00, reflector.setRegister00)

	r.PropertyAdd(reflectRegister02Id, "/* backup of the registers */", false, reflector.getRegister02, reflector.setRegister02)

	r.PropertyAdd(reflectRamId, "/* extra RAM */", false, reflector.getRam, reflector.setRam)

	_ = r.CommandAdd("getRamEntry", "/* extra RAM */", reflector.getRamEntry)
	_ = r.CommandAdd("setRamEntry", "/* extra RAM */", reflector.setRamEntry)

	r.PropertyAdd(reflectFilenameId, "/* filename when attached */", false, reflector.getFilename, reflector.setFilename)

	_ = r.CommandAdd("SetUpdateEApi", "SetUpdateEApi(e) - SetUpdateEApi configures the updateEApi flag to enable or disable the extended API updating functionality.", r.SetUpdateEApi)
	_ = r.CommandAdd("Operand", "Operand(addr) uint8 - Operand retrieves a byte of data from the cartridge memory based on the provided ROM interval and address.", r.Read)
	_ = r.CommandAdd("Config", "Config() uint8,uint8,bool - Config returns the Game line status, ExROM line state, and a boolean indicating successful configuration retrieval.", r.Config)
	_ = r.CommandAdd("HardwareButton", "HardwareButton(pressed, value) - HardwareButton handles the system response to a physical button press event, updating cartridge state as necessary.", r.HardwareButton)
	_ = r.CommandAdd("IRQCLear", "IRQCLear(_) - IRQCLear clears the state of any active Interrupt Requests (IRQ) for the CartridgeGeneric.", r.IRQCLear)
	_ = r.CommandAdd("SetJumper", "SetJumper(j) - SetJumper sets the jumper state for the EasyFlash cartridge to the specified boolean value.", r.SetJumper)
	_ = r.CommandAdd("IOWrite", "IOWrite(addr, data) bool - IOWrite handles input/output write operations for the CartridgeEasyFlash.  It processes writes to specific memory address ranges (0xde00 and 0xdf00).  Updates internal registers and control states based on the provided data.  Returns true if the operation is valid and the data is handled, otherwise false.", r.IOWrite)
	_ = r.CommandAdd("Detach", "Detach() error - Detach finalizes and detaches the EasyFlash cartridge, ensuring any pending writes are flushed before shutdown.", r.Detach)
	_ = r.CommandAdd("Reset", "Reset() - Reset reinitializes the CartridgeEasyFlash state, clearing any temporary data and restoring default settings.", r.Reset)
	_ = r.CommandAdd("GetLoaderId", "GetLoaderId() string - GetLoaderId retrieves the unique identifier of the CartridgeEasyFlash instance.", r.GetLoaderId)
	_ = r.CommandAdd("Emulate", "Emulate() - Emulate starts the emulation process for the CartridgeEasyFlash, executing associated operations and behaviors.", r.Emulate)
	_ = r.CommandAdd("IORead", "IORead(addr) uint8,bool - IORead reads a value from the specified address within the EasyFlash cartridge's I/O space.  Returns the value and a boolean indicating if the read is valid.", r.IORead)
	_ = r.CommandAdd("IRQ", "IRQ(_) - IRQ handles the Interrupt Request (IRQ) signal for the CartridgeGeneric, enabling appropriate cartridge-specific behavior.", r.IRQ)
	_ = r.CommandAdd("SetOptimize", "SetOptimize(o) - SetOptimize sets the optimize flag for the CartridgeEasyFlash instance.", r.SetOptimize)
	_ = r.CommandAdd("SetWriteEnabled", "SetWriteEnabled(e) - SetWriteEnabled updates the write-enabled state of the cartridge.", r.SetWriteEnabled)

	return reflector
}

// getWriteEnabled is the generated getter for the writeEnabled.
func (s *CartridgeEasyFlashReflect) getWriteEnabled() bool {
	return s.ref.writeEnabled
}

// setWriteEnabled is the generated setter for the writeEnabled field.
func (s *CartridgeEasyFlashReflect) setWriteEnabled(v bool) error {
	s.ref.SetWriteEnabled(v)
	return nil
}

// getOptimize is the generated getter for the optimize.
func (s *CartridgeEasyFlashReflect) getOptimize() bool {
	return s.ref.optimize
}

// setOptimize is the generated setter for the optimize field.
func (s *CartridgeEasyFlashReflect) setOptimize(v bool) error {
	s.ref.SetOptimize(v)
	return nil
}

// getRegister00 is the generated getter for the register00.
func (s *CartridgeEasyFlashReflect) getRegister00() uint8 {
	return s.ref.register00
}

// setRegister00 is the generated setter for the register00 field.
func (s *CartridgeEasyFlashReflect) setRegister00(v uint8) error {
	s.ref.register00 = v
	return nil
}

// getRegister02 is the generated getter for the register02.
func (s *CartridgeEasyFlashReflect) getRegister02() uint8 {
	return s.ref.register02
}

// setRegister02 is the generated setter for the register02 field.
func (s *CartridgeEasyFlashReflect) setRegister02(v uint8) error {
	s.ref.register02 = v
	return nil
}

// getRam is the generated getter for the ram.
func (s *CartridgeEasyFlashReflect) getRam() []uint8 {
	return s.ref.ram
}

// setRam is the generated setter for the ram field.
func (s *CartridgeEasyFlashReflect) setRam(v []uint8) error {
	copy(s.ref.ram, v)
	return nil
}

// getRamEntry is the generated indexed getter for the ram.
func (s *CartridgeEasyFlashReflect) getRamEntry(idx int) (uint8, error) {
	if idx >= 0 && idx < len(s.ref.ram) {
		return s.ref.ram[idx], nil
	}
	return *new(uint8), s.outOfBoundsError
}

// setRamEntry is the generated indexed setter for the ram.
func (s *CartridgeEasyFlashReflect) setRamEntry(idx int, v uint8) error {
	if idx >= 0 && idx < len(s.ref.ram) {
		s.ref.ram[idx] = v
		return nil
	}
	return errors.New("index out of bounds")
}

// getFilename is the generated getter for the filename.
func (s *CartridgeEasyFlashReflect) getFilename() string {
	return s.ref.filename
}

// setFilename is the generated setter for the filename field.
func (s *CartridgeEasyFlashReflect) setFilename(v string) error {
	s.ref.filename = v
	return nil
}
