package mos6569

// Code generated by symphony-generator. DO NOT EDIT.

import (
	"errors"
	"github.com/markel1974/c64emu/src/references"
)

const (
	reflectNumId              = "num"
	reflectMaxId              = "max"
	reflectMaskId             = "mask"
	reflectLatchId            = "latch"
	reflectPtrId              = "ptr"
	reflectCounterId          = "counter"
	reflectCounterBaseId      = "counterBase"
	reflectCounterIncrementId = "counterIncrement"
	reflectLatchIndexId       = "latchIndex"
)

type SpriteReflect struct {
	ref              *Sprite
	outOfBoundsError error
	readOnlyError    error
}

func NewSpriteReflect(r *Sprite, factory references.IComponentFactory, parent references.IComponent, identifier string, instance int, hardwareId string) *SpriteReflect {
	reflector := &SpriteReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.BaseComponent.Register(factory, parent, identifier, instance, r, hardwareId)
	r.PropertyAdd(reflectNumId, "Num", false, reflector.getNum, reflector.setNum)

	r.PropertyAdd(reflectMaxId, "Max", false, reflector.getMax, reflector.setMax)

	r.PropertyAdd(reflectMaskId, "Mask", false, reflector.getMask, reflector.setMask)

	r.PropertyAdd(reflectLatchId, "Latch", false, reflector.getLatch, reflector.setLatch)

	_ = r.CommandAdd("getLatchEntry", "Latch", reflector.getLatchEntry)
	_ = r.CommandAdd("setLatchEntry", "Latch", reflector.setLatchEntry)

	r.PropertyAdd(reflectPtrId, "Ptr", false, reflector.getPtr, reflector.setPtr)

	r.PropertyAdd(reflectCounterId, "Counter", false, reflector.getCounter, reflector.setCounter)

	r.PropertyAdd(reflectCounterBaseId, "CounterBase", false, reflector.getCounterBase, reflector.setCounterBase)

	r.PropertyAdd(reflectCounterIncrementId, "CounterIncrement", false, reflector.getCounterIncrement, reflector.setCounterIncrement)

	r.PropertyAdd(reflectLatchIndexId, "LatchIndex", false, reflector.getLatchIndex, reflector.setLatchIndex)

	_ = r.CommandAdd("SetLatchIndex", "SetLatchIndex(index) - ", r.SetLatchIndex)
	_ = r.CommandAdd("SetPtr", "SetPtr(ptr) - ", r.SetPtr)
	_ = r.CommandAdd("Emulate", "Emulate() - Emulate executes the main processing logic for the sprite during each emulation cycle, updating its state and behavior.", r.Emulate)
	_ = r.CommandAdd("Reset", "Reset() - Reset reinitializes the sprite's internal state, counters, and data to their default configuration.", r.Reset)
	_ = r.CommandAdd("Counter", "Counter() uint16 - ", r.Counter)
	_ = r.CommandAdd("Ptr", "Ptr() uint16 - ", r.Ptr)
	_ = r.CommandAdd("LatchAttributes", "LatchAttributes(mdp, mm0, mm1, mXc, mXx) - LatchAttributes updates the sprite's color data, multicolor flags, and offset using the provided parameters.", r.LatchAttributes)
	_ = r.CommandAdd("IncrementCounterBase", "IncrementCounterBase() - IncrementCounterBase updates the counterIncrement field of the sprite to align with the current data alignment value.", r.IncrementCounterBase)
	_ = r.CommandAdd("Draw", "Draw(latchIndex) - ", r.Draw)
	_ = r.CommandAdd("WriteData", "WriteData(bNum, data) - ", r.SetData)
	_ = r.CommandAdd("CommitIncrementCounterBase", "CommitIncrementCounterBase() bool - CommitIncrementCounterBase updates the counter-base by adding the counter-increment, resets the increment, and checks a condition.", r.CommitIncrementCounterBase)
	_ = r.CommandAdd("ResetCounterBase", "ResetCounterBase() - ResetCounterBase resets the sprite's counterBase to zero. It is typically used to reinitialize the base counter.", r.ResetCounterBase)
	_ = r.CommandAdd("CommitCounterBase", "CommitCounterBase() - CommitCounterBase sets the sprite's data counter to its base value stored in dataCounterBase.", r.CommitCounterBase)
	_ = r.CommandAdd("Number", "Number() uint8 - Number returns the unique identifier of the sprite as an 8-bit unsigned integer.", r.Number)
	_ = r.CommandAdd("Mask", "Mask() uint8 - Mask returns the bitmask representing the sprite's unique identifier for operations like collision detection.", r.Mask)
	_ = r.CommandAdd("ModeUpdate", "ModeUpdate(mmc, mxe) - ModeUpdate updates the sprite's rendering mode pipeline based on multicolor and horizontal expansion flags.", r.ModeUpdate)

	return reflector
}

// getNum is the generated getter for the num.
func (s *SpriteReflect) getNum() uint8 {
	return s.ref.num
}

// setNum is the generated setter for the num field.
func (s *SpriteReflect) setNum(v uint8) error {
	s.ref.num = v
	return nil
}

// getMax is the generated getter for the max.
func (s *SpriteReflect) getMax() int {
	return s.ref.max
}

// setMax is the generated setter for the max field.
func (s *SpriteReflect) setMax(v int) error {
	s.ref.max = v
	return nil
}

// getMask is the generated getter for the mask.
func (s *SpriteReflect) getMask() uint8 {
	return s.ref.mask
}

// setMask is the generated setter for the mask field.
func (s *SpriteReflect) setMask(v uint8) error {
	s.ref.mask = v
	return nil
}

// getLatch is the generated getter for the latch.
func (s *SpriteReflect) getLatch() []int {
	return s.ref.latch
}

// setLatch is the generated setter for the latch field.
func (s *SpriteReflect) setLatch(v []int) error {
	copy(s.ref.latch, v)
	return nil
}

// getLatchEntry is the generated indexed getter for the latch.
func (s *SpriteReflect) getLatchEntry(idx int) (int, error) {
	if idx >= 0 && idx < len(s.ref.latch) {
		return s.ref.latch[idx], nil
	}
	return *new(int), s.outOfBoundsError
}

// setLatchEntry is the generated indexed setter for the latch.
func (s *SpriteReflect) setLatchEntry(idx int, v int) error {
	if idx >= 0 && idx < len(s.ref.latch) {
		s.ref.latch[idx] = v
		return nil
	}
	return errors.New("index out of bounds")
}

// getPtr is the generated getter for the ptr.
func (s *SpriteReflect) getPtr() uint16 {
	return s.ref.ptr
}

// setPtr is the generated setter for the ptr field.
func (s *SpriteReflect) setPtr(v uint16) error {
	s.ref.SetPtr(v)
	return nil
}

// getCounter is the generated getter for the counter.
func (s *SpriteReflect) getCounter() uint16 {
	return s.ref.counter
}

// setCounter is the generated setter for the counter field.
func (s *SpriteReflect) setCounter(v uint16) error {
	s.ref.counter = v
	return nil
}

// getCounterBase is the generated getter for the counterBase.
func (s *SpriteReflect) getCounterBase() uint16 {
	return s.ref.counterBase
}

// setCounterBase is the generated setter for the counterBase field.
func (s *SpriteReflect) setCounterBase(v uint16) error {
	s.ref.counterBase = v
	return nil
}

// getCounterIncrement is the generated getter for the counterIncrement.
func (s *SpriteReflect) getCounterIncrement() uint16 {
	return s.ref.counterIncrement
}

// setCounterIncrement is the generated setter for the counterIncrement field.
func (s *SpriteReflect) setCounterIncrement(v uint16) error {
	s.ref.counterIncrement = v
	return nil
}

// getLatchIndex is the generated getter for the latchIndex.
func (s *SpriteReflect) getLatchIndex() int {
	return s.ref.latchIndex
}

// setLatchIndex is the generated setter for the latchIndex field.
func (s *SpriteReflect) setLatchIndex(v int) error {
	s.ref.SetLatchIndex(v)
	return nil
}
