package mos6569

// Code generated by symphony-generator. DO NOT EDIT.

import "errors"

const (
	reflectLabelId              = "label"
	reflectRow25YStartId        = "row25YStart"
	reflectRow25YStopId         = "row25YStop"
	reflectRow24YStartId        = "row24YStart"
	reflectRow24YStopId         = "row24YStop"
	reflectFirstDisplayedLineId = "firstDisplayedLine"
	reflectLastDisplayedLineId  = "lastDisplayedLine"
	reflectCr1Id                = "cr1"
	reflectCr2Id                = "cr2"
	reflectRasterXId            = "rasterX"
	reflectRasterYId            = "rasterY"
	reflectRasterYMaxId         = "rasterYMax"
	reflectBaLowId              = "baLow"
	reflectAecLowId             = "aecLow"
	reflectAecLowNextCycleId    = "aecLowNextCycle"
	reflectVBlankNextCycleId    = "vBlankNextCycle"
	reflectDrawLineId           = "drawLine"
)

type VICReflect struct {
	ref              *VIC
	outOfBoundsError error
	readOnlyError    error
}

func NewVICReflect(r *VIC) *VICReflect {
	reflector := &VICReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.PropertyAdd(reflectLabelId, "Label", false, reflector.getLabel, reflector.setLabel)

	r.PropertyAdd(reflectRow25YStartId, "Row25YStart", false, reflector.getRow25YStart, reflector.setRow25YStart)

	r.PropertyAdd(reflectRow25YStopId, "Row25YStop", false, reflector.getRow25YStop, reflector.setRow25YStop)

	r.PropertyAdd(reflectRow24YStartId, "Row24YStart", false, reflector.getRow24YStart, reflector.setRow24YStart)

	r.PropertyAdd(reflectRow24YStopId, "Row24YStop", false, reflector.getRow24YStop, reflector.setRow24YStop)

	r.PropertyAdd(reflectFirstDisplayedLineId, "FirstDisplayedLine", false, reflector.getFirstDisplayedLine, reflector.setFirstDisplayedLine)

	r.PropertyAdd(reflectLastDisplayedLineId, "LastDisplayedLine", false, reflector.getLastDisplayedLine, reflector.setLastDisplayedLine)

	r.PropertyAdd(reflectCr1Id, "VIC register", false, reflector.getCr1, reflector.setCr1)

	r.PropertyAdd(reflectCr2Id, "VIC register", false, reflector.getCr2, reflector.setCr2)

	r.PropertyAdd(reflectRasterXId, "Current raster x position", false, reflector.getRasterX, reflector.setRasterX)

	r.PropertyAdd(reflectRasterYId, "Current raster y position", false, reflector.getRasterY, reflector.setRasterY)

	r.PropertyAdd(reflectRasterYMaxId, "RasterYMax", false, reflector.getRasterYMax, reflector.setRasterYMax)

	r.PropertyAdd(reflectBaLowId, "BA Line", false, reflector.getBaLow, reflector.setBaLow)

	r.PropertyAdd(reflectAecLowId, "AEC Line", false, reflector.getAecLow, reflector.setAecLow)

	r.PropertyAdd(reflectAecLowNextCycleId, "aecLowNextCycle represents the counter for the next cycle in the AEC low-level operation.", false, reflector.getAecLowNextCycle, reflector.setAecLowNextCycle)

	r.PropertyAdd(reflectVBlankNextCycleId, "vBlankNextCycle indicates whether the next cycle will trigger a vertical blanking interval (vBlank) in the display.", false, reflector.getVBlankNextCycle, reflector.setVBlankNextCycle)

	r.PropertyAdd(reflectDrawLineId, "DrawLine", false, reflector.getDrawLine, reflector.setDrawLine)

	_ = r.CommandAdd("ChangedVA", "ChangedVA(newVA) - ChangedVA updates the VIC's virtual address base and triggers the memory pointer update process.", r.ChangedVA)
	_ = r.CommandAdd("WriteCR1", "WriteCR1(data) - WriteCR1 updates the control register CR1 and adjusts various graphical and border settings based on the given data.", r.WriteCR1)
	_ = r.CommandAdd("GetText", "GetText() []byte - GetText retrieves the current text data as a byte slice from the VIC's bgrState system.", r.GetText)
	_ = r.CommandAdd("LightPenTrigger", "LightPenTrigger() - LightPenTrigger handles triggering the light pen functionality based on the current raster position.", r.LightPenTrigger)
	_ = r.CommandAdd("ReadCR1", "ReadCR1() uint8 - ReadCR1 reads the CR1 register, combining specific raster and control bits, and returns the resulting 8-bit value.", r.ReadCR1)
	_ = r.CommandAdd("ReadCR2", "ReadCR2() uint8 - ReadCR2 reads the CR2 register value, applies a bitwise OR with 0xC0, and returns the result as an 8-bit unsigned integer.", r.ReadCR2)
	_ = r.CommandAdd("WriteRegister", "WriteRegister(addr, data) - WriteRegister writes data to a register at the specified address, handling various control and memory settings.  go:nosplit", r.WriteRegister)
	_ = r.CommandAdd("Reset", "Reset() - Reset reinitializes the VIC instance to its default state by resetting its internal readiness flag.", r.Reset)
	_ = r.CommandAdd("GetVASignal", "GetVASignal() uint8 - GetVASignal returns the last byte stored in the VIC instance.", r.GetVASignal)
	_ = r.CommandAdd("SetBALow", "SetBALow() - SetBALow sets the BA (bus-available) signal to low and schedules the AEC signal to be low after 3 cycles if not already set.", r.SetBALow)
	_ = r.CommandAdd("ClearBALow", "ClearBALow() - ClearBALow resets the BA low and AEC low flags in the VIC instance and updates the corresponding socket states.", r.ClearBALow)
	_ = r.CommandAdd("WriteCR2", "WriteCR2(data) - WriteCR2 updates the CR2 register and adjusts associated bgrState settings like XScroll, column selection, and display mode.", r.WriteCR2)
	_ = r.CommandAdd("Emulate", "Emulate() - Emulate executes the current function assigned to the VIC and transitions to the next function in the sequence.  go:nosplit", r.Emulate)
	_ = r.CommandAdd("GetBALow", "GetBALow() bool - GetBALow returns the state of the baLow variable, indicating whether the BA low condition is active.", r.GetBALow)
	_ = r.CommandAdd("ReadRasterY", "ReadRasterY() uint8 - ReadRasterY returns the current raster Y position as an 8-bit unsigned integer.", r.ReadRasterY)
	_ = r.CommandAdd("ReadRegister", "ReadRegister(addr) uint8 - ReadRegister reads a register at the given address and returns the corresponding 8-bit value.  go:nosplit", r.ReadRegister)
	_ = r.CommandAdd("GetAECLow", "GetAECLow() bool - GetAECLow retrieves the current state of the AEC low flag for the VIC instance. Returns true if enabled, false otherwise.", r.GetAECLow)

	return reflector
}

// getLabel is the generated getter for the label.
func (s *VICReflect) getLabel() string {
	return s.ref.label
}

// setLabel is the generated setter for the label field.
func (s *VICReflect) setLabel(v string) error {
	s.ref.label = v
	return nil
}

// getRow25YStart is the generated getter for the row25YStart.
func (s *VICReflect) getRow25YStart() uint16 {
	return s.ref.row25YStart
}

// setRow25YStart is the generated setter for the row25YStart field.
func (s *VICReflect) setRow25YStart(v uint16) error {
	s.ref.row25YStart = v
	return nil
}

// getRow25YStop is the generated getter for the row25YStop.
func (s *VICReflect) getRow25YStop() uint16 {
	return s.ref.row25YStop
}

// setRow25YStop is the generated setter for the row25YStop field.
func (s *VICReflect) setRow25YStop(v uint16) error {
	s.ref.row25YStop = v
	return nil
}

// getRow24YStart is the generated getter for the row24YStart.
func (s *VICReflect) getRow24YStart() uint16 {
	return s.ref.row24YStart
}

// setRow24YStart is the generated setter for the row24YStart field.
func (s *VICReflect) setRow24YStart(v uint16) error {
	s.ref.row24YStart = v
	return nil
}

// getRow24YStop is the generated getter for the row24YStop.
func (s *VICReflect) getRow24YStop() uint16 {
	return s.ref.row24YStop
}

// setRow24YStop is the generated setter for the row24YStop field.
func (s *VICReflect) setRow24YStop(v uint16) error {
	s.ref.row24YStop = v
	return nil
}

// getFirstDisplayedLine is the generated getter for the firstDisplayedLine.
func (s *VICReflect) getFirstDisplayedLine() uint16 {
	return s.ref.firstDisplayedLine
}

// setFirstDisplayedLine is the generated setter for the firstDisplayedLine field.
func (s *VICReflect) setFirstDisplayedLine(v uint16) error {
	s.ref.firstDisplayedLine = v
	return nil
}

// getLastDisplayedLine is the generated getter for the lastDisplayedLine.
func (s *VICReflect) getLastDisplayedLine() uint16 {
	return s.ref.lastDisplayedLine
}

// setLastDisplayedLine is the generated setter for the lastDisplayedLine field.
func (s *VICReflect) setLastDisplayedLine(v uint16) error {
	s.ref.lastDisplayedLine = v
	return nil
}

// getCr1 is the generated getter for the cr1.
func (s *VICReflect) getCr1() uint8 {
	return s.ref.cr1
}

// setCr1 is the generated setter for the cr1 field.
func (s *VICReflect) setCr1(v uint8) error {
	s.ref.cr1 = v
	return nil
}

// getCr2 is the generated getter for the cr2.
func (s *VICReflect) getCr2() uint8 {
	return s.ref.cr2
}

// setCr2 is the generated setter for the cr2 field.
func (s *VICReflect) setCr2(v uint8) error {
	s.ref.cr2 = v
	return nil
}

// getRasterX is the generated getter for the rasterX.
func (s *VICReflect) getRasterX() uint16 {
	return s.ref.rasterX
}

// setRasterX is the generated setter for the rasterX field.
func (s *VICReflect) setRasterX(v uint16) error {
	s.ref.rasterX = v
	return nil
}

// getRasterY is the generated getter for the rasterY.
func (s *VICReflect) getRasterY() uint16 {
	return s.ref.rasterY
}

// setRasterY is the generated setter for the rasterY field.
func (s *VICReflect) setRasterY(v uint16) error {
	s.ref.rasterY = v
	return nil
}

// getRasterYMax is the generated getter for the rasterYMax.
func (s *VICReflect) getRasterYMax() uint16 {
	return s.ref.rasterYMax
}

// setRasterYMax is the generated setter for the rasterYMax field.
func (s *VICReflect) setRasterYMax(v uint16) error {
	s.ref.rasterYMax = v
	return nil
}

// getBaLow is the generated getter for the baLow.
func (s *VICReflect) getBaLow() bool {
	return s.ref.baLow
}

// setBaLow is the generated setter for the baLow field.
func (s *VICReflect) setBaLow(v bool) error {
	s.ref.baLow = v
	return nil
}

// getAecLow is the generated getter for the aecLow.
func (s *VICReflect) getAecLow() bool {
	return s.ref.aecLow
}

// setAecLow is the generated setter for the aecLow field.
func (s *VICReflect) setAecLow(v bool) error {
	s.ref.aecLow = v
	return nil
}

// getAecLowNextCycle is the generated getter for the aecLowNextCycle.
func (s *VICReflect) getAecLowNextCycle() uint64 {
	return s.ref.aecLowNextCycle
}

// setAecLowNextCycle is the generated setter for the aecLowNextCycle field.
func (s *VICReflect) setAecLowNextCycle(v uint64) error {
	s.ref.aecLowNextCycle = v
	return nil
}

// getVBlankNextCycle is the generated getter for the vBlankNextCycle.
func (s *VICReflect) getVBlankNextCycle() bool {
	return s.ref.vBlankNextCycle
}

// setVBlankNextCycle is the generated setter for the vBlankNextCycle field.
func (s *VICReflect) setVBlankNextCycle(v bool) error {
	s.ref.vBlankNextCycle = v
	return nil
}

// getDrawLine is the generated getter for the drawLine.
func (s *VICReflect) getDrawLine() bool {
	return s.ref.drawLine
}

// setDrawLine is the generated setter for the drawLine field.
func (s *VICReflect) setDrawLine(v bool) error {
	s.ref.drawLine = v
	return nil
}
