package mos6569

// Code generated by symphony-generator. DO NOT EDIT.

import (
	"errors"
	"github.com/markel1974/c64emu/src/references"
)

const (
	reflectDmaFlagsId           = "dmaFlags"
	reflectSpriteFlagsId        = "spriteFlags"
	reflectCurrentSpriteFlagsId = "currentSpriteFlags"
	reflectYExpansionId         = "yExpansion"
	reflectMXxId                = "mXx"
	reflectMXyId                = "mXy"
	reflectMXcId                = "mXc"
	reflectMx8Id                = "mx8"
	reflectMmcId                = "mmc"
	reflectMxeId                = "mxe"
	reflectMeId                 = "me"
	reflectMyeId                = "mye"
	reflectMdpId                = "mdp"
	reflectMm0Id                = "mm0"
	reflectMm1Id                = "mm1"
	reflectBufferIndexId        = "bufferIndex"
)

type SpritesUnitReflect struct {
	ref              *SpritesUnit
	outOfBoundsError error
	readOnlyError    error
}

func NewSpritesUnitReflect(r *SpritesUnit, factory references.IComponentFactory, parent references.IComponent, identifier string, instance int, hardwareId string) *SpritesUnitReflect {
	reflector := &SpritesUnitReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.BaseComponent.Register(factory, parent, identifier, instance, r, hardwareId)
	r.PropertyAdd(reflectDmaFlagsId, "dmaFlags represents the active Direct MemoryUnit Access (DMA) flags for sprite operations in the current cycle.", false, reflector.getDmaFlags, reflector.setDmaFlags)

	r.PropertyAdd(reflectSpriteFlagsId, "spriteFlags represents the combined state of sprite display activity for the current line in the VIC-II system.", false, reflector.getSpriteFlags, reflector.setSpriteFlags)

	r.PropertyAdd(reflectCurrentSpriteFlagsId, "currentSpriteFlags represents the active display flags for sprites, updated based on their DMA state and counters.", false, reflector.getCurrentSpriteFlags, reflector.setCurrentSpriteFlags)

	r.PropertyAdd(reflectYExpansionId, "8 sprite y expansion FlipFlops", false, reflector.getYExpansion, reflector.setYExpansion)

	r.PropertyAdd(reflectMXxId, "VIC registers [m0x - m1x - m2x - m3x - m4x - m5x - m6x - m7x]", false, reflector.getMXx, reflector.setMXx)

	_ = r.CommandAdd("getMXxEntry", "VIC registers [m0x - m1x - m2x - m3x - m4x - m5x - m6x - m7x]", reflector.getMXxEntry)
	_ = r.CommandAdd("setMXxEntry", "VIC registers [m0x - m1x - m2x - m3x - m4x - m5x - m6x - m7x]", reflector.setMXxEntry)

	r.PropertyAdd(reflectMXyId, "VIC registers [m0y - m1y - m2y - m3y - m4y - m5y - m6y - m7y]", false, reflector.getMXy, reflector.setMXy)

	_ = r.CommandAdd("getMXyEntry", "VIC registers [m0y - m1y - m2y - m3y - m4y - m5y - m6y - m7y]", reflector.getMXyEntry)
	_ = r.CommandAdd("setMXyEntry", "VIC registers [m0y - m1y - m2y - m3y - m4y - m5y - m6y - m7y]", reflector.setMXyEntry)

	r.PropertyAdd(reflectMXcId, "VIC registers [m0c - m1c - m2c - m3c - m4c - m5c - m6c - m7c]", false, reflector.getMXc, reflector.setMXc)

	_ = r.CommandAdd("getMXcEntry", "VIC registers [m0c - m1c - m2c - m3c - m4c - m5c - m6c - m7c]", reflector.getMXcEntry)
	_ = r.CommandAdd("setMXcEntry", "VIC registers [m0c - m1c - m2c - m3c - m4c - m5c - m6c - m7c]", reflector.setMXcEntry)

	r.PropertyAdd(reflectMx8Id, "VIC register", false, reflector.getMx8, reflector.setMx8)

	r.PropertyAdd(reflectMmcId, "VIC register", false, reflector.getMmc, reflector.setMmc)

	r.PropertyAdd(reflectMxeId, "VIC register", false, reflector.getMxe, reflector.setMxe)

	r.PropertyAdd(reflectMeId, "Sprite Enabled", false, reflector.getMe, reflector.setMe)

	r.PropertyAdd(reflectMyeId, "VIC register", false, reflector.getMye, reflector.setMye)

	r.PropertyAdd(reflectMdpId, "Sprite data priority", false, reflector.getMdp, reflector.setMdp)

	r.PropertyAdd(reflectMm0Id, "Mm0", false, reflector.getMm0, reflector.setMm0)

	r.PropertyAdd(reflectMm1Id, "Mm1", false, reflector.getMm1, reflector.setMm1)

	r.PropertyAdd(reflectBufferIndexId, "BufferIndex", false, reflector.getBufferIndex, reflector.setBufferIndex)

	_ = r.CommandAdd("WriteMMc", "WriteMMc(data) - WriteMMc updates the mmc field and calls ModeUpdate on all sprites to refresh their rendering mode with updated flags.", r.WriteMMc)
	_ = r.CommandAdd("WriteMXx0", "WriteMXx0(data) - WriteMXx0 updates the lower byte of the first mXx element with the provided data while preserving the upper byte.", r.WriteMXx0)
	_ = r.CommandAdd("ReadMXc5", "ReadMXc5() uint8 - ReadMXc5 retrieves and returns the modified value of the sixth multi-color register for the sprite system.", r.ReadMXc5)
	_ = r.CommandAdd("ReadMXy0", "ReadMXy0() uint8 - ReadMXy0 retrieves the first element of the mXy array, representing the Y-coordinate-related sprite data.", r.ReadMXy0)
	_ = r.CommandAdd("WriteMXc3", "WriteMXc3(data) - WriteMXc3 assigns the given data to the fourth index of the mXc array in the SpritesUnit.", r.WriteMXc3)
	_ = r.CommandAdd("Emulate", "Emulate() - Emulate executes a single emulation step for sprite processing, handling rendering, collisions, and DMA updates.", r.Emulate)
	_ = r.CommandAdd("WriteMXx6", "WriteMXx6(data) - WriteMXx6 writes the provided 8-bit data to the lower byte of the mXx[6] field, preserving the upper byte.", r.WriteMXx6)
	_ = r.CommandAdd("WriteMXy6", "WriteMXy6(data) - WriteMXy6 sets the seventh element of the mXy array to the specified data value.", r.WriteMXy6)
	_ = r.CommandAdd("WriteMXc2", "WriteMXc2(data) - WriteMXc2 sets the third element (index 2) of the mXc array in the SpritesUnit to the specified data value.", r.WriteMXc2)
	_ = r.CommandAdd("WriteMXy3", "WriteMXy3(data) - WriteMXy3 sets the value of the fourth element in the mXy slice to the specified data.", r.WriteMXy3)
	_ = r.CommandAdd("ReadBufferIndex", "ReadBufferIndex() int - ", r.ReadBufferIndex)
	_ = r.CommandAdd("ReadMXc0", "ReadMXc0() uint8 - ReadMXc0 reads and returns the first element of the mXc array combined with a fixed mask of 0xf0.", r.ReadMXc0)
	_ = r.CommandAdd("ReadMXc7", "ReadMXc7() uint8 - ReadMXc7 retrieves the 8th sprite's collision configuration, combining it with a constant value of 0xf0.", r.ReadMXc7)
	_ = r.CommandAdd("ReadMXy2", "ReadMXy2() uint8 - ReadMXy2 retrieves the Y-coordinate value of the third sprite (index 2) from the internal mXy array.", r.ReadMXy2)
	_ = r.CommandAdd("ReadMXx3", "ReadMXx3() uint8 - ReadMXx3 retrieves the value of the fourth element in the mXx slice of SpritesUnit as an unsigned 8-bit integer.", r.ReadMXx3)
	_ = r.CommandAdd("ReadMXx7", "ReadMXx7() uint8 - ReadMXx7 returns the 8th element of the mXx array as a uint8 representing the X-coordinate of sprite 7.", r.ReadMXx7)
	_ = r.CommandAdd("ReadMXy7", "ReadMXy7() uint8 - ReadMXy7 retrieves the value stored at index 7 of the mXy array in the SpritesUnit.", r.ReadMXy7)
	_ = r.CommandAdd("ReadMYe", "ReadMYe() uint8 - ReadMYe retrieves the current Sprite Y expansion value.", r.ReadMYe)
	_ = r.CommandAdd("ReadMXe", "ReadMXe() uint8 - ReadMXe retrieves the current state of the sprite's X expansion flag.", r.ReadMXe)
	_ = r.CommandAdd("WriteMYe", "WriteMYe(data) - WriteMYe sets the sprite Y expansion register with the provided data.  Updates the internal `yExpansion` state based on the input value.", r.WriteMYe)
	_ = r.CommandAdd("WriteMe", "WriteMe(data) - WriteMe sets the sprite enable register to the provided data value.", r.WriteMe)
	_ = r.CommandAdd("WriteMXx2", "WriteMXx2(data) - WriteMXx2 updates the lower byte of the third element in the mXx array with the provided uint8 data value.", r.WriteMXx2)
	_ = r.CommandAdd("WriteMX8", "WriteMX8(data) - WriteMX8 updates the MSBs of X coordinates for sprite handling based on the given data.", r.WriteMX8)
	_ = r.CommandAdd("WriteMXc0", "WriteMXc0(data) - WriteMXc0 assigns the provided uint8 data value to the first element of the mXc array in the SpritesUnit.", r.WriteMXc0)
	_ = r.CommandAdd("ReadMXc2", "ReadMXc2() uint8 - ReadMXc2 reads the third value from the mXc array and combines it with 0xf0 using bitwise OR, returning the result.", r.ReadMXc2)
	_ = r.CommandAdd("WriteMXc5", "WriteMXc5(data) - WriteMXc5 updates the fifth element of the mXc slice with the provided 8-bit unsigned integer data.", r.WriteMXc5)
	_ = r.CommandAdd("WriteMXc6", "WriteMXc6(data) - WriteMXc6 writes the provided data to the 6th index of the mXc slice in the SpritesUnit.", r.WriteMXc6)
	_ = r.CommandAdd("UpdateYExpansion", "UpdateYExpansion() - UpdateYExpansion adjusts the sprite's vertical expansion state based on the MYE register using an inversion technique.", r.UpdateYExpansion)
	_ = r.CommandAdd("ActivateSprite", "ActivateSprite(sNum) - ActivateSprite sets the active sprite to the one specified by the index sNum.", r.ActivateSprite)
	_ = r.CommandAdd("TryIncrementCounterBase", "TryIncrementCounterBase() - TryIncrementCounterBase checks sprite vertical expansion state and conditionally increments the sprite's internal row counter.", r.TryIncrementCounterBase)
	_ = r.CommandAdd("WriteMXx3", "WriteMXx3(data) - WriteMXx3 updates the lowest 8 bits of the fourth element in the mXx array with the provided data.", r.WriteMXx3)
	_ = r.CommandAdd("GetDMAFlag", "GetDMAFlag(b) uint8 - GetDMAFlag checks and returns the active DMA flag for the specified sprite(s) by performing a bitwise AND operation.", r.GetDMAFlag)
	_ = r.CommandAdd("ReadData", "ReadData(bNum) - ReadData reads a byte of data from memory using the calculated address and sets it within the active SpriteUnit state.", r.ReadData)
	_ = r.CommandAdd("UpdateDMA", "UpdateDMA(rasterY) - UpdateDMA updates the Direct MemoryUnit Access (DMA) flags for sprites at the current raster line position.  It resets the counter-base for active sprites and handles vertical expansion mode and line-specific configurations.", r.UpdateDMA)
	_ = r.CommandAdd("ReadMDp", "ReadMDp() uint8 - ReadMDp retrieves the sprite data priority (MDp) from the SpritesUnit and returns it as an unsigned 8-bit integer.", r.ReadMDp)
	_ = r.CommandAdd("ReadMX8", "ReadMX8() uint8 - ReadMX8 retrieves the most significant bit (MSB) of sprite X positions.  Returns the value of the mx8 field as an 8-bit unsigned integer.", r.ReadMX8)
	_ = r.CommandAdd("WriteMXc7", "WriteMXc7(data) - WriteMXc7 sets the 7th index of the mXc array to the provided uint8 data value.", r.WriteMXc7)
	_ = r.CommandAdd("ReadMM1", "ReadMM1() uint8 - ReadMM1 returns the result of the bitwise OR operation between the mm1 field and the constant 0xf0.", r.ReadMM1)
	_ = r.CommandAdd("ReadMXc1", "ReadMXc1() uint8 - ReadMXc1 returns the second element of the mXc array bitwise OR'd with 0xf0.", r.ReadMXc1)
	_ = r.CommandAdd("WriteMM1", "WriteMM1(data) - WriteMM1 sets the value of the mm1 property in the SpritesUnit instance using the provided 8-bit unsigned integer.", r.WriteMM1)
	_ = r.CommandAdd("WriteMXy2", "WriteMXy2(data) - WriteMXy2 sets the third index of the mXy slice to the specified data value.", r.WriteMXy2)
	_ = r.CommandAdd("ReadMXy4", "ReadMXy4() uint8 - ReadMXy4 retrieves the Y-coordinate value for the sprite stored at index 4 in the mXy array.", r.ReadMXy4)
	_ = r.CommandAdd("ReadMXx5", "ReadMXx5() uint8 - ReadMXx5 returns the value of the 6th element in the mXx array as an unsigned 8-bit integer.", r.ReadMXx5)
	_ = r.CommandAdd("ReadMXx6", "ReadMXx6() uint8 - ReadMXx6 retrieves the X-coordinate value of the 6th sprite from the internal mXx array of the SpritesUnit.", r.ReadMXx6)
	_ = r.CommandAdd("WriteMXy0", "WriteMXy0(data) - WriteMXy0 updates the first element of the SpritesUnit's mXy slice with the provided data value.", r.WriteMXy0)
	_ = r.CommandAdd("WriteMXy4", "WriteMXy4(data) - WriteMXy4 sets the fifth element of the mXy array in SpritesUnit to the provided uint8 data value.", r.WriteMXy4)
	_ = r.CommandAdd("WriteMXc4", "WriteMXc4(data) - WriteMXc4 writes a uint8 value to the fifth element of the mXc array within the SpritesUnit struct.", r.WriteMXc4)
	_ = r.CommandAdd("Reset", "Reset() - Reset reinitializes the SpritesUnit's internal state and configurations to its default settings.", r.Reset)
	_ = r.CommandAdd("WriteBufferIndex", "WriteBufferIndex(index) - ", r.WriteBufferIndex)
	_ = r.CommandAdd("ReadMMc", "ReadMMc() uint8 - ReadMMc returns the sprite multicolor configuration stored in the `mmc` field of the SpritesUnit.", r.ReadMMc)
	_ = r.CommandAdd("WriteMDp", "WriteMDp(data) - WriteMDp sets the sprite data priority (mdp) to the provided uint8 value.", r.WriteMDp)
	_ = r.CommandAdd("WriteMXx4", "WriteMXx4(data) - WriteMXx4 updates the lower 8 bits of the fifth element in the mXx array with the given uint8 data value.", r.WriteMXx4)
	_ = r.CommandAdd("ReadPtr", "ReadPtr(base) - ReadPtr reads a sprite pointer from memory and sets the active sprite's pointer to the calculated address.", r.ReadPtr)
	_ = r.CommandAdd("ReadMe", "ReadMe() uint8 - ReadMe returns the current value of the sprite enable flag stored in the 'me' field.", r.ReadMe)
	_ = r.CommandAdd("ReadMXy1", "ReadMXy1() uint8 - ReadMXy1 retrieves the Y position of the second sprite from the mXy array.", r.ReadMXy1)
	_ = r.CommandAdd("ReadMXx2", "ReadMXx2() uint8 - ReadMXx2 retrieves the X-coordinate of the third sprite from the internal mXx array as an unsigned 8-bit integer.", r.ReadMXx2)
	_ = r.CommandAdd("ReadMXy3", "ReadMXy3() uint8 - ReadMXy3 retrieves the Y coordinate value of the third sprite from the internal mXy array.  It returns a uint8 representing the Y coordinate.", r.ReadMXy3)
	_ = r.CommandAdd("WriteMM0", "WriteMM0(data) - WriteMM0 assigns the provided 8-bit unsigned integer value to the mm0 field of the SpritesUnit instance.", r.WriteMM0)
	_ = r.CommandAdd("WriteMXx1", "WriteMXx1(data) - WriteMXx1 updates the lower 8 bits of the mXx[1] field with the provided data value, preserving the upper 8 bits.", r.WriteMXx1)
	_ = r.CommandAdd("CommitIncrementCounterBase", "CommitIncrementCounterBase() - CommitIncrementCounterBase ensures sprite row counters are updated, and disables DMA flags for sprites reaching their row end.", r.CommitIncrementCounterBase)
	_ = r.CommandAdd("ReadMXc4", "ReadMXc4() uint8 - ReadMXc4 returns the value of the fifth element of the mXc array OR'ed with 0xf0.", r.ReadMXc4)
	_ = r.CommandAdd("WriteMXe", "WriteMXe(data) - WriteMXe updates the horizontal expansion flag (MXE) for sprites and triggers their mode update accordingly.", r.WriteMXe)
	_ = r.CommandAdd("WriteMXy5", "WriteMXy5(data) - WriteMXy5 updates the sixth element (index 5) of the mXy slice with the provided data value.", r.WriteMXy5)
	_ = r.CommandAdd("LatchAttributes", "LatchAttributes() - LatchAttributes updates the sprite's attributes by calling SetLatchAttributes with its current configuration values.", r.LatchAttributes)
	_ = r.CommandAdd("CommitSpriteFlags", "CommitSpriteFlags() - CommitSpriteFlags updates the display flags for sprites by checking and clearing flags based on DMA activity status.  It determines which sprites are currently active for display based on DMA and counter-status.", r.CommitSpriteFlags)
	_ = r.CommandAdd("Prepare", "Prepare() - ", r.Prepare)
	_ = r.CommandAdd("ReadMXc6", "ReadMXc6() uint8 - ReadMXc6 retrieves the seventh sprite's X-coordinate high bit, combined with a fixed high nibble value of 0xf.", r.ReadMXc6)
	_ = r.CommandAdd("ReadMXx1", "ReadMXx1() uint8 - ReadMXx1 retrieves the most significant bit of the x-coordinate for sprite 1 from the internal mXx array.", r.ReadMXx1)
	_ = r.CommandAdd("ReadMXy6", "ReadMXy6() uint8 - ReadMXy6 retrieves the Y-coordinate value of the 6th sprite from the mXy array.", r.ReadMXy6)
	_ = r.CommandAdd("WriteMXy7", "WriteMXy7(data) - WriteMXy7 sets the 8th index of the mXy slice in the SpritesUnit to the provided uint8 value.", r.WriteMXy7)
	_ = r.CommandAdd("ReadMM0", "ReadMM0() uint8 - ReadMM0 returns the mm0 value of the sprite with the upper nibble set to 0xf.", r.ReadMM0)
	_ = r.CommandAdd("ReadMXc3", "ReadMXc3() uint8 - ReadMXc3 reads the fourth element of the mXc array, applies a bitwise OR with 0xf0, and returns the resulting value.", r.ReadMXc3)
	_ = r.CommandAdd("ReadMXx0", "ReadMXx0() uint8 - ReadMXx0 returns the least-significant byte of the X-coordinate for the first sprite stored in the mXx array.", r.ReadMXx0)
	_ = r.CommandAdd("ReadMXx4", "ReadMXx4() uint8 - ReadMXx4 retrieves the fourth horizontal position value for a sprite from the mXx array in the SpritesUnit.", r.ReadMXx4)
	_ = r.CommandAdd("ReadMXy5", "ReadMXy5() uint8 - ReadMXy5 retrieves the Y-coordinate of the sixth sprite from the mXy array in the SpritesUnit struct.", r.ReadMXy5)
	_ = r.CommandAdd("WriteMXx5", "WriteMXx5(data) - WriteMXx5 writes an 8-bit value to the lower 8 bits of the 6th element in the mXx array.", r.WriteMXx5)
	_ = r.CommandAdd("PrepareSpriteFlags", "PrepareSpriteFlags(rasterY) - PrepareSpriteFlags updates the current sprite display flags based on DMA activity and the current raster line position.", r.PrepareSpriteFlags)
	_ = r.CommandAdd("WriteMXy1", "WriteMXy1(data) - WriteMXy1 writes the given uint8 data to the second index (1) of the mXy slice in the SpritesUnit struct.", r.WriteMXy1)
	_ = r.CommandAdd("WriteMXx7", "WriteMXx7(data) - WriteMXx7 updates the lower 8 bits of the 7th element in the mXx array with the provided data while preserving the upper bits.", r.WriteMXx7)
	_ = r.CommandAdd("WriteMXc1", "WriteMXc1(data) - WriteMXc1 sets the second element of the mXc slice to the provided data value.", r.WriteMXc1)
	_ = r.CommandAdd("Draw", "Draw() - Draw renders all active sprites for the current line based on their flags, properties, and configurations.  It handles both expanded and unexpanded sprites in standard and multicolor modes.  Collision detection for sprites is carried out during the rendering process.", r.Draw)

	return reflector
}

// getDmaFlags is the generated getter for the dmaFlags.
func (s *SpritesUnitReflect) getDmaFlags() uint8 {
	return s.ref.dmaFlags
}

// setDmaFlags is the generated setter for the dmaFlags field.
func (s *SpritesUnitReflect) setDmaFlags(v uint8) error {
	s.ref.dmaFlags = v
	return nil
}

// getSpriteFlags is the generated getter for the spriteFlags.
func (s *SpritesUnitReflect) getSpriteFlags() uint8 {
	return s.ref.spriteFlags
}

// setSpriteFlags is the generated setter for the spriteFlags field.
func (s *SpritesUnitReflect) setSpriteFlags(v uint8) error {
	s.ref.spriteFlags = v
	return nil
}

// getCurrentSpriteFlags is the generated getter for the currentSpriteFlags.
func (s *SpritesUnitReflect) getCurrentSpriteFlags() uint8 {
	return s.ref.currentSpriteFlags
}

// setCurrentSpriteFlags is the generated setter for the currentSpriteFlags field.
func (s *SpritesUnitReflect) setCurrentSpriteFlags(v uint8) error {
	s.ref.currentSpriteFlags = v
	return nil
}

// getYExpansion is the generated getter for the yExpansion.
func (s *SpritesUnitReflect) getYExpansion() uint8 {
	return s.ref.yExpansion
}

// setYExpansion is the generated setter for the yExpansion field.
func (s *SpritesUnitReflect) setYExpansion(v uint8) error {
	s.ref.yExpansion = v
	return nil
}

// getMXx is the generated getter for the mXx.
func (s *SpritesUnitReflect) getMXx() []uint16 {
	return s.ref.mXx
}

// setMXx is the generated setter for the mXx field.
func (s *SpritesUnitReflect) setMXx(v []uint16) error {
	copy(s.ref.mXx, v)
	return nil
}

// getMXxEntry is the generated indexed getter for the mXx.
func (s *SpritesUnitReflect) getMXxEntry(idx int) (uint16, error) {
	if idx >= 0 && idx < len(s.ref.mXx) {
		return s.ref.mXx[idx], nil
	}
	return *new(uint16), s.outOfBoundsError
}

// setMXxEntry is the generated indexed setter for the mXx.
func (s *SpritesUnitReflect) setMXxEntry(idx int, v uint16) error {
	if idx >= 0 && idx < len(s.ref.mXx) {
		s.ref.mXx[idx] = v
		return nil
	}
	return errors.New("index out of bounds")
}

// getMXy is the generated getter for the mXy.
func (s *SpritesUnitReflect) getMXy() []uint8 {
	return s.ref.mXy
}

// setMXy is the generated setter for the mXy field.
func (s *SpritesUnitReflect) setMXy(v []uint8) error {
	copy(s.ref.mXy, v)
	return nil
}

// getMXyEntry is the generated indexed getter for the mXy.
func (s *SpritesUnitReflect) getMXyEntry(idx int) (uint8, error) {
	if idx >= 0 && idx < len(s.ref.mXy) {
		return s.ref.mXy[idx], nil
	}
	return *new(uint8), s.outOfBoundsError
}

// setMXyEntry is the generated indexed setter for the mXy.
func (s *SpritesUnitReflect) setMXyEntry(idx int, v uint8) error {
	if idx >= 0 && idx < len(s.ref.mXy) {
		s.ref.mXy[idx] = v
		return nil
	}
	return errors.New("index out of bounds")
}

// getMXc is the generated getter for the mXc.
func (s *SpritesUnitReflect) getMXc() []uint8 {
	return s.ref.mXc
}

// setMXc is the generated setter for the mXc field.
func (s *SpritesUnitReflect) setMXc(v []uint8) error {
	copy(s.ref.mXc, v)
	return nil
}

// getMXcEntry is the generated indexed getter for the mXc.
func (s *SpritesUnitReflect) getMXcEntry(idx int) (uint8, error) {
	if idx >= 0 && idx < len(s.ref.mXc) {
		return s.ref.mXc[idx], nil
	}
	return *new(uint8), s.outOfBoundsError
}

// setMXcEntry is the generated indexed setter for the mXc.
func (s *SpritesUnitReflect) setMXcEntry(idx int, v uint8) error {
	if idx >= 0 && idx < len(s.ref.mXc) {
		s.ref.mXc[idx] = v
		return nil
	}
	return errors.New("index out of bounds")
}

// getMx8 is the generated getter for the mx8.
func (s *SpritesUnitReflect) getMx8() uint8 {
	return s.ref.mx8
}

// setMx8 is the generated setter for the mx8 field.
func (s *SpritesUnitReflect) setMx8(v uint8) error {
	s.ref.mx8 = v
	return nil
}

// getMmc is the generated getter for the mmc.
func (s *SpritesUnitReflect) getMmc() uint8 {
	return s.ref.mmc
}

// setMmc is the generated setter for the mmc field.
func (s *SpritesUnitReflect) setMmc(v uint8) error {
	s.ref.mmc = v
	return nil
}

// getMxe is the generated getter for the mxe.
func (s *SpritesUnitReflect) getMxe() uint8 {
	return s.ref.mxe
}

// setMxe is the generated setter for the mxe field.
func (s *SpritesUnitReflect) setMxe(v uint8) error {
	s.ref.mxe = v
	return nil
}

// getMe is the generated getter for the me.
func (s *SpritesUnitReflect) getMe() uint8 {
	return s.ref.me
}

// setMe is the generated setter for the me field.
func (s *SpritesUnitReflect) setMe(v uint8) error {
	s.ref.me = v
	return nil
}

// getMye is the generated getter for the mye.
func (s *SpritesUnitReflect) getMye() uint8 {
	return s.ref.mye
}

// setMye is the generated setter for the mye field.
func (s *SpritesUnitReflect) setMye(v uint8) error {
	s.ref.mye = v
	return nil
}

// getMdp is the generated getter for the mdp.
func (s *SpritesUnitReflect) getMdp() uint8 {
	return s.ref.mdp
}

// setMdp is the generated setter for the mdp field.
func (s *SpritesUnitReflect) setMdp(v uint8) error {
	s.ref.mdp = v
	return nil
}

// getMm0 is the generated getter for the mm0.
func (s *SpritesUnitReflect) getMm0() uint8 {
	return s.ref.mm0
}

// setMm0 is the generated setter for the mm0 field.
func (s *SpritesUnitReflect) setMm0(v uint8) error {
	s.ref.mm0 = v
	return nil
}

// getMm1 is the generated getter for the mm1.
func (s *SpritesUnitReflect) getMm1() uint8 {
	return s.ref.mm1
}

// setMm1 is the generated setter for the mm1 field.
func (s *SpritesUnitReflect) setMm1(v uint8) error {
	s.ref.mm1 = v
	return nil
}

// getBufferIndex is the generated getter for the bufferIndex.
func (s *SpritesUnitReflect) getBufferIndex() int {
	return s.ref.bufferIndex
}

// setBufferIndex is the generated setter for the bufferIndex field.
func (s *SpritesUnitReflect) setBufferIndex(v int) error {
	s.ref.bufferIndex = v
	return nil
}
