package mos6569

// Code generated by symphony-generator. DO NOT EDIT.

import (
	"errors"
	"github.com/markel1974/c64emu/src/references"
)

const (
	reflectXId         = "x"
	reflectYId         = "y"
	reflectTriggeredId = "triggered"
)

type LightPenReflect struct {
	ref              *LightPen
	outOfBoundsError error
	readOnlyError    error
}

func NewLightPenReflect(r *LightPen, factory references.IComponentFactory, parent references.IComponent, identifier string, instance int, hardwareId string) *LightPenReflect {
	reflector := &LightPenReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.BaseComponent.Register(factory, parent, identifier, instance, r, hardwareId)
	r.PropertyAdd(reflectXId, "X", false, reflector.getX, reflector.setX)

	r.PropertyAdd(reflectYId, "Y", false, reflector.getY, reflector.setY)

	r.PropertyAdd(reflectTriggeredId, "Triggered", false, reflector.getTriggered, reflector.setTriggered)

	_ = r.CommandAdd("Emulate", "Emulate() - Emulate processes the light pen's behavior for the current emulation frame, checking its state and coordinating updates.", r.Emulate)
	_ = r.CommandAdd("Reset", "Reset() - Reset reinitializes the LightPen's state, clearing its coordinates and triggered status to defaults.", r.Reset)
	_ = r.CommandAdd("Trigger", "Trigger(rasterX, rasterY) - Trigger sets the light pen as triggered and records the given raster coordinates (rasterX, rasterY).  It also emits an interrupt using the specified light pen interrupt bit.  If the light pen is already triggered, this method does nothing.", r.Trigger)
	_ = r.CommandAdd("TriggerClear", "TriggerClear() - TriggerClear resets the light pen's triggered state to false, indicating it has not been activated.", r.TriggerClear)
	_ = r.CommandAdd("ReadX", "ReadX() uint8 - ReadX retrieves the current X-coordinate value of the light pen.", r.ReadX)
	_ = r.CommandAdd("ReadY", "ReadY() uint8 - ReadY returns the Y-coordinate stored by the LightPen, representing the last triggered position on the raster.", r.ReadY)
	_ = r.CommandAdd("WriteX", "WriteX(data) - WriteX sets the X-coordinate of the LightPen by updating the internal lpx register with the provided data.", r.WriteX)
	_ = r.CommandAdd("WriteY", "WriteY(data) - WriteY sets the LightPen's internal lpx register to the specified data value.", r.WriteY)

	return reflector
}

// getX is the generated getter for the x.
func (s *LightPenReflect) getX() uint8 {
	return s.ref.x
}

// setX is the generated setter for the x field.
func (s *LightPenReflect) setX(v uint8) error {
	s.ref.x = v
	return nil
}

// getY is the generated getter for the y.
func (s *LightPenReflect) getY() uint8 {
	return s.ref.y
}

// setY is the generated setter for the y field.
func (s *LightPenReflect) setY(v uint8) error {
	s.ref.y = v
	return nil
}

// getTriggered is the generated getter for the triggered.
func (s *LightPenReflect) getTriggered() bool {
	return s.ref.triggered
}

// setTriggered is the generated setter for the triggered field.
func (s *LightPenReflect) setTriggered(v bool) error {
	s.ref.triggered = v
	return nil
}
