package mos6569

// Code generated by symphony-generator. DO NOT EDIT.

import (
	"errors"
	"github.com/markel1974/symphony/src/references"
)

const (
	reflectBgrStateId         = "bgrState"
	reflectSprStateId         = "sprState"
	reflectSprPresenceId      = "sprPresence"
	reflectBgrBufferId        = "bgrBuffer"
	reflectBgrBufferOffsetId  = "bgrBufferOffset"
	reflectSpr2BgrClxId       = "spr2BgrClx"
	reflectSpr2SprClxId       = "spr2SprClx"
	reflectSprPresenceEmptyId = "sprPresenceEmpty"
	reflectBgrBufferEmptyId   = "bgrBufferEmpty"
)

type CollisionsUnitReflect struct {
	ref              *CollisionsUnit
	outOfBoundsError error
	readOnlyError    error
}

func NewCollisionsUnitReflect(r *CollisionsUnit, factory references.IComponentFactory, parent references.IComponent, identifier string, instance int, hardwareId string) *CollisionsUnitReflect {
	reflector := &CollisionsUnitReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.BaseComponent.Register(factory, parent, identifier, instance, r, hardwareId)
	r.PropertyAdd(reflectBgrStateId, "bgrState represents the collision state of all graphics in the current line.", false, reflector.getBgrState, reflector.setBgrState)

	r.PropertyAdd(reflectSprStateId, "sprState represent the state and collision mask of all active sprites in the current line.", false, reflector.getSprState, reflector.setSprState)

	r.PropertyAdd(reflectSprPresenceId, "sprPresence stores the state of sprite presence at each pixel, used for collision detection within the line.", false, reflector.getSprPresence, reflector.setSprPresence)

	_ = r.CommandAdd("getSprPresenceEntry", "sprPresence stores the state of sprite presence at each pixel, used for collision detection within the line.", reflector.getSprPresenceEntry)
	_ = r.CommandAdd("setSprPresenceEntry", "sprPresence stores the state of sprite presence at each pixel, used for collision detection within the line.", reflector.setSprPresenceEntry)

	r.PropertyAdd(reflectBgrBufferId, "bgrBuffer holds the collision state for background bgrState.", false, reflector.getBgrBuffer, reflector.setBgrBuffer)

	_ = r.CommandAdd("getBgrBufferEntry", "bgrBuffer holds the collision state for background bgrState.", reflector.getBgrBufferEntry)
	_ = r.CommandAdd("setBgrBufferEntry", "bgrBuffer holds the collision state for background bgrState.", reflector.setBgrBufferEntry)

	r.PropertyAdd(reflectBgrBufferOffsetId, "bgrBufferOffset tracks the current position in the bgrState buffer for collision updates.", false, reflector.getBgrBufferOffset, reflector.setBgrBufferOffset)

	r.PropertyAdd(reflectSpr2BgrClxId, "spr2BgrClx sprite to background collision", false, reflector.getSpr2BgrClx, reflector.setSpr2BgrClx)

	r.PropertyAdd(reflectSpr2SprClxId, "spr2SprClx sprite to sprite collision", false, reflector.getSpr2SprClx, reflector.setSpr2SprClx)

	r.PropertyAdd(reflectSprPresenceEmptyId, "sprPresenceEmpty is the initialized buffer used to reset sprite collision states for each line.", false, reflector.getSprPresenceEmpty, reflector.setSprPresenceEmpty)

	_ = r.CommandAdd("getSprPresenceEmptyEntry", "sprPresenceEmpty is the initialized buffer used to reset sprite collision states for each line.", reflector.getSprPresenceEmptyEntry)
	_ = r.CommandAdd("setSprPresenceEmptyEntry", "sprPresenceEmpty is the initialized buffer used to reset sprite collision states for each line.", reflector.setSprPresenceEmptyEntry)

	r.PropertyAdd(reflectBgrBufferEmptyId, "bgrBufferEmpty holds an initialized empty buffer for resetting or clearing bgrState collision data.", false, reflector.getBgrBufferEmpty, reflector.setBgrBufferEmpty)

	_ = r.CommandAdd("getBgrBufferEmptyEntry", "bgrBufferEmpty holds an initialized empty buffer for resetting or clearing bgrState collision data.", reflector.getBgrBufferEmptyEntry)
	_ = r.CommandAdd("setBgrBufferEmptyEntry", "bgrBufferEmpty holds an initialized empty buffer for resetting or clearing bgrState collision data.", reflector.setBgrBufferEmptyEntry)

	_ = r.CommandAdd("SetBackground", "SetBackground(data) - SetBackground sets the sprite-to-background collision state with the given value.", r.SetBackground)
	_ = r.CommandAdd("SetSprite2SpritePresence", "SetSprite2SpritePresence(index, spriteBit) bool - SetSprite2SpritePresence checks and sets sprite collision at a specific index with a sprite bit and returns collision status.  If a collision occurs, it updates the sprite collision state;  otherwise, it updates the sprite buffer with the new bit.", r.SetSprite2SpritePresence)
	_ = r.CommandAdd("CommitSprite", "CommitSprite() - CommitSprite updates the sprite-to-sprite collision state and triggers an interrupt if a collision occurred.", r.CommitSprite)
	_ = r.CommandAdd("CommitBackground", "CommitBackground() - CommitBackground updates the sprite-to-background collision state and triggers an interrupt if a collision is detected.", r.CommitBackground)
	_ = r.CommandAdd("ClearBackground", "ClearBackground() - ClearBackground resets the bgrState collision buffer and its offset to their initial empty states.  Called at the *beginning* of each frame.", r.ClearBackground)
	_ = r.CommandAdd("UpdateBackground", "UpdateBackground(a, b) - UpdateBackground updates the bgrState collision buffer with provided foreground mask values a and b at the current offset.  Called during *background* rendering.  'a' and 'b' represent the pixel data for two *consecutive* pixels.", r.UpdateBackground)
	_ = r.CommandAdd("IncrementBackgroundOffset", "IncrementBackgroundOffset() - IncrementBackgroundOffset increments the bgrBufferOffset field  to track the bgrState buffer position during updates.", r.IncrementBackgroundOffset)
	_ = r.CommandAdd("Emulate", "Emulate() - Emulate performs the collision emulation process for the current frame, updating internal state based on collisions detected.", r.Emulate)
	_ = r.CommandAdd("Reset", "Reset() - Reset clears all collision states and buffers, preparing the collision system for a new frame.", r.Reset)
	_ = r.CommandAdd("SetSprite2BackgroundPresence", "SetSprite2BackgroundPresence(sBit) - SetSprite2BackgroundPresence sets a collision bit for bgrState by performing a bitwise OR operation with the given bit.  'sBit' is a bitmask representing the sprite that collided with the background (1, 2, 4, 8, 16, 32, 64, 128).", r.SetSprite2BackgroundPresence)
	_ = r.CommandAdd("GetGraphicsR", "GetGraphicsR(charColumn, pixelOffset) uint32 - GetGraphicsR calculates a 32-bit bgrState mask from the bgrState buffer starting at 'charColumn+4'.  It shifts the mask by 'pixelOffset' bits to align with the intended sub-pixel bgrState position.  Returns a composite 32-bit unsigned integer representing the derived bgrState mask.", r.GetGraphicsR)
	_ = r.CommandAdd("RetrieveSprite2Sprite", "RetrieveSprite2Sprite() uint8 - RetrieveSprite2Sprite reads and clears the sprite-to-sprite collision state, returning its value as an 8-bit unsigned integer.", r.RetrieveSprite2Sprite)
	_ = r.CommandAdd("RetrieveSprite2Background", "RetrieveSprite2Background() uint8 - RetrieveSprite2Background reads and resets the sprite-to-background collision state, returning its value as an 8-bit unsigned integer.", r.RetrieveSprite2Background)
	_ = r.CommandAdd("SetSprite", "SetSprite(data) - SetSprite updates the sprite-to-sprite collision state with the specified value.", r.SetSprite)
	_ = r.CommandAdd("Prepare", "Prepare() - Prepare resets collision detection states and initializes sprite collision buffers for the next frame update.  Called at the beginning of sprite drawing on each scanline.", r.Prepare)
	_ = r.CommandAdd("GetGraphicsL", "GetGraphicsL(charColumn, pixelOffset) uint32 - GetGraphicsL computes a 32-bit bgrState mask from the bgrState buffer starting at 'charColumn' with a 'pixelOffset' adjustment.  The result is shifted and combined to align with the intended sub-pixel bgrState position, returning a 32-bit uint representation.", r.GetGraphicsL)

	return reflector
}

// getBgrState is the generated getter for the bgrState.
func (s *CollisionsUnitReflect) getBgrState() uint8 {
	return s.ref.bgrState
}

// setBgrState is the generated setter for the bgrState field.
func (s *CollisionsUnitReflect) setBgrState(v uint8) error {
	s.ref.bgrState = v
	return nil
}

// getSprState is the generated getter for the sprState.
func (s *CollisionsUnitReflect) getSprState() uint8 {
	return s.ref.sprState
}

// setSprState is the generated setter for the sprState field.
func (s *CollisionsUnitReflect) setSprState(v uint8) error {
	s.ref.sprState = v
	return nil
}

// getSprPresence is the generated getter for the sprPresence.
func (s *CollisionsUnitReflect) getSprPresence() []uint8 {
	return s.ref.sprPresence
}

// setSprPresence is the generated setter for the sprPresence field.
func (s *CollisionsUnitReflect) setSprPresence(v []uint8) error {
	copy(s.ref.sprPresence, v)
	return nil
}

// getSprPresenceEntry is the generated indexed getter for the sprPresence.
func (s *CollisionsUnitReflect) getSprPresenceEntry(idx int) (uint8, error) {
	if idx >= 0 && idx < len(s.ref.sprPresence) {
		return s.ref.sprPresence[idx], nil
	}
	return *new(uint8), s.outOfBoundsError
}

// setSprPresenceEntry is the generated indexed setter for the sprPresence.
func (s *CollisionsUnitReflect) setSprPresenceEntry(idx int, v uint8) error {
	if idx >= 0 && idx < len(s.ref.sprPresence) {
		s.ref.sprPresence[idx] = v
		return nil
	}
	return errors.New("index out of bounds")
}

// getBgrBuffer is the generated getter for the bgrBuffer.
func (s *CollisionsUnitReflect) getBgrBuffer() []uint8 {
	return s.ref.bgrBuffer
}

// setBgrBuffer is the generated setter for the bgrBuffer field.
func (s *CollisionsUnitReflect) setBgrBuffer(v []uint8) error {
	copy(s.ref.bgrBuffer, v)
	return nil
}

// getBgrBufferEntry is the generated indexed getter for the bgrBuffer.
func (s *CollisionsUnitReflect) getBgrBufferEntry(idx int) (uint8, error) {
	if idx >= 0 && idx < len(s.ref.bgrBuffer) {
		return s.ref.bgrBuffer[idx], nil
	}
	return *new(uint8), s.outOfBoundsError
}

// setBgrBufferEntry is the generated indexed setter for the bgrBuffer.
func (s *CollisionsUnitReflect) setBgrBufferEntry(idx int, v uint8) error {
	if idx >= 0 && idx < len(s.ref.bgrBuffer) {
		s.ref.bgrBuffer[idx] = v
		return nil
	}
	return errors.New("index out of bounds")
}

// getBgrBufferOffset is the generated getter for the bgrBufferOffset.
func (s *CollisionsUnitReflect) getBgrBufferOffset() int {
	return s.ref.bgrBufferOffset
}

// setBgrBufferOffset is the generated setter for the bgrBufferOffset field.
func (s *CollisionsUnitReflect) setBgrBufferOffset(v int) error {
	s.ref.bgrBufferOffset = v
	return nil
}

// getSpr2BgrClx is the generated getter for the spr2BgrClx.
func (s *CollisionsUnitReflect) getSpr2BgrClx() uint8 {
	return s.ref.spr2BgrClx
}

// setSpr2BgrClx is the generated setter for the spr2BgrClx field.
func (s *CollisionsUnitReflect) setSpr2BgrClx(v uint8) error {
	s.ref.spr2BgrClx = v
	return nil
}

// getSpr2SprClx is the generated getter for the spr2SprClx.
func (s *CollisionsUnitReflect) getSpr2SprClx() uint8 {
	return s.ref.spr2SprClx
}

// setSpr2SprClx is the generated setter for the spr2SprClx field.
func (s *CollisionsUnitReflect) setSpr2SprClx(v uint8) error {
	s.ref.spr2SprClx = v
	return nil
}

// getSprPresenceEmpty is the generated getter for the sprPresenceEmpty.
func (s *CollisionsUnitReflect) getSprPresenceEmpty() []uint8 {
	return s.ref.sprPresenceEmpty
}

// setSprPresenceEmpty is the generated setter for the sprPresenceEmpty field.
func (s *CollisionsUnitReflect) setSprPresenceEmpty(v []uint8) error {
	copy(s.ref.sprPresenceEmpty, v)
	return nil
}

// getSprPresenceEmptyEntry is the generated indexed getter for the sprPresenceEmpty.
func (s *CollisionsUnitReflect) getSprPresenceEmptyEntry(idx int) (uint8, error) {
	if idx >= 0 && idx < len(s.ref.sprPresenceEmpty) {
		return s.ref.sprPresenceEmpty[idx], nil
	}
	return *new(uint8), s.outOfBoundsError
}

// setSprPresenceEmptyEntry is the generated indexed setter for the sprPresenceEmpty.
func (s *CollisionsUnitReflect) setSprPresenceEmptyEntry(idx int, v uint8) error {
	if idx >= 0 && idx < len(s.ref.sprPresenceEmpty) {
		s.ref.sprPresenceEmpty[idx] = v
		return nil
	}
	return errors.New("index out of bounds")
}

// getBgrBufferEmpty is the generated getter for the bgrBufferEmpty.
func (s *CollisionsUnitReflect) getBgrBufferEmpty() []uint8 {
	return s.ref.bgrBufferEmpty
}

// setBgrBufferEmpty is the generated setter for the bgrBufferEmpty field.
func (s *CollisionsUnitReflect) setBgrBufferEmpty(v []uint8) error {
	copy(s.ref.bgrBufferEmpty, v)
	return nil
}

// getBgrBufferEmptyEntry is the generated indexed getter for the bgrBufferEmpty.
func (s *CollisionsUnitReflect) getBgrBufferEmptyEntry(idx int) (uint8, error) {
	if idx >= 0 && idx < len(s.ref.bgrBufferEmpty) {
		return s.ref.bgrBufferEmpty[idx], nil
	}
	return *new(uint8), s.outOfBoundsError
}

// setBgrBufferEmptyEntry is the generated indexed setter for the bgrBufferEmpty.
func (s *CollisionsUnitReflect) setBgrBufferEmptyEntry(idx int, v uint8) error {
	if idx >= 0 && idx < len(s.ref.bgrBufferEmpty) {
		s.ref.bgrBufferEmpty[idx] = v
		return nil
	}
	return errors.New("index out of bounds")
}
