package mos6569

// Code generated by symphony-generator. DO NOT EDIT.

import (
	"errors"
	"github.com/markel1974/c64emu/src/references"
)

const (
	reflectLineWidthRGBAId  = "lineWidthRGBA"
	reflectLineOffsetRGBAId = "lineOffsetRGBA"
)

type RasterBeamReflect struct {
	ref              *RasterBeam
	outOfBoundsError error
	readOnlyError    error
}

func NewRasterBeamReflect(r *RasterBeam, factory references.IComponentFactory, parent references.IComponent, identifier string, instance int, hardwareId string) *RasterBeamReflect {
	reflector := &RasterBeamReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.BaseComponent.Register(factory, parent, identifier, instance, r, hardwareId)
	r.PropertyAdd(reflectLineWidthRGBAId, "LineWidthRGBA", false, reflector.getLineWidthRGBA, reflector.setLineWidthRGBA)

	r.PropertyAdd(reflectLineOffsetRGBAId, "LineOffsetRGBA", false, reflector.getLineOffsetRGBA, reflector.setLineOffsetRGBA)

	_ = r.CommandAdd("Draw", "Draw(offset, color) - Draw updates the internal scanline buffer at the computed location with the specified color value.", r.Draw)
	_ = r.CommandAdd("Draw8", "Draw8(offset, color) - Draw8 writes an 8-pixel multicolor value to the internal scanline buffer at the specified offset using the given color.", r.Draw8)
	_ = r.CommandAdd("Commit", "Commit() - Commit transfers the completed scanline from the internal buffer to the final display buffer.  This should be called once at the very end of a scanline's rendering cycle.", r.Commit)
	_ = r.CommandAdd("Emulate", "Emulate() - ", r.Emulate)
	_ = r.CommandAdd("Reset", "Reset() - ", r.Reset)
	_ = r.CommandAdd("ResetLineOffset", "ResetLineOffset() - ResetLineOffset resets the line offset to 0, typically used to prepare for a new rendering cycle or frame.", r.ResetLineOffset)
	_ = r.CommandAdd("DrawStandard", "DrawStandard(offset, a, b, data) - DrawStandard renders 8 pixels in standard mode into the internal scanline buffer.", r.DrawStandard)
	_ = r.CommandAdd("DrawMultiColor", "DrawMultiColor(offset, a, b, c, d, data) - DrawMultiColor renders 8 pixels using a multicolor mode into the internal scanline buffer.", r.DrawMultiColor)

	return reflector
}

// getLineWidthRGBA is the generated getter for the lineWidthRGBA.
func (s *RasterBeamReflect) getLineWidthRGBA() int {
	return s.ref.lineWidthRGBA
}

// setLineWidthRGBA is the generated setter for the lineWidthRGBA field.
func (s *RasterBeamReflect) setLineWidthRGBA(v int) error {
	s.ref.lineWidthRGBA = v
	return nil
}

// getLineOffsetRGBA is the generated getter for the lineOffsetRGBA.
func (s *RasterBeamReflect) getLineOffsetRGBA() int {
	return s.ref.lineOffsetRGBA
}

// setLineOffsetRGBA is the generated setter for the lineOffsetRGBA field.
func (s *RasterBeamReflect) setLineOffsetRGBA(v int) error {
	s.ref.lineOffsetRGBA = v
	return nil
}
