package mos6569

// Code generated by symphony-generator. DO NOT EDIT.

import (
	"errors"
	"github.com/markel1974/c64emu/src/references"
)

const (
	reflectVaBaseId         = "vaBase"
	reflectCiaVaBaseId      = "ciaVaBase"
	reflectMatrixBaseId     = "matrixBase"
	reflectCharBaseId       = "charBase"
	reflectBitmapBaseId     = "bitmapBase"
	reflectLastByteId       = "lastByte"
	reflectRefreshCounterId = "refreshCounter"
)

type MemoryUnitReflect struct {
	ref              *MemoryUnit
	outOfBoundsError error
	readOnlyError    error
}

func NewMemoryUnitReflect(r *MemoryUnit, factory references.IComponentFactory, parent references.IComponent, identifier string, instance int, hardwareId string) *MemoryUnitReflect {
	reflector := &MemoryUnitReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.BaseComponent.Register(factory, parent, identifier, instance, r, hardwareId)
	r.PropertyAdd(reflectVaBaseId, "vaBase", false, reflector.getVaBase, reflector.setVaBase)

	r.PropertyAdd(reflectCiaVaBaseId, "CIA VA14/15 video base", false, reflector.getCiaVaBase, reflector.setCiaVaBase)

	r.PropertyAdd(reflectMatrixBaseId, "Video matrix base", false, reflector.getMatrixBase, reflector.setMatrixBase)

	r.PropertyAdd(reflectCharBaseId, "Character generator base", false, reflector.getCharBase, reflector.setCharBase)

	r.PropertyAdd(reflectBitmapBaseId, "Bitmap base", false, reflector.getBitmapBase, reflector.setBitmapBase)

	r.PropertyAdd(reflectLastByteId, "Last byte read by VIC", false, reflector.getLastByte, reflector.setLastByte)

	r.PropertyAdd(reflectRefreshCounterId, "refreshCounter tracks the number of times a refresh operation has been performed.", false, reflector.getRefreshCounter, reflector.setRefreshCounter)

	_ = r.CommandAdd("Emulate", "Emulate() - Emulate performs the core video memory emulation logic associated with the MemoryUnit structure and its components.", r.Emulate)
	_ = r.CommandAdd("SetCIAVABase", "SetCIAVABase(newVA) - SetCIAVABase updates the CIA VA14/15 video base based on the given newVA value and performs a memory pointer update.", r.SetCIAVABase)
	_ = r.CommandAdd("GetVABase", "GetVABase() uint8 - GetVABase retrieves the value of vaBase with the least significant bit forced to 1.", r.GetVABase)
	_ = r.CommandAdd("GetBitmapBase", "GetBitmapBase() uint16 - GetBitmapBase retrieves the base address of the bitmap within the memory structure.", r.GetBitmapBase)
	_ = r.CommandAdd("ReadByte", "ReadByte(addr) uint8 - ReadByte reads a byte of data from the specified memory address and updates the last byte read.", r.ReadByte)
	_ = r.CommandAdd("GetCharBase", "GetCharBase() uint16 - GetCharBase retrieves the base address of the character generator from the memory structure.", r.GetCharBase)
	_ = r.CommandAdd("SetVABase", "SetVABase(data) - SetVABase sets the video address base value and updates memory pointer configurations.", r.SetVABase)
	_ = r.CommandAdd("AccessIdle", "AccessIdle() - AccessIdle performs idle access by reading from the memory address 0x3FFF using the ReadByte method.", r.AccessIdle)
	_ = r.CommandAdd("Reset", "Reset() - Reset restores the MemoryUnit object to its initial state, resetting all memory-related configurations and properties.", r.Reset)
	_ = r.CommandAdd("GetMatrixBase", "GetMatrixBase() uint16 - GetMatrixBase retrieves the base address of the video matrix from the memory structure.", r.GetMatrixBase)
	_ = r.CommandAdd("AccessRefresh", "AccessRefresh() - AccessRefresh performs a DRAM refresh operation by reading from an address constructed from the refresh counter.  Decrements the refresh counter after each operation.", r.AccessRefresh)
	_ = r.CommandAdd("GetLastByte", "GetLastByte() uint8 - GetLastByte retrieves the value of the last byte read by the VIC from memory within the current instance.", r.GetLastByte)
	_ = r.CommandAdd("ResetRefreshCounter", "ResetRefreshCounter() - ResetRefreshCounter resets the refresh counter to its default value of 0xff.", r.ResetRefreshCounter)

	return reflector
}

// getVaBase is the generated getter for the vaBase.
func (s *MemoryUnitReflect) getVaBase() uint8 {
	return s.ref.vaBase
}

// setVaBase is the generated setter for the vaBase field.
func (s *MemoryUnitReflect) setVaBase(v uint8) error {
	s.ref.vaBase = v
	return nil
}

// getCiaVaBase is the generated getter for the ciaVaBase.
func (s *MemoryUnitReflect) getCiaVaBase() uint16 {
	return s.ref.ciaVaBase
}

// setCiaVaBase is the generated setter for the ciaVaBase field.
func (s *MemoryUnitReflect) setCiaVaBase(v uint16) error {
	s.ref.ciaVaBase = v
	return nil
}

// getMatrixBase is the generated getter for the matrixBase.
func (s *MemoryUnitReflect) getMatrixBase() uint16 {
	return s.ref.GetMatrixBase()
}

// setMatrixBase is the generated setter for the matrixBase field.
func (s *MemoryUnitReflect) setMatrixBase(v uint16) error {
	s.ref.matrixBase = v
	return nil
}

// getCharBase is the generated getter for the charBase.
func (s *MemoryUnitReflect) getCharBase() uint16 {
	return s.ref.GetCharBase()
}

// setCharBase is the generated setter for the charBase field.
func (s *MemoryUnitReflect) setCharBase(v uint16) error {
	s.ref.charBase = v
	return nil
}

// getBitmapBase is the generated getter for the bitmapBase.
func (s *MemoryUnitReflect) getBitmapBase() uint16 {
	return s.ref.GetBitmapBase()
}

// setBitmapBase is the generated setter for the bitmapBase field.
func (s *MemoryUnitReflect) setBitmapBase(v uint16) error {
	s.ref.bitmapBase = v
	return nil
}

// getLastByte is the generated getter for the lastByte.
func (s *MemoryUnitReflect) getLastByte() uint8 {
	return s.ref.GetLastByte()
}

// setLastByte is the generated setter for the lastByte field.
func (s *MemoryUnitReflect) setLastByte(v uint8) error {
	s.ref.lastByte = v
	return nil
}

// getRefreshCounter is the generated getter for the refreshCounter.
func (s *MemoryUnitReflect) getRefreshCounter() uint8 {
	return s.ref.refreshCounter
}

// setRefreshCounter is the generated setter for the refreshCounter field.
func (s *MemoryUnitReflect) setRefreshCounter(v uint8) error {
	s.ref.refreshCounter = v
	return nil
}
