package mos6569

// Code generated by symphony-generator. DO NOT EDIT.

import (
	"errors"
	"github.com/markel1974/symphony/src/references"
)

const (
	reflectHorizontalFlipFlopId = "horizontalFlipFlop"
	reflectVerticalFlipFlopId   = "verticalFlipFlop"
	reflectLeftId               = "left"
	reflectMidLeftId            = "midLeft"
	reflectCenterId             = "center"
	reflectMidRightId           = "midRight"
	reflectRightId              = "right"
	reflectSequencerStateId     = "sequencerState"
	reflectColumnSelId          = "columnSel"
	reflectDyTopId              = "dyTop"
	reflectDyBottomId           = "dyBottom"
	reflectEcId                 = "ec"
	reflectDenId                = "den"
)

type BordersUnitReflect struct {
	ref              *BordersUnit
	outOfBoundsError error
	readOnlyError    error
}

func NewBordersUnitReflect(r *BordersUnit, factory references.IComponentFactory, parent references.IComponent, identifier string, instance int, hardwareId string) *BordersUnitReflect {
	reflector := &BordersUnitReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.BaseComponent.Register(factory, parent, identifier, instance, r, hardwareId)
	r.PropertyAdd(reflectHorizontalFlipFlopId, "HorizontalFlipFlop", false, reflector.getHorizontalFlipFlop, reflector.setHorizontalFlipFlop)

	r.PropertyAdd(reflectVerticalFlipFlopId, "VerticalFlipFlop", false, reflector.getVerticalFlipFlop, reflector.setVerticalFlipFlop)

	r.PropertyAdd(reflectLeftId, "Left", false, reflector.getLeft, reflector.setLeft)

	_ = r.CommandAdd("getLeftEntry", "Left", reflector.getLeftEntry)
	_ = r.CommandAdd("setLeftEntry", "Left", reflector.setLeftEntry)

	r.PropertyAdd(reflectMidLeftId, "MidLeft", false, reflector.getMidLeft, reflector.setMidLeft)

	r.PropertyAdd(reflectCenterId, "Center", false, reflector.getCenter, reflector.setCenter)

	_ = r.CommandAdd("getCenterEntry", "Center", reflector.getCenterEntry)
	_ = r.CommandAdd("setCenterEntry", "Center", reflector.setCenterEntry)

	r.PropertyAdd(reflectMidRightId, "MidRight", false, reflector.getMidRight, reflector.setMidRight)

	r.PropertyAdd(reflectRightId, "Right", false, reflector.getRight, reflector.setRight)

	_ = r.CommandAdd("getRightEntry", "Right", reflector.getRightEntry)
	_ = r.CommandAdd("setRightEntry", "Right", reflector.setRightEntry)

	r.PropertyAdd(reflectSequencerStateId, "SequencerState", false, reflector.getSequencerState, reflector.setSequencerState)

	r.PropertyAdd(reflectColumnSelId, "columnSel indicates whether column selection mode is enabled.", false, reflector.getColumnSel, reflector.setColumnSel)

	r.PropertyAdd(reflectDyTopId, "Comparison values for borders logic", false, reflector.getDyTop, reflector.setDyTop)

	r.PropertyAdd(reflectDyBottomId, "Comparison values for borders logic", false, reflector.getDyBottom, reflector.setDyBottom)

	r.PropertyAdd(reflectEcId, "VIC register - border", false, reflector.getEc, reflector.setEc)

	r.PropertyAdd(reflectDenId, "den bit", false, reflector.getDen, reflector.setDen)

	_ = r.CommandAdd("SetColumnSel", "SetColumnSel(columnSel) - SetColumnSel sets the column selection mode to the specified state, enabling or disabling related behaviors.", r.SetColumnSel)
	_ = r.CommandAdd("ColumnInitialize", "ColumnInitialize() - ColumnInitialize resets and updates the sequencerState based on the horizontalFlipFlop value for the left border bit.", r.ColumnInitialize)
	_ = r.CommandAdd("Column40Update", "Column40Update(rasterY) - Column40Update updates the state of the mid-left border column based on the flip-flop and column selection logic.", r.Column40Update)
	_ = r.CommandAdd("ReadEc", "ReadEc() uint8 - ReadEc returns the `ec` field of the BordersUnit structure combined with the binary OR operation to add a `0xf0` bitmask.", r.ReadEc)
	_ = r.CommandAdd("SetDYTop", "SetDYTop(top) - SetDYTop sets the top comparison value for the vertical border logic, used in determining vertical flip-flop behavior.", r.SetDYTop)
	_ = r.CommandAdd("SetDen", "SetDen(den) - SetDen sets the value of the den property in the BordersUnit instance.", r.SetDen)
	_ = r.CommandAdd("GetDen", "GetDen() bool - GetDen returns the value of the den property from the BordersUnit receiver.", r.GetDen)
	_ = r.CommandAdd("Emulate", "Emulate() - Emulate performs the main emulation logic for the BordersUnit instance, processing updates and managing its internal state.", r.Emulate)
	_ = r.CommandAdd("WriteEc", "WriteEc(data) - WriteEc sets the value of the ec field in the BordersUnit object using the provided uint8 data.", r.WriteEc)
	_ = r.CommandAdd("Column38Apply", "Column38Apply() - Column38Apply updates the sequence state for the mid-right border bit, conditionally setting the horizontal flip-flop.", r.Column38Apply)
	_ = r.CommandAdd("Column40Apply", "Column40Apply() - Column40Apply updates the sequencer state for the right border column, adjusting horizontal flip-flop if conditions are met.", r.Column40Apply)
	_ = r.CommandAdd("Draw", "Draw() - Draw executes a sequence of rendering functions based on the current sequencer state of the BordersUnit instance.", r.Draw)
	_ = r.CommandAdd("VerticalFlipFlop", "VerticalFlipFlop() bool - VerticalFlipFlop returns true if the vertical border flip-flop is set; otherwise, it returns false.", r.VerticalFlipFlop)
	_ = r.CommandAdd("Column38Update", "Column38Update(rasterY) - Column38Update updates the sequencer state for column 38 based on the horizontal and vertical flip-flop states.  If column mode is not selected, it updates the vertical flip-flop value and adjusts the horizontal flip-flop accordingly.", r.Column38Update)
	_ = r.CommandAdd("Reset", "Reset() - Reset clears and reinitializes the internal state of the BordersUnit instance, preparing it for further operations.", r.Reset)
	_ = r.CommandAdd("AcquireColor", "AcquireColor(idx) - AcquireColor assigns a color to the specified index in the borders color array using the current execution context.", r.AcquireColor)
	_ = r.CommandAdd("SetDYBottom", "SetDYBottom(bottom) - SetDYBottom sets the bottom comparison value for the vertical border logic to the provided value.", r.SetDYBottom)
	_ = r.CommandAdd("UpdateVerticalFlipFlop", "UpdateVerticalFlipFlop(rasterY) - UpdateVerticalFlipFlop updates the vertical border flip-flop state based on the current raster Y coordinate and control flags.", r.UpdateVerticalFlipFlop)

	return reflector
}

// getHorizontalFlipFlop is the generated getter for the horizontalFlipFlop.
func (s *BordersUnitReflect) getHorizontalFlipFlop() uint8 {
	return s.ref.horizontalFlipFlop
}

// setHorizontalFlipFlop is the generated setter for the horizontalFlipFlop field.
func (s *BordersUnitReflect) setHorizontalFlipFlop(v uint8) error {
	s.ref.horizontalFlipFlop = v
	return nil
}

// getVerticalFlipFlop is the generated getter for the verticalFlipFlop.
func (s *BordersUnitReflect) getVerticalFlipFlop() uint8 {
	return s.ref.verticalFlipFlop
}

// setVerticalFlipFlop is the generated setter for the verticalFlipFlop field.
func (s *BordersUnitReflect) setVerticalFlipFlop(v uint8) error {
	s.ref.verticalFlipFlop = v
	return nil
}

// getLeft is the generated getter for the left.
func (s *BordersUnitReflect) getLeft() []int {
	return s.ref.left
}

// setLeft is the generated setter for the left field.
func (s *BordersUnitReflect) setLeft(v []int) error {
	copy(s.ref.left, v)
	return nil
}

// getLeftEntry is the generated indexed getter for the left.
func (s *BordersUnitReflect) getLeftEntry(idx int) (int, error) {
	if idx >= 0 && idx < len(s.ref.left) {
		return s.ref.left[idx], nil
	}
	return *new(int), s.outOfBoundsError
}

// setLeftEntry is the generated indexed setter for the left.
func (s *BordersUnitReflect) setLeftEntry(idx int, v int) error {
	if idx >= 0 && idx < len(s.ref.left) {
		s.ref.left[idx] = v
		return nil
	}
	return errors.New("index out of bounds")
}

// getMidLeft is the generated getter for the midLeft.
func (s *BordersUnitReflect) getMidLeft() int {
	return s.ref.midLeft
}

// setMidLeft is the generated setter for the midLeft field.
func (s *BordersUnitReflect) setMidLeft(v int) error {
	s.ref.midLeft = v
	return nil
}

// getCenter is the generated getter for the center.
func (s *BordersUnitReflect) getCenter() []int {
	return s.ref.center
}

// setCenter is the generated setter for the center field.
func (s *BordersUnitReflect) setCenter(v []int) error {
	copy(s.ref.center, v)
	return nil
}

// getCenterEntry is the generated indexed getter for the center.
func (s *BordersUnitReflect) getCenterEntry(idx int) (int, error) {
	if idx >= 0 && idx < len(s.ref.center) {
		return s.ref.center[idx], nil
	}
	return *new(int), s.outOfBoundsError
}

// setCenterEntry is the generated indexed setter for the center.
func (s *BordersUnitReflect) setCenterEntry(idx int, v int) error {
	if idx >= 0 && idx < len(s.ref.center) {
		s.ref.center[idx] = v
		return nil
	}
	return errors.New("index out of bounds")
}

// getMidRight is the generated getter for the midRight.
func (s *BordersUnitReflect) getMidRight() int {
	return s.ref.midRight
}

// setMidRight is the generated setter for the midRight field.
func (s *BordersUnitReflect) setMidRight(v int) error {
	s.ref.midRight = v
	return nil
}

// getRight is the generated getter for the right.
func (s *BordersUnitReflect) getRight() []int {
	return s.ref.right
}

// setRight is the generated setter for the right field.
func (s *BordersUnitReflect) setRight(v []int) error {
	copy(s.ref.right, v)
	return nil
}

// getRightEntry is the generated indexed getter for the right.
func (s *BordersUnitReflect) getRightEntry(idx int) (int, error) {
	if idx >= 0 && idx < len(s.ref.right) {
		return s.ref.right[idx], nil
	}
	return *new(int), s.outOfBoundsError
}

// setRightEntry is the generated indexed setter for the right.
func (s *BordersUnitReflect) setRightEntry(idx int, v int) error {
	if idx >= 0 && idx < len(s.ref.right) {
		s.ref.right[idx] = v
		return nil
	}
	return errors.New("index out of bounds")
}

// getSequencerState is the generated getter for the sequencerState.
func (s *BordersUnitReflect) getSequencerState() uint8 {
	return s.ref.sequencerState
}

// setSequencerState is the generated setter for the sequencerState field.
func (s *BordersUnitReflect) setSequencerState(v uint8) error {
	s.ref.sequencerState = v
	return nil
}

// getColumnSel is the generated getter for the columnSel.
func (s *BordersUnitReflect) getColumnSel() bool {
	return s.ref.columnSel
}

// setColumnSel is the generated setter for the columnSel field.
func (s *BordersUnitReflect) setColumnSel(v bool) error {
	s.ref.SetColumnSel(v)
	return nil
}

// getDyTop is the generated getter for the dyTop.
func (s *BordersUnitReflect) getDyTop() uint16 {
	return s.ref.dyTop
}

// setDyTop is the generated setter for the dyTop field.
func (s *BordersUnitReflect) setDyTop(v uint16) error {
	s.ref.dyTop = v
	return nil
}

// getDyBottom is the generated getter for the dyBottom.
func (s *BordersUnitReflect) getDyBottom() uint16 {
	return s.ref.dyBottom
}

// setDyBottom is the generated setter for the dyBottom field.
func (s *BordersUnitReflect) setDyBottom(v uint16) error {
	s.ref.dyBottom = v
	return nil
}

// getEc is the generated getter for the ec.
func (s *BordersUnitReflect) getEc() uint8 {
	return s.ref.ec
}

// setEc is the generated setter for the ec field.
func (s *BordersUnitReflect) setEc(v uint8) error {
	s.ref.ec = v
	return nil
}

// getDen is the generated getter for the den.
func (s *BordersUnitReflect) getDen() bool {
	return s.ref.GetDen()
}

// setDen is the generated setter for the den field.
func (s *BordersUnitReflect) setDen(v bool) error {
	s.ref.SetDen(v)
	return nil
}
