package mos6569

// Code generated by symphony-generator. DO NOT EDIT.

import (
	"errors"
	"github.com/markel1974/c64emu/src/references"
)

const (
	reflectGfxDataId               = "gfxData"
	reflectColorDataId             = "colorData"
	reflectCharDataId              = "charData"
	reflectCharDataLatchId         = "charDataLatch"
	reflectEcmBackgroundColorId    = "ecmBackgroundColor"
	reflectEcmForegroundColorId    = "ecmForegroundColor"
	reflectBaseOffsetId            = "baseOffset"
	reflectLineIndexId             = "lineIndex"
	reflectVideoMatrixId           = "videoMatrix"
	reflectColorLineId             = "colorLine"
	reflectRowCounterId            = "rowCounter"
	reflectVideoCounterId          = "videoCounter"
	reflectVideoCounterLatchId     = "videoCounterLatch"
	reflectDisplayAccessId         = "displayAccess"
	reflectTextBufferId            = "textBuffer"
	reflectXScrollId               = "xScroll"
	reflectYScrollId               = "yScroll"
	reflectDisplayModeId           = "displayMode"
	reflectBmmId                   = "bmm"
	reflectEcmId                   = "ecm"
	reflectB0cId                   = "b0c"
	reflectB1cId                   = "b1c"
	reflectB2cId                   = "b2c"
	reflectB3cId                   = "b3c"
	reflectBadLineEnablerId        = "badLineEnabler"
	reflectBadLineId               = "badLine"
	reflectSequencerFirstDmaLineId = "sequencerFirstDmaLine"
	reflectSequencerLastDmaLineId  = "sequencerLastDmaLine"
)

type GraphicsUnitReflect struct {
	ref              *GraphicsUnit
	outOfBoundsError error
	readOnlyError    error
}

func NewGraphicsUnitReflect(r *GraphicsUnit, factory references.IComponentFactory, parent references.IComponent, identifier string, instance int, hardwareId string) *GraphicsUnitReflect {
	reflector := &GraphicsUnitReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.BaseComponent.Register(factory, parent, identifier, instance, r, hardwareId)
	r.PropertyAdd(reflectGfxDataId, "GfxData", false, reflector.getGfxData, reflector.setGfxData)

	r.PropertyAdd(reflectColorDataId, "ColorData", false, reflector.getColorData, reflector.setColorData)

	r.PropertyAdd(reflectCharDataId, "CharData", false, reflector.getCharData, reflector.setCharData)

	r.PropertyAdd(reflectCharDataLatchId, "CharDataLatch", false, reflector.getCharDataLatch, reflector.setCharDataLatch)

	r.PropertyAdd(reflectEcmBackgroundColorId, "EcmBackgroundColor", false, reflector.getEcmBackgroundColor, reflector.setEcmBackgroundColor)

	r.PropertyAdd(reflectEcmForegroundColorId, "EcmForegroundColor", false, reflector.getEcmForegroundColor, reflector.setEcmForegroundColor)

	r.PropertyAdd(reflectBaseOffsetId, "Offset from bitmap sprPresence", false, reflector.getBaseOffset, reflector.setBaseOffset)

	r.PropertyAdd(reflectLineIndexId, "Index in video matrix / color line", false, reflector.getLineIndex, reflector.setLineIndex)

	r.PropertyAdd(reflectVideoMatrixId, "Video matrix sprPresence", false, reflector.getVideoMatrix, reflector.setVideoMatrix)

	_ = r.CommandAdd("getVideoMatrixEntry", "Video matrix sprPresence", reflector.getVideoMatrixEntry)
	_ = r.CommandAdd("setVideoMatrixEntry", "Video matrix sprPresence", reflector.setVideoMatrixEntry)

	r.PropertyAdd(reflectColorLineId, "Color line sprPresence", false, reflector.getColorLine, reflector.setColorLine)

	_ = r.CommandAdd("getColorLineEntry", "Color line sprPresence", reflector.getColorLineEntry)
	_ = r.CommandAdd("setColorLineEntry", "Color line sprPresence", reflector.setColorLineEntry)

	r.PropertyAdd(reflectRowCounterId, "Row counter", false, reflector.getRowCounter, reflector.setRowCounter)

	r.PropertyAdd(reflectVideoCounterId, "Video counter", false, reflector.getVideoCounter, reflector.setVideoCounter)

	r.PropertyAdd(reflectVideoCounterLatchId, "Video counter base", false, reflector.getVideoCounterLatch, reflector.setVideoCounterLatch)

	r.PropertyAdd(reflectDisplayAccessId, "Display state", false, reflector.getDisplayAccess, reflector.setDisplayAccess)

	r.PropertyAdd(reflectTextBufferId, "TextBuffer", false, reflector.getTextBuffer, reflector.setTextBuffer)

	_ = r.CommandAdd("getTextBufferEntry", "TextBuffer", reflector.getTextBufferEntry)
	_ = r.CommandAdd("setTextBufferEntry", "TextBuffer", reflector.setTextBufferEntry)

	r.PropertyAdd(reflectXScrollId, "X scroll value", false, reflector.getXScroll, reflector.setXScroll)

	r.PropertyAdd(reflectYScrollId, "Y scroll value", false, reflector.getYScroll, reflector.setYScroll)

	r.PropertyAdd(reflectDisplayModeId, "Index of current display mode", false, reflector.getDisplayMode, reflector.setDisplayMode)

	r.PropertyAdd(reflectBmmId, "Bmm", false, reflector.getBmm, reflector.setBmm)

	r.PropertyAdd(reflectEcmId, "Ecm", false, reflector.getEcm, reflector.setEcm)

	r.PropertyAdd(reflectB0cId, "VIC register - bgrState", false, reflector.getB0c, reflector.setB0c)

	r.PropertyAdd(reflectB1cId, "VIC register - bgrState", false, reflector.getB1c, reflector.setB1c)

	r.PropertyAdd(reflectB2cId, "VIC register - bgrState", false, reflector.getB2c, reflector.setB2c)

	r.PropertyAdd(reflectB3cId, "VIC register - bgrState", false, reflector.getB3c, reflector.setB3c)

	r.PropertyAdd(reflectBadLineEnablerId, "Bad Lines enabled for this frame", false, reflector.getBadLineEnabler, reflector.setBadLineEnabler)

	r.PropertyAdd(reflectBadLineId, "Current line is bad line", false, reflector.getBadLine, reflector.setBadLine)

	r.PropertyAdd(reflectSequencerFirstDmaLineId, "SequencerFirstDmaLine", false, reflector.getSequencerFirstDmaLine, reflector.setSequencerFirstDmaLine)

	r.PropertyAdd(reflectSequencerLastDmaLineId, "SequencerLastDmaLine", false, reflector.getSequencerLastDmaLine, reflector.setSequencerLastDmaLine)

	_ = r.CommandAdd("BadLineVerify", "BadLineVerify(rasterY, denBit) - BadLineVerify updates the bad line condition based on the current raster position, DEN bit, and YSCROLL value.  The bad line condition occurs when specific raster and scroll conditions are met, enabling certain VIC behavior.  Bad Line Condition is given at any arbitrary clock cycle, if at the  negative edge of ø0 at the beginning of the cycle RASTER >= $30 and RASTER <= $f7  and the lower three bits of RASTER are equal to YSCROLL,  and if the DEN bit has been set for at least one cycle somewhere in raster line $30  So clearing the DEN bit will normally prevent Bad Lines", r.BadLineVerify)
	_ = r.CommandAdd("WriteB1c", "WriteB1c(data) - WriteB1c sets the value of the b1c field in the GraphicsUnit struct to the provided uint8 data.", r.WriteB1c)
	_ = r.CommandAdd("UpdateVideoCounter", "UpdateVideoCounter() - UpdateVideoCounter updates the video counter to match the current video counter latch value.", r.UpdateVideoCounter)
	_ = r.CommandAdd("ResetOffset", "ResetOffset() - ResetOffset resets the base offset of the GraphicsUnit to its default value of 0.", r.ResetOffset)
	_ = r.CommandAdd("ReadB2c", "ReadB2c() uint8 - ReadB2c retrieves the value of the b2c property with a bitwise OR operation applied, returning uint8 result.", r.ReadB2c)
	_ = r.CommandAdd("BadLine", "BadLine() bool - BadLine checks if the bgrState unit is in a bad line state and returns true if it is, otherwise false.", r.BadLine)
	_ = r.CommandAdd("Reset", "Reset() - Reset reinitializes the GraphicsUnit instance to its default state, clearing any temporary data and resetting counters.", r.Reset)
	_ = r.CommandAdd("SetYScroll", "SetYScroll(yScroll) - SetYScroll sets the vertical scroll offset for the bgrState rendering system to the specified value.", r.SetYScroll)
	_ = r.CommandAdd("FetchMemory", "FetchMemory(rasterY) - FetchMemory retrieves memory for a given raster line (rasterY) using the display access method.", r.FetchMemory)
	_ = r.CommandAdd("ReadB3c", "ReadB3c() uint8 - ReadB3c reads the b3c property of the GraphicsUnit receiver and applies a bitwise OR operation with the value 0xf0.", r.ReadB3c)
	_ = r.CommandAdd("SetXScroll", "SetXScroll(xScroll) - SetXScroll sets the horizontal scroll offset for the bgrState rendering system to the specified value.", r.SetXScroll)
	_ = r.CommandAdd("FetchDataFake", "FetchDataFake() - FetchDataFake fills the video matrix with fake data when AEC is high, simulating CPU access to the address bus.", r.FetchDataFake)
	_ = r.CommandAdd("ReadB0c", "ReadB0c() uint8 - ReadB0c returns the value of b0c with the high nibble set to 1 (binary 1111), effectively OR-ing the value with 0xf0.", r.ReadB0c)
	_ = r.CommandAdd("WriteB2c", "WriteB2c(data) - WriteB2c sets the value of the b2c field with the provided data parameter.", r.WriteB2c)
	_ = r.CommandAdd("WriteB3c", "WriteB3c(data) - WriteB3c sets the b3c property of the GraphicsUnit object to the given data value.", r.WriteB3c)
	_ = r.CommandAdd("SetDisplayMode", "SetDisplayMode(displayMode) - SetDisplayMode sets the current graphical display mode for the GraphicsUnit instance to the specified integer value.", r.SetDisplayMode)
	_ = r.CommandAdd("WriteB0c", "WriteB0c(data) - WriteB0c sets the value of the b0c field in the GraphicsUnit instance to the specified data value.", r.WriteB0c)
	_ = r.CommandAdd("ResetRowCounterIfBadLine", "ResetRowCounterIfBadLine() - ResetRowCounterIfBadLine resets the row counter (RC) to 0 if the badLine in the core is true.", r.ResetRowCounterIfBadLine)
	_ = r.CommandAdd("FetchColor", "FetchColor(base) - FetchColor reads color data from color RAM for the current video address and stores it in the active color line buffer.", r.FetchColor)
	_ = r.CommandAdd("GetText", "GetText() []byte - GetText retrieves the text buffer content from the GraphicsUnit instance as a slice of bytes.", r.GetText)
	_ = r.CommandAdd("DrawBackground", "DrawBackground() - DrawBackground renders the background using the current display mode  and updates the bgrState offset and collision state.", r.DrawBackground)
	_ = r.CommandAdd("ResetLineIndex", "ResetLineIndex() - ResetLineIndex resets the line index to zero. This happens at the beginning of each scanline.", r.ResetLineIndex)
	_ = r.CommandAdd("FetchColorFake", "FetchColorFake() - FetchColorFake fills the color line buffer with a fake data value when AEC is high and CPU has address bus access.", r.FetchColorFake)
	_ = r.CommandAdd("SetEcm", "SetEcm(ecm) - SetEcm sets the ECM (Error Correction Mode) state for the GraphicsUnit instance.", r.SetEcm)
	_ = r.CommandAdd("CommitCharData", "CommitCharData() - CommitCharData processes the character data latch and updates the ECM background color based on bits 7 and 6 of the latch.", r.CommitCharData)
	_ = r.CommandAdd("DrawForeground", "DrawForeground() - DrawForeground renders the foreground bgrState based on the current display mode and x-scroll offset.  It also increments the offset and updates the collisions.", r.DrawForeground)
	_ = r.CommandAdd("GetXScroll", "GetXScroll() uint16 - GetXScroll retrieves the horizontal scroll offset of the bgrState rendering system.  Returns the current value of `xScroll`.", r.GetXScroll)
	_ = r.CommandAdd("GetYScroll", "GetYScroll() uint16 - GetYScroll retrieves the vertical scroll offset of the bgrState rendering system.  Returns the current value of `yScroll`.", r.GetYScroll)
	_ = r.CommandAdd("ResetVideoCounterLatch", "ResetVideoCounterLatch() - ResetVideoCounterLatch resets the video counter latch to zero.  This happens at the start of each frame.", r.ResetVideoCounterLatch)
	_ = r.CommandAdd("FetchData", "FetchData(base) - FetchData reads a character code from the video matrix at a calculated address based on videoCounter and base offset.", r.FetchData)
	_ = r.CommandAdd("SetBmm", "SetBmm(bmm) - SetBmm sets the bmm property of the GraphicsUnit object to the specified boolean value.", r.SetBmm)
	_ = r.CommandAdd("TryAcquireDisplayAccessOnScanlineEnd", "TryAcquireDisplayAccessOnScanlineEnd() - TryAcquireDisplayAccessOnScanlineEnd updates the display access state and row counter based on the current conditions and row limit.  This function manages the timing of when the display access is granted to the CPU and when the row counter is incremented.  It's called at the *end* of each scanline.", r.TryAcquireDisplayAccessOnScanlineEnd)
	_ = r.CommandAdd("Emulate", "Emulate() - Emulate executes the main bgrState rendering loop, processing video memory, updating counters, and rendering components.", r.Emulate)
	_ = r.CommandAdd("ReadB1c", "ReadB1c() uint8 - ReadB1c retrieves the `b1c` value from the GraphicsUnit struct, applies a bitwise OR with 0xf0, and returns the result.", r.ReadB1c)
	_ = r.CommandAdd("PrintText", "PrintText() - PrintText outputs the contents of the textBuffer in a formatted manner, wrapping lines at every 40 characters.  This is a helper function for debugging.", r.PrintText)
	_ = r.CommandAdd("AcquireDisplayAccessIfBadLine", "AcquireDisplayAccessIfBadLine() - AcquireDisplayAccessIfBadLine sets the displayAccess flag to true if the badLine flag in the core is active.  This gives the CPU access to video memory during 'bad lines'.", r.AcquireDisplayAccessIfBadLine)

	return reflector
}

// getGfxData is the generated getter for the gfxData.
func (s *GraphicsUnitReflect) getGfxData() uint8 {
	return s.ref.gfxData
}

// setGfxData is the generated setter for the gfxData field.
func (s *GraphicsUnitReflect) setGfxData(v uint8) error {
	s.ref.gfxData = v
	return nil
}

// getColorData is the generated getter for the colorData.
func (s *GraphicsUnitReflect) getColorData() uint8 {
	return s.ref.colorData
}

// setColorData is the generated setter for the colorData field.
func (s *GraphicsUnitReflect) setColorData(v uint8) error {
	s.ref.setColorData(v)
	return nil
}

// getCharData is the generated getter for the charData.
func (s *GraphicsUnitReflect) getCharData() uint8 {
	return s.ref.charData
}

// setCharData is the generated setter for the charData field.
func (s *GraphicsUnitReflect) setCharData(v uint8) error {
	s.ref.setCharData(v)
	return nil
}

// getCharDataLatch is the generated getter for the charDataLatch.
func (s *GraphicsUnitReflect) getCharDataLatch() uint8 {
	return s.ref.charDataLatch
}

// setCharDataLatch is the generated setter for the charDataLatch field.
func (s *GraphicsUnitReflect) setCharDataLatch(v uint8) error {
	s.ref.charDataLatch = v
	return nil
}

// getEcmBackgroundColor is the generated getter for the ecmBackgroundColor.
func (s *GraphicsUnitReflect) getEcmBackgroundColor() uint8 {
	return s.ref.ecmBackgroundColor
}

// setEcmBackgroundColor is the generated setter for the ecmBackgroundColor field.
func (s *GraphicsUnitReflect) setEcmBackgroundColor(v uint8) error {
	s.ref.ecmBackgroundColor = v
	return nil
}

// getEcmForegroundColor is the generated getter for the ecmForegroundColor.
func (s *GraphicsUnitReflect) getEcmForegroundColor() uint8 {
	return s.ref.ecmForegroundColor
}

// setEcmForegroundColor is the generated setter for the ecmForegroundColor field.
func (s *GraphicsUnitReflect) setEcmForegroundColor(v uint8) error {
	s.ref.ecmForegroundColor = v
	return nil
}

// getBaseOffset is the generated getter for the baseOffset.
func (s *GraphicsUnitReflect) getBaseOffset() int {
	return s.ref.baseOffset
}

// setBaseOffset is the generated setter for the baseOffset field.
func (s *GraphicsUnitReflect) setBaseOffset(v int) error {
	s.ref.baseOffset = v
	return nil
}

// getLineIndex is the generated getter for the lineIndex.
func (s *GraphicsUnitReflect) getLineIndex() int {
	return s.ref.lineIndex
}

// setLineIndex is the generated setter for the lineIndex field.
func (s *GraphicsUnitReflect) setLineIndex(v int) error {
	s.ref.lineIndex = v
	return nil
}

// getVideoMatrix is the generated getter for the videoMatrix.
func (s *GraphicsUnitReflect) getVideoMatrix() []uint8 {
	return s.ref.videoMatrix
}

// setVideoMatrix is the generated setter for the videoMatrix field.
func (s *GraphicsUnitReflect) setVideoMatrix(v []uint8) error {
	copy(s.ref.videoMatrix, v)
	return nil
}

// getVideoMatrixEntry is the generated indexed getter for the videoMatrix.
func (s *GraphicsUnitReflect) getVideoMatrixEntry(idx int) (uint8, error) {
	if idx >= 0 && idx < len(s.ref.videoMatrix) {
		return s.ref.videoMatrix[idx], nil
	}
	return *new(uint8), s.outOfBoundsError
}

// setVideoMatrixEntry is the generated indexed setter for the videoMatrix.
func (s *GraphicsUnitReflect) setVideoMatrixEntry(idx int, v uint8) error {
	if idx >= 0 && idx < len(s.ref.videoMatrix) {
		s.ref.videoMatrix[idx] = v
		return nil
	}
	return errors.New("index out of bounds")
}

// getColorLine is the generated getter for the colorLine.
func (s *GraphicsUnitReflect) getColorLine() []uint8 {
	return s.ref.colorLine
}

// setColorLine is the generated setter for the colorLine field.
func (s *GraphicsUnitReflect) setColorLine(v []uint8) error {
	copy(s.ref.colorLine, v)
	return nil
}

// getColorLineEntry is the generated indexed getter for the colorLine.
func (s *GraphicsUnitReflect) getColorLineEntry(idx int) (uint8, error) {
	if idx >= 0 && idx < len(s.ref.colorLine) {
		return s.ref.colorLine[idx], nil
	}
	return *new(uint8), s.outOfBoundsError
}

// setColorLineEntry is the generated indexed setter for the colorLine.
func (s *GraphicsUnitReflect) setColorLineEntry(idx int, v uint8) error {
	if idx >= 0 && idx < len(s.ref.colorLine) {
		s.ref.colorLine[idx] = v
		return nil
	}
	return errors.New("index out of bounds")
}

// getRowCounter is the generated getter for the rowCounter.
func (s *GraphicsUnitReflect) getRowCounter() uint16 {
	return s.ref.rowCounter
}

// setRowCounter is the generated setter for the rowCounter field.
func (s *GraphicsUnitReflect) setRowCounter(v uint16) error {
	s.ref.rowCounter = v
	return nil
}

// getVideoCounter is the generated getter for the videoCounter.
func (s *GraphicsUnitReflect) getVideoCounter() uint16 {
	return s.ref.videoCounter
}

// setVideoCounter is the generated setter for the videoCounter field.
func (s *GraphicsUnitReflect) setVideoCounter(v uint16) error {
	s.ref.videoCounter = v
	return nil
}

// getVideoCounterLatch is the generated getter for the videoCounterLatch.
func (s *GraphicsUnitReflect) getVideoCounterLatch() uint16 {
	return s.ref.videoCounterLatch
}

// setVideoCounterLatch is the generated setter for the videoCounterLatch field.
func (s *GraphicsUnitReflect) setVideoCounterLatch(v uint16) error {
	s.ref.videoCounterLatch = v
	return nil
}

// getDisplayAccess is the generated getter for the displayAccess.
func (s *GraphicsUnitReflect) getDisplayAccess() uint8 {
	return s.ref.displayAccess
}

// setDisplayAccess is the generated setter for the displayAccess field.
func (s *GraphicsUnitReflect) setDisplayAccess(v uint8) error {
	s.ref.displayAccess = v
	return nil
}

// getTextBuffer is the generated getter for the textBuffer.
func (s *GraphicsUnitReflect) getTextBuffer() []byte {
	return s.ref.textBuffer
}

// setTextBuffer is the generated setter for the textBuffer field.
func (s *GraphicsUnitReflect) setTextBuffer(v []byte) error {
	copy(s.ref.textBuffer, v)
	return nil
}

// getTextBufferEntry is the generated indexed getter for the textBuffer.
func (s *GraphicsUnitReflect) getTextBufferEntry(idx int) (byte, error) {
	if idx >= 0 && idx < len(s.ref.textBuffer) {
		return s.ref.textBuffer[idx], nil
	}
	return *new(byte), s.outOfBoundsError
}

// setTextBufferEntry is the generated indexed setter for the textBuffer.
func (s *GraphicsUnitReflect) setTextBufferEntry(idx int, v byte) error {
	if idx >= 0 && idx < len(s.ref.textBuffer) {
		s.ref.textBuffer[idx] = v
		return nil
	}
	return errors.New("index out of bounds")
}

// getXScroll is the generated getter for the xScroll.
func (s *GraphicsUnitReflect) getXScroll() uint16 {
	return s.ref.GetXScroll()
}

// setXScroll is the generated setter for the xScroll field.
func (s *GraphicsUnitReflect) setXScroll(v uint16) error {
	s.ref.SetXScroll(v)
	return nil
}

// getYScroll is the generated getter for the yScroll.
func (s *GraphicsUnitReflect) getYScroll() uint16 {
	return s.ref.GetYScroll()
}

// setYScroll is the generated setter for the yScroll field.
func (s *GraphicsUnitReflect) setYScroll(v uint16) error {
	s.ref.SetYScroll(v)
	return nil
}

// getDisplayMode is the generated getter for the displayMode.
func (s *GraphicsUnitReflect) getDisplayMode() uint8 {
	return s.ref.displayMode
}

// setDisplayMode is the generated setter for the displayMode field.
func (s *GraphicsUnitReflect) setDisplayMode(v uint8) error {
	s.ref.SetDisplayMode(v)
	return nil
}

// getBmm is the generated getter for the bmm.
func (s *GraphicsUnitReflect) getBmm() bool {
	return s.ref.bmm
}

// setBmm is the generated setter for the bmm field.
func (s *GraphicsUnitReflect) setBmm(v bool) error {
	s.ref.SetBmm(v)
	return nil
}

// getEcm is the generated getter for the ecm.
func (s *GraphicsUnitReflect) getEcm() bool {
	return s.ref.ecm
}

// setEcm is the generated setter for the ecm field.
func (s *GraphicsUnitReflect) setEcm(v bool) error {
	s.ref.SetEcm(v)
	return nil
}

// getB0c is the generated getter for the b0c.
func (s *GraphicsUnitReflect) getB0c() uint8 {
	return s.ref.b0c
}

// setB0c is the generated setter for the b0c field.
func (s *GraphicsUnitReflect) setB0c(v uint8) error {
	s.ref.b0c = v
	return nil
}

// getB1c is the generated getter for the b1c.
func (s *GraphicsUnitReflect) getB1c() uint8 {
	return s.ref.b1c
}

// setB1c is the generated setter for the b1c field.
func (s *GraphicsUnitReflect) setB1c(v uint8) error {
	s.ref.b1c = v
	return nil
}

// getB2c is the generated getter for the b2c.
func (s *GraphicsUnitReflect) getB2c() uint8 {
	return s.ref.b2c
}

// setB2c is the generated setter for the b2c field.
func (s *GraphicsUnitReflect) setB2c(v uint8) error {
	s.ref.b2c = v
	return nil
}

// getB3c is the generated getter for the b3c.
func (s *GraphicsUnitReflect) getB3c() uint8 {
	return s.ref.b3c
}

// setB3c is the generated setter for the b3c field.
func (s *GraphicsUnitReflect) setB3c(v uint8) error {
	s.ref.b3c = v
	return nil
}

// getBadLineEnabler is the generated getter for the badLineEnabler.
func (s *GraphicsUnitReflect) getBadLineEnabler() bool {
	return s.ref.badLineEnabler
}

// setBadLineEnabler is the generated setter for the badLineEnabler field.
func (s *GraphicsUnitReflect) setBadLineEnabler(v bool) error {
	s.ref.badLineEnabler = v
	return nil
}

// getBadLine is the generated getter for the badLine.
func (s *GraphicsUnitReflect) getBadLine() bool {
	return s.ref.badLine
}

// setBadLine is the generated setter for the badLine field.
func (s *GraphicsUnitReflect) setBadLine(v bool) error {
	s.ref.badLine = v
	return nil
}

// getSequencerFirstDmaLine is the generated getter for the sequencerFirstDmaLine.
func (s *GraphicsUnitReflect) getSequencerFirstDmaLine() uint16 {
	return s.ref.sequencerFirstDmaLine
}

// setSequencerFirstDmaLine is the generated setter for the sequencerFirstDmaLine field.
func (s *GraphicsUnitReflect) setSequencerFirstDmaLine(v uint16) error {
	s.ref.sequencerFirstDmaLine = v
	return nil
}

// getSequencerLastDmaLine is the generated getter for the sequencerLastDmaLine.
func (s *GraphicsUnitReflect) getSequencerLastDmaLine() uint16 {
	return s.ref.sequencerLastDmaLine
}

// setSequencerLastDmaLine is the generated setter for the sequencerLastDmaLine field.
func (s *GraphicsUnitReflect) setSequencerLastDmaLine(v uint16) error {
	s.ref.sequencerLastDmaLine = v
	return nil
}
