package mos6569

// Code generated by symphony-generator. DO NOT EDIT.

import (
	"errors"
	"github.com/markel1974/c64emu/src/references"
)

const (
	reflectIrqLatchId  = "irqLatch"
	reflectIrqMaskId   = "irqMask"
	reflectIrqRasterId = "irqRaster"
)

type InterruptsReflect struct {
	ref              *Interrupts
	outOfBoundsError error
	readOnlyError    error
}

func NewInterruptsReflect(r *Interrupts, factory references.IComponentFactory, parent references.IComponent, identifier string, instance int, hardwareId string) *InterruptsReflect {
	reflector := &InterruptsReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.BaseComponent.Register(factory, parent, identifier, instance, r, hardwareId)
	r.PropertyAdd(reflectIrqLatchId, "irqLatch holds an 8-bit value that latches the IRQ (Interrupt Request) configuration.", false, reflector.getIrqLatch, reflector.setIrqLatch)

	r.PropertyAdd(reflectIrqMaskId, "irqMask represents an 8-bit mask used for interrupt request (IRQ) management.", false, reflector.getIrqMask, reflector.setIrqMask)

	r.PropertyAdd(reflectIrqRasterId, "Interrupt raster line", false, reflector.getIrqRaster, reflector.setIrqRaster)

	_ = r.CommandAdd("Emit", "Emit(irq) - Emit handles triggering of an interrupt by setting the IRQ latch and activating the IRQ if it matches the mask.", r.Emit)
	_ = r.CommandAdd("WriteLatch", "WriteLatch(data) - WriteLatch updates the IRQ latch by clearing specific bits based on the provided data and verifies IRQ conditions.", r.WriteLatch)
	_ = r.CommandAdd("WriteRasterLow", "WriteRasterLow(rasterY, data) - WriteRasterLow updates the low byte of the IRQ raster line with the given 8-bit data and triggers raster settings.", r.WriteRasterLow)
	_ = r.CommandAdd("Reset", "Reset() - Reset clears the internal state, ensuring all interrupt-related settings are reset to their default values.", r.Reset)
	_ = r.CommandAdd("WriteMask", "WriteMask(data) - WriteMask updates the IRQ mask by applying a bitwise AND operation with the given data and 0xF.  It also invokes irqVerify to manage the interrupt state.", r.WriteMask)
	_ = r.CommandAdd("WriteRasterHigh", "WriteRasterHigh(rasterY, data) - WriteRasterHigh sets the high 8 bits of the IRQ raster line by combining the current high bits with the input data.", r.WriteRasterHigh)
	_ = r.CommandAdd("Emulate", "Emulate() - Emulate processes a single step in the emulation cycle for the interrupt system, managing raster operations and IRQ states.", r.Emulate)
	_ = r.CommandAdd("ReadLatch", "ReadLatch() uint8 - ReadLatch returns the current IRQ latch value combined with a constant offset of 0x70 for additional bits' configuration.", r.ReadLatch)
	_ = r.CommandAdd("VerifyRasterY", "VerifyRasterY(rasterY) - VerifyRasterY checks if the given rasterY line matches the configured irqRaster line and triggers an IRQ if they match.", r.VerifyRasterY)
	_ = r.CommandAdd("ReadMask", "ReadMask() uint8 - ReadMask returns the current interrupt mask with the upper 4 bits set to 1 (0xf0).", r.ReadMask)

	return reflector
}

// getIrqLatch is the generated getter for the irqLatch.
func (s *InterruptsReflect) getIrqLatch() uint8 {
	return s.ref.irqLatch
}

// setIrqLatch is the generated setter for the irqLatch field.
func (s *InterruptsReflect) setIrqLatch(v uint8) error {
	s.ref.irqLatch = v
	return nil
}

// getIrqMask is the generated getter for the irqMask.
func (s *InterruptsReflect) getIrqMask() uint8 {
	return s.ref.irqMask
}

// setIrqMask is the generated setter for the irqMask field.
func (s *InterruptsReflect) setIrqMask(v uint8) error {
	s.ref.irqMask = v
	return nil
}

// getIrqRaster is the generated getter for the irqRaster.
func (s *InterruptsReflect) getIrqRaster() uint16 {
	return s.ref.irqRaster
}

// setIrqRaster is the generated setter for the irqRaster field.
func (s *InterruptsReflect) setIrqRaster(v uint16) error {
	s.ref.irqRaster = v
	return nil
}
