package mos6522

// Code generated by symphony-generator. DO NOT EDIT.

import (
	"errors"
	"github.com/markel1974/c64emu/src/references"
)

const (
	reflectCounterId    = "counter"
	reflectLatchId      = "latch"
	reflectClockPulseId = "clockPulse"
	reflectLoadSignalId = "loadSignal"
	reflectUnderflowId  = "underflow"
)

type TimerReflect struct {
	ref              *Timer
	outOfBoundsError error
	readOnlyError    error
}

func NewTimerReflect(r *Timer, factory references.IComponentFactory, parent references.IComponent, identifier string, instance int, hardwareId string) *TimerReflect {
	reflector := &TimerReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.BaseComponent.Register(factory, parent, identifier, instance, r, hardwareId)
	r.PropertyAdd(reflectCounterId, "counter is a 16-bit register used for counting cycles or steps in the Timer's operation.", false, reflector.getCounter, reflector.setCounter)

	r.PropertyAdd(reflectLatchId, "latch is a 16-bit register used to store a predefined value for reloading the counter during Timer operations.", false, reflector.getLatch, reflector.setLatch)

	r.PropertyAdd(reflectClockPulseId, "clockPulse indicates whether the timer's clock signal is active during the current emulation cycle.", false, reflector.getClockPulse, reflector.setClockPulse)

	r.PropertyAdd(reflectLoadSignalId, "loadSignal indicates a flag to signal reloading the counter from the latch value in the Timer.", false, reflector.getLoadSignal, reflector.setLoadSignal)

	r.PropertyAdd(reflectUnderflowId, "underflow indicates whether the timer has reached zero and triggered an underflow condition during operation.", false, reflector.getUnderflow, reflector.setUnderflow)

	_ = r.CommandAdd("Emulate", "Emulate() - Emulate performs a single emulation cycle for the timer, handling countdown, reload, and underflow detection.", r.Emulate)
	_ = r.CommandAdd("CounterLow", "CounterLow() uint8 - CounterLow returns the lower byte (8 bits) of the 16-bit counter value.", r.CounterLow)
	_ = r.CommandAdd("SetClockPulse", "SetClockPulse(clockPulse) - SetClockPulse updates the clock pulse signal for the current emulation cycle.", r.SetClockPulse)
	_ = r.CommandAdd("Load", "Load() - Load sets the loadSignal flag to true, indicating a request to reload the counter from the latch value.", r.Load)
	_ = r.CommandAdd("SetLatchLow", "SetLatchLow(data) - SetLatchLow sets the low byte of the latch register without altering the high byte.", r.SetLatchLow)
	_ = r.CommandAdd("Underflow", "Underflow() bool - Underflow returns true if the timer has experienced an underflow during the current emulation cycle.", r.Underflow)
	_ = r.CommandAdd("LatchHigh", "LatchHigh() uint8 - LatchHigh returns the high byte (bits 8-15) of the 16-bit latch value as an unsigned 8-bit integer.", r.LatchHigh)
	_ = r.CommandAdd("SetLatchHigh", "SetLatchHigh(data) - SetLatchHigh sets the high byte of the latch value with the provided data, retaining the low byte unchanged.", r.SetLatchHigh)
	_ = r.CommandAdd("Reset", "Reset() - Reset initializes the Timer to its default state, resetting all internal fields to predefined default values.", r.Reset)
	_ = r.CommandAdd("CounterHigh", "CounterHigh() uint8 - CounterHigh returns the high 8 bits of the 16-bit counter value as a uint8.", r.CounterHigh)
	_ = r.CommandAdd("LatchLow", "LatchLow() uint8 - LatchLow returns the low byte of the 16-bit `latch` value of the Timer as an unsigned 8-bit integer.", r.LatchLow)

	return reflector
}

// getCounter is the generated getter for the counter.
func (s *TimerReflect) getCounter() uint16 {
	return s.ref.counter
}

// setCounter is the generated setter for the counter field.
func (s *TimerReflect) setCounter(v uint16) error {
	s.ref.counter = v
	return nil
}

// getLatch is the generated getter for the latch.
func (s *TimerReflect) getLatch() uint16 {
	return s.ref.latch
}

// setLatch is the generated setter for the latch field.
func (s *TimerReflect) setLatch(v uint16) error {
	s.ref.latch = v
	return nil
}

// getClockPulse is the generated getter for the clockPulse.
func (s *TimerReflect) getClockPulse() bool {
	return s.ref.clockPulse
}

// setClockPulse is the generated setter for the clockPulse field.
func (s *TimerReflect) setClockPulse(v bool) error {
	s.ref.SetClockPulse(v)
	return nil
}

// getLoadSignal is the generated getter for the loadSignal.
func (s *TimerReflect) getLoadSignal() bool {
	return s.ref.loadSignal
}

// setLoadSignal is the generated setter for the loadSignal field.
func (s *TimerReflect) setLoadSignal(v bool) error {
	s.ref.loadSignal = v
	return nil
}

// getUnderflow is the generated getter for the underflow.
func (s *TimerReflect) getUnderflow() bool {
	return s.ref.underflow
}

// setUnderflow is the generated setter for the underflow field.
func (s *TimerReflect) setUnderflow(v bool) error {
	s.ref.underflow = v
	return nil
}
