package mos6522

// Code generated by symphony-generator. DO NOT EDIT.

import "errors"

const (
	reflectShiftCounterId = "shiftCounter"
	reflectSrId           = "sr"
)

type ShiftRegisterReflect struct {
	ref              *ShiftRegister
	outOfBoundsError error
	readOnlyError    error
}

func NewShiftRegisterReflect(r *ShiftRegister) *ShiftRegisterReflect {
	reflector := &ShiftRegisterReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.PropertyAdd(reflectShiftCounterId, "shiftCounter tracks the number of shifts performed, resetting after completing an 8-bit operation.", false, reflector.getShiftCounter, reflector.setShiftCounter)

	r.PropertyAdd(reflectSrId, "sr represents the internal 8-bit storage for the shift register operations.", false, reflector.getSr, reflector.setSr)

	_ = r.CommandAdd("Emulate", "Emulate() - Emulate triggers the emulation process for the shift register, updating its internal state as required.", r.Emulate)
	_ = r.CommandAdd("Set", "Set(data) - Set updates the internal shift register with the provided 8-bit data.", r.Set)
	_ = r.CommandAdd("Reset", "Reset() - Reset resets the shift register and shift counter to their initial state (0).", r.Reset)
	_ = r.CommandAdd("Get", "Get() uint8 - Get retrieves the current value stored in the shift register.", r.Get)
	_ = r.CommandAdd("Handle", "Handle(shiftIn) bool - Handle processes a single shift operation in the shift register, either shifting in or out based on isShiftIn flag.  It increments the shift counter and returns true when a full 8-bit operation is completed.", r.Handle)

	return reflector
}

// getShiftCounter is the generated getter for the shiftCounter.
func (s *ShiftRegisterReflect) getShiftCounter() uint8 {
	return s.ref.shiftCounter
}

// setShiftCounter is the generated setter for the shiftCounter field.
func (s *ShiftRegisterReflect) setShiftCounter(v uint8) error {
	s.ref.shiftCounter = v
	return nil
}

// getSr is the generated getter for the sr.
func (s *ShiftRegisterReflect) getSr() uint8 {
	return s.ref.sr
}

// setSr is the generated setter for the sr field.
func (s *ShiftRegisterReflect) setSr(v uint8) error {
	s.ref.sr = v
	return nil
}
