package mos6522

// Code generated by symphony-generator. DO NOT EDIT.

import (
	"errors"
	"github.com/markel1974/c64emu/src/references"
)

const (
	reflectPraId     = "pra"
	reflectDdraId    = "ddra"
	reflectPrbId     = "prb"
	reflectDdrbId    = "ddrb"
	reflectAcrId     = "acr"
	reflectPcrId     = "pcr"
	reflectIfrId     = "ifr"
	reflectIerId     = "ier"
	reflectLastCA1Id = "lastCA1"
	reflectLastCB2Id = "lastCB2"
	reflectLastPB6Id = "lastPB6"
	reflectLastCB1Id = "lastCB1"
)

type VIAReflect struct {
	ref              *VIA
	outOfBoundsError error
	readOnlyError    error
}

func NewVIAReflect(r *VIA, factory references.IComponentFactory, parent references.IComponent, identifier string, instance int, hardwareId string) *VIAReflect {
	reflector := &VIAReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.BaseComponent.Register(factory, parent, identifier, instance, r, hardwareId)
	r.PropertyAdd(reflectPraId, "pra represents the Peripheral Register A (PRA) used to store or output data for port A in the VIA.", false, reflector.getPra, reflector.setPra)

	r.PropertyAdd(reflectDdraId, "ddra represents the Data Direction Register A in the VIA, used to configure the direction of port A pins as input or output.", false, reflector.getDdra, reflector.setDdra)

	r.PropertyAdd(reflectPrbId, "prb represents the Peripheral Register B (PRB) used to store or output data for port B in the VIA.", false, reflector.getPrb, reflector.setPrb)

	r.PropertyAdd(reflectDdrbId, "ddrb represents the Data Direction Register B, controlling the input/output configuration of the VIA Port B pins.", false, reflector.getDdrb, reflector.setDdrb)

	r.PropertyAdd(reflectAcrId, "acr represents the Auxiliary Control Register used for configuring VIA operating modes and functionalities.", false, reflector.getAcr, reflector.setAcr)

	r.PropertyAdd(reflectPcrId, "pcr represents the Peripheral Control Register for managing control pin configurations and interrupt settings.", false, reflector.getPcr, reflector.setPcr)

	r.PropertyAdd(reflectIfrId, "ifr represents the interrupt flag register, which indicates pending interrupts for the VIA component.", false, reflector.getIfr, reflector.setIfr)

	r.PropertyAdd(reflectIerId, "ier represents the Interrupt Enable Register, used to enable or disable specific interrupt sources in the VIA.", false, reflector.getIer, reflector.setIer)

	r.PropertyAdd(reflectLastCA1Id, "lastCA1 indicates the last observed state of the CA1 control pin for edge detection or handshake operations.", false, reflector.getLastCA1, reflector.setLastCA1)

	r.PropertyAdd(reflectLastCB2Id, "lastCB2 tracks the last state of the CB2 pin for edge detection or state comparison purposes.", false, reflector.getLastCB2, reflector.setLastCB2)

	r.PropertyAdd(reflectLastPB6Id, "lastPB6 tracks the previous state of the PB6 control line for edge detection and timer operations.", false, reflector.getLastPB6, reflector.setLastPB6)

	r.PropertyAdd(reflectLastCB1Id, "lastCB1 indicates the previous state of the CB1 control line for edge detection or handshake operations.", false, reflector.getLastCB1, reflector.setLastCB1)

	_ = r.CommandAdd("Reset", "Reset() - Reset initializes all VIA internal registers to their default state of zero.", r.Reset)
	_ = r.CommandAdd("Emulate", "Emulate() - Emulate executes a single emulation cycle for VIA, decrementing timers and handling interrupts based on current settings.  go:nosplit", r.Emulate)
	_ = r.CommandAdd("ReadPRA", "ReadPRA() uint8 - ReadPRA returns the current value of the Peripheral Register A (PRA) from the VIA.", r.ReadPRA)
	_ = r.CommandAdd("ReadPCR", "ReadPCR() uint8 - ReadPCR retrieves the current value of the Peripheral Control Register (PCR) from the VIA.", r.ReadPCR)
	_ = r.CommandAdd("ReadDDRA", "ReadDDRA() uint8 - ReadDDRA returns the current value of the Data Direction Register A (DDRA) of the VIA.", r.ReadDDRA)
	_ = r.CommandAdd("ReadDDRB", "ReadDDRB() uint8 - ReadDDRB returns the current value of the Data Direction Register A (DDRB) of the VIA.", r.ReadDDRB)
	_ = r.CommandAdd("ReadPRB", "ReadPRB() uint8 - ReadPRB returns the current value of the Peripheral Register B (PRB) from the VIA.", r.ReadPRB)
	_ = r.CommandAdd("ReadACR", "ReadACR() uint8 - ReadACR returns the current value of the Auxiliary Control Register (ACR) from the VIA.", r.ReadACR)
	_ = r.CommandAdd("ReadByte", "ReadByte(addr) uint8 - ReadByte reads a byte from the specified VIA register address and returns the corresponding value based on its state.", r.ReadByte)
	_ = r.CommandAdd("WriteByte", "WriteByte(addr, data) - WriteByte writes a byte of data to the specified register address in the VIA and updates the internal state accordingly.", r.WriteByte)

	return reflector
}

// getPra is the generated getter for the pra.
func (s *VIAReflect) getPra() uint8 {
	return s.ref.pra
}

// setPra is the generated setter for the pra field.
func (s *VIAReflect) setPra(v uint8) error {
	s.ref.pra = v
	return nil
}

// getDdra is the generated getter for the ddra.
func (s *VIAReflect) getDdra() uint8 {
	return s.ref.ddra
}

// setDdra is the generated setter for the ddra field.
func (s *VIAReflect) setDdra(v uint8) error {
	s.ref.ddra = v
	return nil
}

// getPrb is the generated getter for the prb.
func (s *VIAReflect) getPrb() uint8 {
	return s.ref.prb
}

// setPrb is the generated setter for the prb field.
func (s *VIAReflect) setPrb(v uint8) error {
	s.ref.prb = v
	return nil
}

// getDdrb is the generated getter for the ddrb.
func (s *VIAReflect) getDdrb() uint8 {
	return s.ref.ddrb
}

// setDdrb is the generated setter for the ddrb field.
func (s *VIAReflect) setDdrb(v uint8) error {
	s.ref.ddrb = v
	return nil
}

// getAcr is the generated getter for the acr.
func (s *VIAReflect) getAcr() uint8 {
	return s.ref.acr
}

// setAcr is the generated setter for the acr field.
func (s *VIAReflect) setAcr(v uint8) error {
	s.ref.acr = v
	return nil
}

// getPcr is the generated getter for the pcr.
func (s *VIAReflect) getPcr() uint8 {
	return s.ref.pcr
}

// setPcr is the generated setter for the pcr field.
func (s *VIAReflect) setPcr(v uint8) error {
	s.ref.pcr = v
	return nil
}

// getIfr is the generated getter for the ifr.
func (s *VIAReflect) getIfr() uint8 {
	return s.ref.ifr
}

// setIfr is the generated setter for the ifr field.
func (s *VIAReflect) setIfr(v uint8) error {
	s.ref.ifr = v
	return nil
}

// getIer is the generated getter for the ier.
func (s *VIAReflect) getIer() uint8 {
	return s.ref.ier
}

// setIer is the generated setter for the ier field.
func (s *VIAReflect) setIer(v uint8) error {
	s.ref.ier = v
	return nil
}

// getLastCA1 is the generated getter for the lastCA1.
func (s *VIAReflect) getLastCA1() bool {
	return s.ref.lastCA1
}

// setLastCA1 is the generated setter for the lastCA1 field.
func (s *VIAReflect) setLastCA1(v bool) error {
	s.ref.lastCA1 = v
	return nil
}

// getLastCB2 is the generated getter for the lastCB2.
func (s *VIAReflect) getLastCB2() bool {
	return s.ref.lastCB2
}

// setLastCB2 is the generated setter for the lastCB2 field.
func (s *VIAReflect) setLastCB2(v bool) error {
	s.ref.lastCB2 = v
	return nil
}

// getLastPB6 is the generated getter for the lastPB6.
func (s *VIAReflect) getLastPB6() bool {
	return s.ref.lastPB6
}

// setLastPB6 is the generated setter for the lastPB6 field.
func (s *VIAReflect) setLastPB6(v bool) error {
	s.ref.lastPB6 = v
	return nil
}

// getLastCB1 is the generated getter for the lastCB1.
func (s *VIAReflect) getLastCB1() bool {
	return s.ref.lastCB1
}

// setLastCB1 is the generated setter for the lastCB1 field.
func (s *VIAReflect) setLastCB1(v bool) error {
	s.ref.lastCB1 = v
	return nil
}
