package mos6522

// Code generated by symphony-generator. DO NOT EDIT.

const (
	shiftCounterId = "shiftCounter"
	srId           = "sr"
)

type ShiftRegisterReflect struct {
	ref *ShiftRegister
}

func NewShiftRegisterReflect(r *ShiftRegister) *ShiftRegisterReflect {
	reflector := &ShiftRegisterReflect{ref: r}
	r.PropertyAdd(shiftCounterId, "shiftCounter tracks the number of shifts performed, resetting after completing an 8-bit operation.", false, reflector.getShiftCounter, reflector.setShiftCounter)
	r.PropertyAdd(srId, "sr represents the internal 8-bit storage for the shift register operations.", false, reflector.getSr, reflector.setSr)
	return reflector
}

// getShiftCounter is the generated getter for the shiftCounter field.
func (s *ShiftRegisterReflect) getShiftCounter() uint8 {
	return s.ref.shiftCounter
}

// setShiftCounter is the generated setter for the shiftCounter field.
func (s *ShiftRegisterReflect) setShiftCounter(v uint8) error {
	s.ref.shiftCounter = v
	return nil
}

// getSr is the generated getter for the sr field.
func (s *ShiftRegisterReflect) getSr() uint8 {
	return s.ref.sr
}

// setSr is the generated setter for the sr field.
func (s *ShiftRegisterReflect) setSr(v uint8) error {
	s.ref.sr = v
	return nil
}
