package mos6522

// Code generated by symphony-generator. DO NOT EDIT.

const (
	counterId    = "counter"
	latchId      = "latch"
	clockPulseId = "clockPulse"
	loadSignalId = "loadSignal"
	underflowId  = "underflow"
)

type TimerReflect struct {
	ref *Timer
}

func NewTimerReflect(r *Timer) *TimerReflect {
	reflector := &TimerReflect{ref: r}
	r.AddProperty(counterId, "counter is a 16-bit register used for counting cycles or steps in the Timer's operation.", false, reflector.getCounter, reflector.setCounter)
	r.AddProperty(latchId, "latch is a 16-bit register used to store a predefined value for reloading the counter during Timer operations.", false, reflector.getLatch, reflector.setLatch)
	r.AddProperty(clockPulseId, "clockPulse indicates whether the timer's clock signal is active during the current emulation cycle.", false, reflector.getClockPulse, reflector.setClockPulse)
	r.AddProperty(loadSignalId, "loadSignal indicates a flag to signal reloading the counter from the latch value in the Timer.", false, reflector.getLoadSignal, reflector.setLoadSignal)
	r.AddProperty(underflowId, "underflow indicates whether the timer has reached zero and triggered an underflow condition during operation.", false, reflector.getUnderflow, reflector.setUnderflow)
	return reflector
}

// getCounter is the generated getter for the counter field.
func (s *TimerReflect) getCounter() uint16 {
	return s.ref.counter
}

// setCounter is the generated setter for the counter field.
func (s *TimerReflect) setCounter(v uint16) error {
	s.ref.counter = v
	return nil
}

// getLatch is the generated getter for the latch field.
func (s *TimerReflect) getLatch() uint16 {
	return s.ref.latch
}

// setLatch is the generated setter for the latch field.
func (s *TimerReflect) setLatch(v uint16) error {
	s.ref.latch = v
	return nil
}

// getClockPulse is the generated getter for the clockPulse field.
func (s *TimerReflect) getClockPulse() bool {
	return s.ref.clockPulse
}

// setClockPulse is the generated setter for the clockPulse field.
func (s *TimerReflect) setClockPulse(v bool) error {
	s.ref.clockPulse = v
	return nil
}

// getLoadSignal is the generated getter for the loadSignal field.
func (s *TimerReflect) getLoadSignal() bool {
	return s.ref.loadSignal
}

// setLoadSignal is the generated setter for the loadSignal field.
func (s *TimerReflect) setLoadSignal(v bool) error {
	s.ref.loadSignal = v
	return nil
}

// getUnderflow is the generated getter for the underflow field.
func (s *TimerReflect) getUnderflow() bool {
	return s.ref.underflow
}

// setUnderflow is the generated setter for the underflow field.
func (s *TimerReflect) setUnderflow(v bool) error {
	s.ref.underflow = v
	return nil
}
