package tetris

import (
	"math/rand"
	"strings"
)

// defaultTetrominoX and defaultTetrominoY define the default starting coordinates for a Tetromino piece.
// TetrominoWidth and TetrominoHeight specify the standard dimensions of a Tetromino piece.
const (
	defaultTetrominoX, defaultTetrominoY = 3, -1
	TetrominoWidth, TetrominoHeight      = 4, 4
)

// srcBlocks holds a predefined set of block patterns represented as strings with a grid layout.
var (
	srcBlocks = []string{
		`
			....
			.GG.
			GG..
			....
		`, `
			....
			.RR.
			..RR
			....
		`, `
			....
			.YY.
			.YY.
			....
		`, `
			....
			....
			CCCC
			....
		`, `
			....
			.M..
			MMM.
			....
		`, `
			....
			.b..
			.bbb
			....
		`, `
			....
			..m.
			mmm.
			....
		`,
	}
)

// blocks holds a preprocessed list of tetromino block shapes generated by initializeBlocks using srcBlocks as input.
var blocks = initializeBlocks(srcBlocks)

// initializeBlocks processes a slice of strings by removing tabs, spaces, and trimming newline characters from each element.
func initializeBlocks(blocks []string) []string {
	var out []string
	for _, block := range blocks {
		block = strings.Replace(block, "\t", "", -1)
		block = strings.Replace(block, " ", "", -1)
		block = strings.Trim(block, "\n")
		out = append(out, block)
	}
	return out
}

// Tetromino represents a geometric shape composed of four connected blocks in a Tetris-like grid system.
type Tetromino struct {
	block string
	x     int
	y     int
}

// NewMino creates a new Tetromino instance with a random block and returns a pointer to it.
func NewMino() *Tetromino {
	return &Tetromino{
		block: blocks[rand.Intn(len(blocks))],
	}
}

// cell retrieves the rune stored at the specified (x, y) position within the Tetromino's block representation.
func (m *Tetromino) cell(x, y int) rune {
	return rune(m.block[x+(TetrominoWidth+1)*y])
}

// setCell updates the rune at the specified (x, y) position in the Tetromino block.
func (m *Tetromino) setCell(x, y int, cell rune) {
	buf := []rune(m.block)
	buf[x+(TetrominoWidth+1)*y] = cell
	m.block = string(buf)
}

// putBottom moves the Tetromino down the board until it conflicts and returns the distance it traveled.
func (m *Tetromino) putBottom(board *Board) int {
	distance := -1
	dstMino := *m
	for !dstMino.conflicts(board) {
		*m = dstMino
		dstMino.forceMoveDown()
		distance++
	}
	if distance < 0 {
		distance = 0
	}
	return distance
}

// forceMoveDown increments the y-coordinate of the Tetromino, forcibly moving it one step down.
func (m *Tetromino) forceMoveDown() {
	m.y++
}

// forceRotateRight rotates the tetromino 90 degrees clockwise, modifying the current cell data to reflect the rotation.
func (m *Tetromino) forceRotateRight() {
	oldMino := *m
	for j := 0; j < TetrominoHeight; j++ {
		for i := 0; i < TetrominoWidth; i++ {
			m.setCell(TetrominoHeight-j-1, i, oldMino.cell(i, j))
		}
	}
}

// forceRotateLeft rotates the tetromino counterclockwise by modifying its internal cell structure.
func (m *Tetromino) forceRotateLeft() {
	oldMino := *m
	for j := 0; j < TetrominoHeight; j++ {
		for i := 0; i < TetrominoWidth; i++ {
			m.setCell(j, TetrominoWidth-i-1, oldMino.cell(i, j))
		}
	}
}

// conflicts checks whether the Tetromino's cells overlap with existing cells or are out of bounds on the given board.
func (m *Tetromino) conflicts(board *Board) bool {
	for _, cell := range m.cells() {
		if cell.conflicts(board) {
			return true
		}
	}
	return false
}

// cells returns a slice of pointers to Cell objects representing all non-empty cells of the Tetromino in its current position.
func (m *Tetromino) cells() []*Cell {
	var cells []*Cell
	for i := 0; i < TetrominoWidth; i++ {
		for j := 0; j < TetrominoHeight; j++ {
			if m.cell(i, j) != '.' {
				cells = append(cells, NewCell(m.x+i, m.y+j, m.cell(i, j)))
			}
		}
	}
	return cells
}

// lines splits the tetromino's block string into a slice of strings, using newline characters as delimiters.
func (m *Tetromino) lines() []string {
	return strings.Split(m.block, "\n")
}
