package mos6510

import "reflect"

var _opContainer = make(map[reflect.Value]string)

var _opReverseContainer = make(map[string]reflect.Value)

func init() {
	addOpId(instOpPHA, "instOpPHA")
	addOpId(instOpPHA1, "instOpPHA1")
	addOpId(instOpPLA, "instOpPLA")
	addOpId(instOpPLA1, "instOpPLA1")
	addOpId(instOpPLA2, "instOpPLA2")
	addOpId(instOpPHP, "instOpPHP")
	addOpId(instOpPHP1, "instOpPHP1")
	addOpId(instOpPLP, "instOpPLP")
	addOpId(instOpPLP1, "instOpPLP1")
	addOpId(instOpPLP2, "instOpPLP2")
	addOpId(instOpNMI, "instOpNMI")
	addOpId(instOpNMI1, "instOpNMI1")
	addOpId(instOpNMI2, "instOpNMI2")
	addOpId(instOpNMI3, "instOpNMI3")
	addOpId(instOpNMI4, "instOpNMI4")
	addOpId(instOpNMI5, "instOpNMI5")
	addOpId(instOpNMI6, "instOpNMI6")
	addOpId(instApZER, "instApZER")
	addOpId(instApZERx, "instApZERx")
	addOpId(instApZERx1, "instApZERx1")
	addOpId(instApZERy, "instApZERy")
	addOpId(instApZERy1, "instApZERy1")
	addOpId(instApABS, "instApABS")
	addOpId(instApABS1, "instApABS1")
	addOpId(instApABSx, "instApABSx")
	addOpId(instApABSx1, "instApABSx1")
	addOpId(instApABSx2, "instApABSx2")
	addOpId(instApABSx3, "instApABSx3")
	addOpId(instApABSy, "instApABSy")
	addOpId(instApABSy1, "instApABSy1")
	addOpId(instApABSy2, "instApABSy2")
	addOpId(instApABSy3, "instApABSy3")
	addOpId(instApINDx, "instApINDx")
	addOpId(instApINDx1, "instApINDx1")
	addOpId(instApINDx2, "instApINDx2")
	addOpId(instApINDx3, "instApINDx3")
	addOpId(instApINDy, "instApINDy")
	addOpId(instApINDy1, "instApINDy1")
	addOpId(instApINDy2, "instApINDy2")
	addOpId(instApINDy3, "instApINDy3")
	addOpId(instApINDy4, "instApINDy4")
	addOpId(instAeABSx, "instAeABSx")
	addOpId(instAeABSx1, "instAeABSx1")
	addOpId(instAeABSx2, "instAeABSx2")
	addOpId(instAeABSy, "instAeABSy")
	addOpId(instAeABSy1, "instAeABSy1")
	addOpId(instAeABSy2, "instAeABSy2")
	addOpId(instAeINDy, "instAeINDy")
	addOpId(instAeINDy1, "instAeINDy1")
	addOpId(instAeINDy2, "instAeINDy2")
	addOpId(instAeINDy3, "instAeINDy3")
	addOpId(instMpZER, "instMpZER")
	addOpId(instMpZERx, "instMpZERx")
	addOpId(instMpZERx1, "instMpZERx1")
	addOpId(instMpABS, "instMpABS")
	addOpId(instMpABS1, "instMpABS1")
	addOpId(instMpABSx, "instMpABSx")
	addOpId(instMpABSx1, "instMpABSx1")
	addOpId(instMpABSx2, "instMpABSx2")
	addOpId(instMpABSx3, "instMpABSx3")
	addOpId(instMpABSy, "instMpABSy")
	addOpId(instMpABSy1, "instMpABSy1")
	addOpId(instMpABSy2, "instMpABSy2")
	addOpId(instMpABSy3, "instMpABSy3")
	addOpId(instMpINDx, "instMpINDx")
	addOpId(instMpINDx1, "instMpINDx1")
	addOpId(instMpINDx2, "instMpINDx2")
	addOpId(instMpINDx3, "instMpINDx3")
	addOpId(instMpINDy, "instMpINDy")
	addOpId(instMpINDy1, "instMpINDy1")
	addOpId(instMpINDy2, "instMpINDy2")
	addOpId(instMpINDy3, "instMpINDy3")
	addOpId(instMpINDy4, "instMpINDy4")
	addOpId(instOpRMW, "instOpRMW")
	addOpId(instOpRMW1, "instOpRMW1")
	addOpId(instOpLDA, "instOpLDA")
	addOpId(instOiLDA, "instOiLDA")
	addOpId(instOpLDX, "instOpLDX")
	addOpId(instOiLDX, "instOiLDX")
	addOpId(instOpLDY, "instOpLDY")
	addOpId(instOiLDY, "instOiLDY")
	addOpId(instOpSTA, "instOpSTA")
	addOpId(instOpSTX, "instOpSTX")
	addOpId(instOpSTY, "instOpSTY")
	addOpId(instOpIRQ, "instOpIRQ")
	addOpId(instOpIRQ1, "instOpIRQ1")
	addOpId(instOpIRQ2, "instOpIRQ2")
	addOpId(instOpIRQ3, "instOpIRQ3")
	addOpId(instOpIRQ4, "instOpIRQ4")
	addOpId(instOpIRQ5, "instOpIRQ5")
	addOpId(instOpIRQ6, "instOpIRQ6")
	addOpId(instOiNOP, "instOiNOP")
	addOpId(instOaNOP, "instOaNOP")
	addOpId(instOpLAX, "instOpLAX")
	addOpId(instOpSAX, "instOpSAX")
	addOpId(instOpSLO, "instOpSLO")
	addOpId(instOpRLA, "instOpRLA")
	addOpId(instOpSRE, "instOpSRE")
	addOpId(instOpRRA, "instOpRRA")
	addOpId(instOpDCP, "instOpDCP")
	addOpId(instOpISB, "instOpISB")
	addOpId(instOiANC, "instOiANC")
	addOpId(instOiASR, "instOiASR")
	addOpId(instOiARR, "instOiARR")
	addOpId(instOiANE, "instOiANE")
	addOpId(instOiLXA, "instOiLXA")
	addOpId(instOiSBX, "instOiSBX")
	addOpId(instOpLAS, "instOpLAS")
	addOpId(instOpSHS, "instOpSHS")
	addOpId(instOpSHY, "instOpSHY")
	addOpId(instOpSHX, "instOpSHX")
	addOpId(instOpSHA, "instOpSHA")
	addOpId(instOpJAM, "instOpJAM")
	addOpId(instOpTAX, "instOpTAX")
	addOpId(instOpTXA, "instOpTXA")
	addOpId(instOpTAY, "instOpTAY")
	addOpId(instOpTYA, "instOpTYA")
	addOpId(instOpTSX, "instOpTSX")
	addOpId(instOpTXS, "instOpTXS")
	addOpId(instOpSEC, "instOpSEC")
	addOpId(instOpCLC, "instOpCLC")
	addOpId(instOpSED, "instOpSED")
	addOpId(instOpCLD, "instOpCLD")
	addOpId(instOpSEI, "instOpSEI")
	addOpId(instOpCLI, "instOpCLI")
	addOpId(instOpCLV, "instOpCLV")
	addOpId(instOpNOP, "instOpNOP")
	addOpId(instOpADC, "instOpADC")
	addOpId(instOiADC, "instOiADC")
	addOpId(instOpSBC, "instOpSBC")
	addOpId(instOiSBC, "instOiSBC")
	addOpId(instOpINX, "instOpINX")
	addOpId(instOpDEX, "instOpDEX")
	addOpId(instOpINY, "instOpINY")
	addOpId(instOpDEY, "instOpDEY")
	addOpId(instOpINC, "instOpINC")
	addOpId(instOpDEC, "instOpDEC")
	addOpId(instOpAND, "instOpAND")
	addOpId(instOiAND, "instOiAND")
	addOpId(instOpORA, "instOpORA")
	addOpId(instOiOPA, "instOiOPA")
	addOpId(instOpEOR, "instOpEOR")
	addOpId(instOiEOR, "instOiEOR")
	addOpId(instOpCMP, "instOpCMP")
	addOpId(instOiCMP, "instOiCMP")
	addOpId(instOpCPX, "instOpCPX")
	addOpId(instOiCPX, "instOiCPX")
	addOpId(instOpCPY, "instOpCPY")
	addOpId(instOiCPY, "instOiCPY")
	addOpId(instOpBIT, "instOpBIT")
	addOpId(instOpASL, "instOpASL")
	addOpId(instOaASL, "instOaASL")
	addOpId(instOpLSR, "instOpLSR")
	addOpId(instOaLSR, "instOaLSR")
	addOpId(instOpROL, "instOpROL")
	addOpId(instOaROL, "instOaROL")
	addOpId(instOpROR, "instOpROR")
	addOpId(instOaROR, "instOaROR")
	addOpId(instOpJMP, "instOpJMP")
	addOpId(instOpJMP1, "instOpJMP1")
	addOpId(instOiJMP, "instOiJMP")
	addOpId(instOiJMP1, "instOiJMP1")
	addOpId(instOpJSR, "instOpJSR")
	addOpId(instOpJSR1, "instOpJSR1")
	addOpId(instOpJSR2, "instOpJSR2")
	addOpId(instOpJSR3, "instOpJSR3")
	addOpId(instOpJSR4, "instOpJSR4")
	addOpId(instOpRTS, "instOpRTS")
	addOpId(instOpRTS1, "instOpRTS1")
	addOpId(instOpRTS2, "instOpRTS2")
	addOpId(instOpRTS3, "instOpRTS3")
	addOpId(instOpRTS4, "instOpRTS4")
	addOpId(instOpRTI, "instOpRTI")
	addOpId(instOpRTI1, "instOpRTI1")
	addOpId(instOpRTI2, "instOpRTI2")
	addOpId(instOpRTI3, "instOpRTI3")
	addOpId(instOpRTI4, "instOpRTI4")
	addOpId(instOpBRK, "instOpBRK")
	addOpId(instOpBRK1, "instOpBRK1")
	addOpId(instOpBRK2, "instOpBRK2")
	addOpId(instOpBRK3, "instOpBRK3")
	addOpId(instOpBRK4, "instOpBRK4")
	addOpId(instOpBRK5, "instOpBRK5")
	addOpId(instOpBCS, "instOpBCS")
	addOpId(instOpBCC, "instOpBCC")
	addOpId(instOpBEQ, "instOpBEQ")
	addOpId(instOpBNE, "instOpBNE")
	addOpId(instOpBVS, "instOpBVS")
	addOpId(instOpBVC, "instOpBVC")
	addOpId(instOpBMI, "instOpBMI")
	addOpId(instOpBPL, "instOpBPL")
	addOpId(instOpBRAnp, "instOpBRAnp")
	addOpId(instOpBRAbp, "instOpBRAbp")
	addOpId(instOpBRAbp1, "instOpBRAbp1")
	addOpId(instOpBRAfp, "instOpBRAfp")
	addOpId(instOpBRAfp1, "instOpBRAfp1")
}

func addOpId(v func(cpu *CPU), id string) {
	r := reflect.ValueOf(v)
	_opContainer[r] = id
	_opReverseContainer[id] = r
}

func GetOpId(v func(cpu *CPU)) (string, bool) {
	if v == nil {
		return "", false
	}
	r := reflect.ValueOf(v)
	ret, ok := _opContainer[r]
	if !ok {
		return "", false
	}
	return ret, true
}

func GetOpFn(v string) (func(cpu *CPU), bool) {
	r, ok := _opReverseContainer[v]
	if !ok {
		return nil, false
	}
	ret, ok := r.Interface().(func(cpu *CPU))
	if !ok {
		return nil, false
	}
	return ret, true
}
