package mos6510

import "reflect"

var _opContainer = map[reflect.Value]string{
	reflect.ValueOf(instOpPHA):    "instOpPHA",
	reflect.ValueOf(instOpPHA1):   "instOpPHA1",
	reflect.ValueOf(instOpPLA):    "instOpPLA",
	reflect.ValueOf(instOpPLA1):   "instOpPLA1",
	reflect.ValueOf(instOpPLA2):   "instOpPLA2",
	reflect.ValueOf(instOpPHP):    "instOpPHP",
	reflect.ValueOf(instOpPHP1):   "instOpPHP1",
	reflect.ValueOf(instOpPLP):    "instOpPLP",
	reflect.ValueOf(instOpPLP1):   "instOpPLP1",
	reflect.ValueOf(instOpPLP2):   "instOpPLP2",
	reflect.ValueOf(instOpNMI):    "instOpNMI",
	reflect.ValueOf(instOpNMI1):   "instOpNMI1",
	reflect.ValueOf(instOpNMI2):   "instOpNMI2",
	reflect.ValueOf(instOpNMI3):   "instOpNMI3",
	reflect.ValueOf(instOpNMI4):   "instOpNMI4",
	reflect.ValueOf(instOpNMI5):   "instOpNMI5",
	reflect.ValueOf(instOpNMI6):   "instOpNMI6",
	reflect.ValueOf(instApZER):    "instApZER",
	reflect.ValueOf(instApZERx):   "instApZERx",
	reflect.ValueOf(instApZERx1):  "instApZERx1",
	reflect.ValueOf(instApZERy):   "instApZERy",
	reflect.ValueOf(instApZERy1):  "instApZERy1",
	reflect.ValueOf(instApABS):    "instApABS",
	reflect.ValueOf(instApABS1):   "instApABS1",
	reflect.ValueOf(instApABSx):   "instApABSx",
	reflect.ValueOf(instApABSx1):  "instApABSx1",
	reflect.ValueOf(instApABSx2):  "instApABSx2",
	reflect.ValueOf(instApABSx3):  "instApABSx3",
	reflect.ValueOf(instApABSy):   "instApABSy",
	reflect.ValueOf(instApABSy1):  "instApABSy1",
	reflect.ValueOf(instApABSy2):  "instApABSy2",
	reflect.ValueOf(instApABSy3):  "instApABSy3",
	reflect.ValueOf(instApINDx):   "instApINDx",
	reflect.ValueOf(instApINDx1):  "instApINDx1",
	reflect.ValueOf(instApINDx2):  "instApINDx2",
	reflect.ValueOf(instApINDx3):  "instApINDx3",
	reflect.ValueOf(instApINDy):   "instApINDy",
	reflect.ValueOf(instApINDy1):  "instApINDy1",
	reflect.ValueOf(instApINDy2):  "instApINDy2",
	reflect.ValueOf(instApINDy3):  "instApINDy3",
	reflect.ValueOf(instApINDy4):  "instApINDy4",
	reflect.ValueOf(instAeABSx):   "instAeABSx",
	reflect.ValueOf(instAeABSx1):  "instAeABSx1",
	reflect.ValueOf(instAeABSx2):  "instAeABSx2",
	reflect.ValueOf(instAeABSy):   "instAeABSy",
	reflect.ValueOf(instAeABSy1):  "instAeABSy1",
	reflect.ValueOf(instAeABSy2):  "instAeABSy2",
	reflect.ValueOf(instAeINDy):   "instAeINDy",
	reflect.ValueOf(instAeINDy1):  "instAeINDy1",
	reflect.ValueOf(instAeINDy2):  "instAeINDy2",
	reflect.ValueOf(instAeINDy3):  "instAeINDy3",
	reflect.ValueOf(instMpZER):    "instMpZER",
	reflect.ValueOf(instMpZERx):   "instMpZERx",
	reflect.ValueOf(instMpZERx1):  "instMpZERx1",
	reflect.ValueOf(instMpABS):    "instMpABS",
	reflect.ValueOf(instMpABS1):   "instMpABS1",
	reflect.ValueOf(instMpABSx):   "instMpABSx",
	reflect.ValueOf(instMpABSx1):  "instMpABSx1",
	reflect.ValueOf(instMpABSx2):  "instMpABSx2",
	reflect.ValueOf(instMpABSx3):  "instMpABSx3",
	reflect.ValueOf(instMpABSy):   "instMpABSy",
	reflect.ValueOf(instMpABSy1):  "instMpABSy1",
	reflect.ValueOf(instMpABSy2):  "instMpABSy2",
	reflect.ValueOf(instMpABSy3):  "instMpABSy3",
	reflect.ValueOf(instMpINDx):   "instMpINDx",
	reflect.ValueOf(instMpINDx1):  "instMpINDx1",
	reflect.ValueOf(instMpINDx2):  "instMpINDx2",
	reflect.ValueOf(instMpINDx3):  "instMpINDx3",
	reflect.ValueOf(instMpINDy):   "instMpINDy",
	reflect.ValueOf(instMpINDy1):  "instMpINDy1",
	reflect.ValueOf(instMpINDy2):  "instMpINDy2",
	reflect.ValueOf(instMpINDy3):  "instMpINDy3",
	reflect.ValueOf(instMpINDy4):  "instMpINDy4",
	reflect.ValueOf(instOpRMW):    "instOpRMW",
	reflect.ValueOf(instOpRMW1):   "instOpRMW1",
	reflect.ValueOf(instOpLDA):    "instOpLDA",
	reflect.ValueOf(instOiLDA):    "instOiLDA",
	reflect.ValueOf(instOpLDX):    "instOpLDX",
	reflect.ValueOf(instOiLDX):    "instOiLDX",
	reflect.ValueOf(instOpLDY):    "instOpLDY",
	reflect.ValueOf(instOiLDY):    "instOiLDY",
	reflect.ValueOf(instOpSTA):    "instOpSTA",
	reflect.ValueOf(instOpSTX):    "instOpSTX",
	reflect.ValueOf(instOpSTY):    "instOpSTY",
	reflect.ValueOf(instOpIRQ):    "instOpIRQ",
	reflect.ValueOf(instOpIRQ1):   "instOpIRQ1",
	reflect.ValueOf(instOpIRQ2):   "instOpIRQ2",
	reflect.ValueOf(instOpIRQ3):   "instOpIRQ3",
	reflect.ValueOf(instOpIRQ4):   "instOpIRQ4",
	reflect.ValueOf(instOpIRQ5):   "instOpIRQ5",
	reflect.ValueOf(instOpIRQ6):   "instOpIRQ6",
	reflect.ValueOf(instOiNOP):    "instOiNOP",
	reflect.ValueOf(instOaNOP):    "instOaNOP",
	reflect.ValueOf(instOpLAX):    "instOpLAX",
	reflect.ValueOf(instOpSAX):    "instOpSAX",
	reflect.ValueOf(instOpSLO):    "instOpSLO",
	reflect.ValueOf(instOpRLA):    "instOpRLA",
	reflect.ValueOf(instOpSRE):    "instOpSRE",
	reflect.ValueOf(instOpRRA):    "instOpRRA",
	reflect.ValueOf(instOpDCP):    "instOpDCP",
	reflect.ValueOf(instOpISB):    "instOpISB",
	reflect.ValueOf(instOiANC):    "instOiANC",
	reflect.ValueOf(instOiASR):    "instOiASR",
	reflect.ValueOf(instOiARR):    "instOiARR",
	reflect.ValueOf(instOiANE):    "instOiANE",
	reflect.ValueOf(instOiLXA):    "instOiLXA",
	reflect.ValueOf(instOiSBX):    "instOiSBX",
	reflect.ValueOf(instOpLAS):    "instOpLAS",
	reflect.ValueOf(instOpSHS):    "instOpSHS",
	reflect.ValueOf(instOpSHY):    "instOpSHY",
	reflect.ValueOf(instOpSHX):    "instOpSHX",
	reflect.ValueOf(instOpSHA):    "instOpSHA",
	reflect.ValueOf(instOpJAM):    "instOpJAM",
	reflect.ValueOf(instOpTAX):    "instOpTAX",
	reflect.ValueOf(instOpTXA):    "instOpTXA",
	reflect.ValueOf(instOpTAY):    "instOpTAY",
	reflect.ValueOf(instOpTYA):    "instOpTYA",
	reflect.ValueOf(instOpTSX):    "instOpTSX",
	reflect.ValueOf(instOpTXS):    "instOpTXS",
	reflect.ValueOf(instOpSEC):    "instOpSEC",
	reflect.ValueOf(instOpCLC):    "instOpCLC",
	reflect.ValueOf(instOpSED):    "instOpSED",
	reflect.ValueOf(instOpCLD):    "instOpCLD",
	reflect.ValueOf(instOpSEI):    "instOpSEI",
	reflect.ValueOf(instOpCLI):    "instOpCLI",
	reflect.ValueOf(instOpCLV):    "instOpCLV",
	reflect.ValueOf(instOpNOP):    "instOpNOP",
	reflect.ValueOf(instOpADC):    "instOpADC",
	reflect.ValueOf(instOiADC):    "instOiADC",
	reflect.ValueOf(instOpSBC):    "instOpSBC",
	reflect.ValueOf(instOiSBC):    "instOiSBC",
	reflect.ValueOf(instOpINX):    "instOpINX",
	reflect.ValueOf(instOpDEX):    "instOpDEX",
	reflect.ValueOf(instOpINY):    "instOpINY",
	reflect.ValueOf(instOpDEY):    "instOpDEY",
	reflect.ValueOf(instOpINC):    "instOpINC",
	reflect.ValueOf(instOpDEC):    "instOpDEC",
	reflect.ValueOf(instOpAND):    "instOpAND",
	reflect.ValueOf(instOiAND):    "instOiAND",
	reflect.ValueOf(instOpORA):    "instOpORA",
	reflect.ValueOf(instOiOPA):    "instOiOPA",
	reflect.ValueOf(instOpEOR):    "instOpEOR",
	reflect.ValueOf(instOiEOR):    "instOiEOR",
	reflect.ValueOf(instOpCMP):    "instOpCMP",
	reflect.ValueOf(instOiCMP):    "instOiCMP",
	reflect.ValueOf(instOpCPX):    "instOpCPX",
	reflect.ValueOf(instOiCPX):    "instOiCPX",
	reflect.ValueOf(instOpCPY):    "instOpCPY",
	reflect.ValueOf(instOiCPY):    "instOiCPY",
	reflect.ValueOf(instOpBIT):    "instOpBIT",
	reflect.ValueOf(instOpASL):    "instOpASL",
	reflect.ValueOf(instOaASL):    "instOaASL",
	reflect.ValueOf(instOpLSR):    "instOpLSR",
	reflect.ValueOf(instOaLSR):    "instOaLSR",
	reflect.ValueOf(instOpROL):    "instOpROL",
	reflect.ValueOf(instOaROL):    "instOaROL",
	reflect.ValueOf(instOpROR):    "instOpROR",
	reflect.ValueOf(instOaROR):    "instOaROR",
	reflect.ValueOf(instOpJMP):    "instOpJMP",
	reflect.ValueOf(instOpJMP1):   "instOpJMP1",
	reflect.ValueOf(instOiJMP):    "instOiJMP",
	reflect.ValueOf(instOiJMP1):   "instOiJMP1",
	reflect.ValueOf(instOpJSR):    "instOpJSR",
	reflect.ValueOf(instOpJSR1):   "instOpJSR1",
	reflect.ValueOf(instOpJSR2):   "instOpJSR2",
	reflect.ValueOf(instOpJSR3):   "instOpJSR3",
	reflect.ValueOf(instOpJSR4):   "instOpJSR4",
	reflect.ValueOf(instOpRTS):    "instOpRTS",
	reflect.ValueOf(instOpRTS1):   "instOpRTS1",
	reflect.ValueOf(instOpRTS2):   "instOpRTS2",
	reflect.ValueOf(instOpRTS3):   "instOpRTS3",
	reflect.ValueOf(instOpRTS4):   "instOpRTS4",
	reflect.ValueOf(instOpRTI):    "instOpRTI",
	reflect.ValueOf(instOpRTI1):   "instOpRTI1",
	reflect.ValueOf(instOpRTI2):   "instOpRTI2",
	reflect.ValueOf(instOpRTI3):   "instOpRTI3",
	reflect.ValueOf(instOpRTI4):   "instOpRTI4",
	reflect.ValueOf(instOpBRK):    "instOpBRK",
	reflect.ValueOf(instOpBRK1):   "instOpBRK1",
	reflect.ValueOf(instOpBRK2):   "instOpBRK2",
	reflect.ValueOf(instOpBRK3):   "instOpBRK3",
	reflect.ValueOf(instOpBRK4):   "instOpBRK4",
	reflect.ValueOf(instOpBRK5):   "instOpBRK5",
	reflect.ValueOf(instOpBCS):    "instOpBCS",
	reflect.ValueOf(instOpBCC):    "instOpBCC",
	reflect.ValueOf(instOpBEQ):    "instOpBEQ",
	reflect.ValueOf(instOpBNE):    "instOpBNE",
	reflect.ValueOf(instOpBVS):    "instOpBVS",
	reflect.ValueOf(instOpBVC):    "instOpBVC",
	reflect.ValueOf(instOpBMI):    "instOpBMI",
	reflect.ValueOf(instOpBPL):    "instOpBPL",
	reflect.ValueOf(instOpBRAnp):  "instOpBRAnp",
	reflect.ValueOf(instOpBRAbp):  "instOpBRAbp",
	reflect.ValueOf(instOpBRAbp1): "instOpBRAbp1",
	reflect.ValueOf(instOpBRAfp):  "instOpBRAfp",
	reflect.ValueOf(instOpBRAfp1): "instOpBRAfp1",
}

var _opReverseContainer map[string]reflect.Value

func init() {
	_opReverseContainer = make(map[string]reflect.Value)
	for f, name := range _opContainer {
		_opReverseContainer[name] = f
	}
}

func GetOpId(v interface{}) (string, bool) {
	if v == nil {
		return "", false
	}
	r := reflect.ValueOf(v)
	ret, ok := _opContainer[r]
	if !ok {
		return "", false
	}
	return ret, true
}

func GetOpFn(v string) (func(cpu *CPU), bool) {
	r, ok := _opReverseContainer[v]
	if !ok {
		return nil, false
	}
	ret, ok := r.Interface().(func(cpu *CPU))
	if !ok {
		return nil, false
	}
	return ret, true
}
