package stub

import (
	"bytes"
	"embed"
	"fmt"
	"log"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/markel1974/c64emu/src/compilers"
	"github.com/markel1974/c64emu/src/vm/bytecode"
	"github.com/markel1974/c64emu/src/vm/handler"
	"github.com/markel1974/c64emu/src/vm/objects"
	"github.com/markel1974/c64emu/src/vm/sequencers"
)

// All is an embedded filesystem containing files from the specified directories for runtime access.
//
//go:embed sources/*.go
//go:embed tests/*.go
var All embed.FS

type FileInfo struct {
	Name string
	Data []byte
}

func NewFileInfo(name string) *FileInfo {
	data, _ := All.ReadFile(name)
	return &FileInfo{Name: name, Data: data}
}

// walk traverses the given directory recursively, filtering files based on the specified prefix, and appends them to the provided list.
func walk(baseDir string, prefix string, files *[]string) error {
	data, err := All.ReadDir(baseDir)
	if err != nil {
		return err
	}
	for _, v := range data {
		target := filepath.Join(baseDir, v.Name())
		if v.IsDir() {
			if err = walk(target, prefix, files); err != nil {
				return err
			}
		}
		if !strings.HasPrefix(v.Name(), prefix) {
			continue
		}
		*(files) = append(*(files), target)
	}
	return nil
}

// Launch processes files matching a given prefix, compiles their content, and executes the compiled bytecode.
// It initializes key components like GateKeeper, Sequencer, and Loader to manage dependencies and execution context.
// Parameters:
// - prefix: String prefix to filter target files in the directory.
// - debug: Boolean flag to enable debug logs when compiling and executing bytecode.
// Returns:
// - error: An error object if any compilation or execution step fails, otherwise nil.
func Launch(prefix string, entry string, args []interface{}, debug bool) error {
	var files []string
	err := walk(".", prefix, &files)
	if err != nil {
		return nil
	}
	sort.Strings(files)

	gk := objects.NewGateKeeper()
	for _, fileName := range files {

		fmt.Printf("\n\n------------------ %s ------------------\n", fileName)
		fi := NewFileInfo(fileName)
		seq, err := sequencers.NewSequencers("native")
		if err != nil {
			return err
		}
		loader := bytecode.NewLoader(gk)
		bc, err := Compile(gk, seq, loader, []*FileInfo{fi})
		if err != nil {
			return err
		}
		if debug {
			d := bytecode.NewDisassembler(bc, seq)
			_ = d.Disassemble(log.Writer())
		}
		start := time.Now()
		vm, rv, err := Exec(gk, seq, loader, bc, entry, args, debug)
		if err != nil {
			return err
		}
		end := time.Since(start)
		_, allocatedObjects, iterations, maxFrames := vm.Statistics()
		fmt.Println("------------- Result -------------")
		fmt.Printf("elapsed: %v, allocatedObjects: %d, iterations: %d, frames: %d\n", end, allocatedObjects, iterations, maxFrames)
		fmt.Printf("return values:%v\n", rv)
	}
	return nil
}

// Compile reads a file, compiles its contents, and returns the generated bytecode along with any encountered error.
func Compile(gk objects.IGateKeeper, seq handler.ISequencer, loader bytecode.ILoader, sources []*FileInfo) (*bytecode.Bytecode, error) {
	if len(sources) == 0 {
		return nil, fmt.Errorf("no sources found")
	}
	c, err := compilers.NewCompiler(gk, seq, loader)
	if err != nil {
		return nil, err
	}
	if len(sources) == 1 {
		if err = c.Compile(sources[0].Name, sources[0].Data); err != nil {
			return nil, err
		}
		return bytecode.NewBytecode(gk, c.Constants(), c.Imports(), c.Globals(), c.FileSet()), nil
	}
	rel := bytecode.NewRelocator(gk, loader, seq, bytecode.PreInitFunction, bytecode.InitFunction)
	for _, data := range sources {
		if err = c.Compile(data.Name, data.Data); err != nil {
			return nil, err
		}
		bc := bytecode.NewBytecode(gk, c.Constants(), c.Imports(), c.Globals(), c.FileSet())
		rel.Add(bc)
	}
	return rel.Relocate()
}

// Exec initializes and runs a virtual machine instance with the given gatekeeper, sequencer, loader, bytecode, and debug mode.
// It binds the sequencer to the virtual machine, sets up entry points, and executes the "main" entry point.
// Returns an error if setup or execution fails, optionally logging debug information during runtime errors.
func Exec(gk objects.IGateKeeper, seq handler.ISequencer, loader bytecode.ILoader, bc *bytecode.Bytecode, entry string, args []interface{}, debug bool) (*handler.VM, []interface{}, error) {
	//var args []interface{} = nil
	//args := []interface{}{1, 2}
	vm := handler.NewVM(gk, seq, seq)
	entries, err := vm.Setup(loader, bc)
	if err != nil {
		vm.Print(log.Writer())
		return nil, nil, err
	}
	mainId, ok := entries[entry]
	if !ok {
		return nil, nil, fmt.Errorf("entry point not found: %s", entry)
	}
	vm.EnableRetValues(true)
	rv, err := vm.Run(mainId, args...)
	if debug {
		vm.Print(log.Writer())
	}
	return vm, rv, err
}

// Marshal serializes the provided Bytecode into a byte slice, returning an error if the encoding process fails.
func Marshal(bc *bytecode.Bytecode) ([]byte, error) {
	buf := bytes.NewBuffer([]byte{})
	if err := bc.Encode(buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// Unmarshal deserializes data from a buffer into a new Bytecode instance using the provided IGateKeeper.
func Unmarshal(gk objects.IGateKeeper, buf *bytes.Buffer) (*bytecode.Bytecode, error) {
	bc := bytecode.NewBytecodeEmpty(gk)
	if err := bc.Decode(buf); err != nil {
		return nil, err
	}
	return bc, nil
}
