package stub

import (
	"bytes"
	"embed"
	"fmt"
	"log"
	"path/filepath"
	"sort"
	"strings"

	_nativeCompiler "github.com/markel1974/c64emu/src/compilers/native/compiler"
	_nativeLoader "github.com/markel1974/c64emu/src/compilers/native/sdk"
	"github.com/markel1974/c64emu/src/vm/bytecode"
	"github.com/markel1974/c64emu/src/vm/core"
	"github.com/markel1974/c64emu/src/vm/objects"
	"github.com/markel1974/c64emu/src/vm/sequencers/native"
)

// All is an embedded filesystem containing files from the specified directories for runtime access.
//
//go:embed sources/*.go
//go:embed tests/*.go
var All embed.FS

// walk traverses the given directory recursively, filtering files based on the specified prefix, and appends them to the provided list.
func walk(baseDir string, prefix string, files *[]string) error {
	data, err := All.ReadDir(baseDir)
	if err != nil {
		return err
	}
	for _, v := range data {
		target := filepath.Join(baseDir, v.Name())
		if v.IsDir() {
			if err = walk(target, prefix, files); err != nil {
				return err
			}
		}
		if !strings.HasPrefix(v.Name(), prefix) {
			continue
		}
		*(files) = append(*(files), target)
	}
	return nil
}

// Launch processes files matching a given prefix, compiles their content, and executes the compiled bytecode.
// It initializes key components like GateKeeper, Sequencer, and Loader to manage dependencies and execution context.
// Parameters:
// - prefix: String prefix to filter target files in the directory.
// - debug: Boolean flag to enable debug logs when compiling and executing bytecode.
// Returns:
// - error: An error object if any compilation or execution step fails, otherwise nil.
func Launch(prefix string, debug bool) error {
	var files []string
	if err := walk(".", prefix, &files); err != nil {
		return nil
	}
	sort.Strings(files)

	gk := objects.NewGateKeeper()
	for _, fileName := range files {
		fmt.Printf("\n\n------------------ %s ------------------\n", fileName)
		seq := native.NewSequencer()
		if err := seq.Setup(); err != nil {
			return err
		}
		loader, err := _nativeLoader.NewLoader(gk)
		if err != nil {
			return err
		}
		bc, err := Compile(gk, seq, loader, fileName, debug)
		if err != nil {
			return err
		}
		if err = Exec(gk, seq, loader, bc, debug); err != nil {
			return err
		}
	}
	return nil
}

// Compile reads a file, compiles its contents, and returns the generated bytecode along with any encountered error.
func Compile(gk objects.IGateKeeper, seq core.ISequencer, loader bytecode.ILoader, fileName string, debug bool) (*bytecode.Bytecode, error) {
	compiler := _nativeCompiler.New(gk, loader, seq)
	data, err := All.ReadFile(fileName)
	if err != nil {
		return nil, fmt.Errorf("read file error: %s", err)
	}
	if err = compiler.Compile(fileName, data); err != nil {
		return nil, fmt.Errorf("compiler error: %s", err)
	}
	bc := bytecode.NewBytecode(gk, compiler.Constants(), compiler.Imports(), compiler.Globals(), compiler.FileSet())
	if debug {
		d := bytecode.NewDisassembler(bc, seq)
		_ = d.Disassemble(log.Writer())
	}
	return bc, nil
}

// Exec initializes and runs a virtual machine instance with the given gatekeeper, sequencer, loader, bytecode, and debug mode.
// It binds the sequencer to the virtual machine, sets up entry points, and executes the "main" entry point.
// Returns an error if setup or execution fails, optionally logging debug information during runtime errors.
func Exec(gk objects.IGateKeeper, seq core.ISequencer, loader bytecode.ILoader, bc *bytecode.Bytecode, debug bool) error {
	var args []interface{} = nil
	//args := []interface{}{1, 2}
	machine := core.New(gk, seq)
	if err := seq.Bind(machine); err != nil {
		return err
	}
	entries, err := machine.Setup(loader, seq.Executors(), bc)
	if err != nil {
		machine.Print(log.Writer())
		return fmt.Errorf("vm setup error: %s", err)
	}
	machine.EnableRetValues(true)
	rv, err := machine.Run(entries["main"], args...)
	if err != nil {
		if debug {
			machine.Print(log.Writer())
		}
		return fmt.Errorf("vm runtime error: %s", err)
	}
	if debug {
		machine.Print(log.Writer())
	}
	fmt.Println("RETURN VALUEs", rv)
	return nil
}

// Marshal serializes the provided Bytecode into a byte slice, returning an error if the encoding process fails.
func Marshal(bc *bytecode.Bytecode) ([]byte, error) {
	buf := bytes.NewBuffer([]byte{})
	if err := bc.Encode(buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// Unmarshal deserializes data from a buffer into a new Bytecode instance using the provided IGateKeeper.
func Unmarshal(gk objects.IGateKeeper, buf *bytes.Buffer) (*bytecode.Bytecode, error) {
	bc := bytecode.NewBytecodeEmpty(gk)
	if err := bc.Decode(buf); err != nil {
		return nil, err
	}
	return bc, nil
}

// Relocate relocates components of multiple Bytecode instances into a single, unified Bytecode using the provided dependencies.
func Relocate(gk objects.IGateKeeper, seq core.ISequencer, loader bytecode.ILoader, z []*bytecode.Bytecode) (*bytecode.Bytecode, error) {
	rel := bytecode.NewRelocator(gk, loader, seq, bytecode.PreInitFunction, bytecode.InitFunction)
	bc, err := rel.Relocate(z)
	return bc, err
}
