package pixels

import "fmt"

type GLCanvasPicture struct {
	IGLPicture
	dst *GLCanvas
}

func NewGLCanvasPicture(t IGLPicture, dst *GLCanvas) *GLCanvasPicture {
	return &GLCanvasPicture{
		IGLPicture: t,
		dst:        dst,
	}
}

func (cp *GLCanvasPicture) Draw(t ITargetTriangles) {
	ct := t.(*GLCanvasTriangles)
	if cp.dst != ct.dst {
		panic(fmt.Errorf("(%T).Draw: ITargetTriangles generated by different GLCanvas", cp))
	}
	ct.draw(cp.IGLPicture.Texture(), cp.IGLPicture.Bounds())
}

func (cp *GLCanvasPicture) Update(p IPicture) {
	cp.IGLPicture.Update(p)
}
