package references

// IViaSocket defines an interface for interacting with peripheral register operations and interrupt handling in a system.
// ReadPRA reads from Port A register considering its current state and data direction register.
// ReadPRB reads from Port B register considering its current state and data direction register.
// WritePRA writes to Port A register while considering its associated data direction register.
// WritePRB writes to Port B register while considering its associated data direction register.
// WriteDDRA writes to the Data Direction Register associated with Port A to configure I/O direction.
// WriteDDRB writes to the Data Direction Register associated with Port B to configure I/O direction.
// IRQClear clears any pending interrupt requests generated by the socket.
// IRQTrigger triggers an interrupt request to signal an event in the socket.
type IViaSocket interface {
	ReadPRA(uint8, uint8) uint8
	ReadPRB(uint8, uint8) uint8
	WritePRA(uint8, uint8)
	WritePRB(uint8, uint8)
	WriteDDRA(uint8, uint8)
	WriteDDRB(uint8, uint8)

	IRQClear()
	IRQTrigger()
}
