package c64_keyboard_rev1

// Code generated by symphony-generator. DO NOT EDIT.

import (
	"errors"
	"github.com/markel1974/c64emu/src/references"
)

const (
	reflectEnabledId = "enabled"
)

type KeyboardReflect struct {
	ref              *Keyboard
	outOfBoundsError error
	readOnlyError    error
}

func NewKeyboardReflect(r *Keyboard, factory references.IComponentFactory, parent references.IComponent, identifier string, instance int, hardwareId string) *KeyboardReflect {
	reflector := &KeyboardReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.BaseComponent.Register(factory, parent, identifier, instance, r, hardwareId)
	r.PropertyAdd(reflectEnabledId, "Enabled", false, reflector.getEnabled, reflector.setEnabled)

	_ = r.CommandAdd("NumLockToggle", "NumLockToggle() - NumLockToggle toggles the current state of the Num Lock key by inverting its value on the virtual keyboard.", r.NumLockToggle)
	_ = r.CommandAdd("CapitalToggle", "CapitalToggle() - CapitalToggle toggles the state of the capital key (caps lock) on the virtual keyboard.", r.CapitalToggle)
	_ = r.CommandAdd("SetCommand", "SetCommand(cmd) - SetCommand processes a given string command, converting each character to corresponding key codes and storing them.", r.SetCommand)
	_ = r.CommandAdd("Reset", "Reset() - Reset reinitializes the Keyboard by resetting its storage, virtual key states, and ASCII translations.", r.Reset)
	_ = r.CommandAdd("SetKey", "SetKey(pressed, vKey) - SetKey processes a virtual key press or release by mapping it to a key code and updating the keyboard's storage.", r.SetKey)
	_ = r.CommandAdd("SetKeyPressed", "SetKeyPressed(vKey) - SetKeyPressed triggers a virtual key press for the specified virtual key code by internally calling SetKey.", r.SetKeyPressed)
	_ = r.CommandAdd("SetKeyReleased", "SetKeyReleased(vKey) - SetKeyReleased triggers a virtual key release for the specified virtual key code by internally calling SetKey.", r.SetKeyReleased)
	_ = r.CommandAdd("Poll", "Poll() uint32,bool - Poll retrieves the next key from the keyboard storage as a uint32 and indicates if a key was available.  Returns the key value and true if a key was retrieved, otherwise returns 0 and false.", r.Poll)
	_ = r.CommandAdd("Emulate", "Emulate() - ", r.Emulate)

	return reflector
}

// getEnabled is the generated getter for the enabled.
func (s *KeyboardReflect) getEnabled() int {
	return s.ref.enabled
}

// setEnabled is the generated setter for the enabled field.
func (s *KeyboardReflect) setEnabled(v int) error {
	s.ref.enabled = v
	return nil
}
