package component

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"io"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

var _disallowedMethods = map[string]bool{
	"Setup": true, "Bind": true, "Connect": true, "Wire": true, "Internal": true, "EmulationRequired": true,
}

// allowedBaseTypes defines a set of primitive base types that are considered valid for specific operations or checks.
var _allowedBaseTypes = map[string]bool{
	"string": true, "bool": true, "int": true, "int8": true, "int16": true, "int32": true, "int64": true,
	"uint": true, "uint8": true, "uint16": true, "uint32": true, "uint64": true, "float32": true, "float64": true,
}

// allowedSliceElementTypes defines the set of data types allowed for elements within slice types.
var _allowedSliceElementTypes = map[string]bool{
	"int": true, "int8": true, "int16": true, "int32": true, "int64": true,
	"byte": true, "uint": true, "uint8": true, "uint16": true, "uint32": true, "uint64": true,
}

// exporterPrefix defines the prefix used for symphony export-related operations.
// exporterFileSuffix specifies the suffix for generated reflection files.
// readonlyKeyword indicates the readonly access keyword for operations.
const (
	exporterPrefix     = "symphony:export"
	exporterFileSuffix = "_reflect_gen"
	readonlyKeyword    = "readonly"
)

// reflectTemplate is a constant template string used to generate Go code for struct reflection and property manipulation.
const reflectTemplate = `package {{.PackageName}}

// Code generated by symphony-generator. DO NOT EDIT.

import "errors"

const (
    {{- range .Properties}}
    {{.IDVarName}} = "{{.FieldName}}"
    {{- end}}
)

type {{.StructName}}Reflect struct {
    ref *{{.StructName}}
    err error
}

func New{{.StructName}}Reflect(r *{{.StructName}}) *{{.StructName}}Reflect {
    reflector := &{{.StructName}}Reflect{ref: r}
    {{- range .Properties}}
    r.PropertyAdd({{.IDVarName}}, "{{.Documentation}}", {{.ReadOnly}}, reflector.{{.GetterName}}, reflector.{{.SetterName}})
    {{if eq .Kind 2}}
    _ = r.CommandAdd("{{.CommandGetterName}}", "{{.Documentation}}", reflector.{{.CommandGetterName}})
    _ = r.CommandAdd("{{.CommandSetterName}}", "{{.Documentation}}", reflector.{{.CommandSetterName}})
    {{end}}
    {{- end}}

 	{{- range .Methods}}
    _ = r.CommandAdd("{{.Name}}", "{{.Documentation}}", r.{{.Name}})
    {{- end}}

    return reflector
}
{{range .Properties}}
// {{.GetterName}} is the generated getter for the {{.FieldName}}.
func (s *{{$.StructName}}Reflect) {{.GetterName}}() {{.FieldType}} {
    {{.GetterBody}}
}

// {{.SetterName}} is the generated setter for the {{.FieldName}} field.{{if not .ReadOnly}}
func (s *{{$.StructName}}Reflect) {{.SetterName}}(v {{.FieldType}}) error {
    {{.SetterBody}}
}{{else}}
func (s *{{$.StructName}}Reflect) {{.SetterName}}(v {{.FieldType}}) error {
    // property {{.FieldName}} is read-only.
    return errors.New("property {{.FieldName}} is read-only")
}
{{end}}
{{if eq .Kind 2}}
// {{.CommandGetterName}} is the generated indexed getter for the {{.FieldName}}.
func (s *{{$.StructName}}Reflect) {{.CommandGetterName}}(idx int) ({{.SliceElementType}}, error) {
    {{.CommandGetterBody}}
}

// {{.CommandSetterName}} is the generated indexed setter for the {{.FieldName}}.
func (s *{{$.StructName}}Reflect) {{.CommandSetterName}}(idx int, v {{.SliceElementType}}) error {
    {{.CommandSetterBody}}
}
{{end}}
{{end}}
`

// Property represents the metadata and generated logic for a struct field to enable various code generation features.
type Property struct {
	FieldName         string
	IDVarName         string
	GetterName        string
	SetterName        string
	FieldType         string
	Documentation     string
	ReadOnly          bool
	Kind              int
	GetterBody        string
	SetterBody        string
	CommandGetterName string
	CommandSetterName string
	CommandGetterBody string
	CommandSetterBody string
	SliceElementType  string
}

type Method struct {
	Name          string
	Documentation string
}

// TemplateData represents the template context used during code generation.
// It contains the package name, the struct name, and the list of properties for the struct.
type TemplateData struct {
	PackageName string
	StructName  string
	Properties  []Property
	Methods     []Method
}

// StructData represents metadata for a struct, including its name and associated properties.
type StructData struct {
	Name       string
	Type       *ast.StructType
	FuncDecl   map[string]*ast.FuncDecl
	Properties []Property
	Methods    []Method
}

// NewStructData creates and initializes a new StructData instance with the provided name.
func NewStructData(name string) *StructData {
	return &StructData{Name: name, Properties: []Property{}, FuncDecl: make(map[string]*ast.FuncDecl)}
}

// CompileMethods processes the exported methods of the struct, validates their parameters, and appends valid methods to Methods.
func (sd *StructData) CompileMethods(fileSet *token.FileSet) {
	for _, method := range sd.FuncDecl {
		if !method.Name.IsExported() {
			continue
		}
		if _disallowedMethods[method.Name.Name] {
			continue
		}
		valid := true
		var args []string
		for _, param := range method.Type.Params.List {
			fieldType, err := toType(fileSet, param.Type)
			if err != nil {
				valid = false
				break
			}
			if kind := typeAllowed(fieldType); kind == 0 {
				valid = false
				break
			}
			args = append(args, param.Names[0].Name) //+" "+fieldType)
		}
		if valid {
			doc := method.Name.Name + "(" + strings.Join(args, ", ") + ") " + getDoc(method.Doc.List, method.Name.Name)
			sd.Methods = append(sd.Methods, Method{Name: method.Name.Name, Documentation: doc})
		}
	}
}

// CompileProperties processes the fields of a struct, generating metadata for supported properties with getters and setters.
func (sd *StructData) CompileProperties(fileSet *token.FileSet) {
	structType := sd.Type
	for _, field := range structType.Fields.List {
		if field.Comment == nil || len(field.Names) == 0 {
			continue
		}
		//if !strings.Contains(commentText, exporterPrefix) {
		//	continue
		//}
		fieldName := field.Names[0].Name
		fieldType, err := toType(fileSet, field.Type)
		if err != nil {
			log.Printf("error determining type for field %s: %v", fieldName, err)
			continue
		}
		kind := typeAllowed(fieldType)
		if kind == 0 {
			log.Printf("warning: Skipping field '%s' with unsupported type '%s'", fieldName, fieldType)
			continue
		}
		goName := strings.ToUpper(fieldName[:1]) + fieldName[1:]
		doc := getDoc(field.Comment.List, goName)
		prop := Property{
			FieldName:     fieldName,
			IDVarName:     fieldName + "Id",
			GetterName:    "get" + goName,
			SetterName:    "set" + goName,
			FieldType:     fieldType,
			Documentation: doc,
			ReadOnly:      strings.Contains(doc, readonlyKeyword),
			GetterBody:    createPropertyGet(fieldName),
			Kind:          kind,
		}
		if getterFunc, found := getMethod(sd.FuncDecl, goName, []string{"Get", "get"}); found {
			prop.GetterBody = createPropertyGet(getterFunc)
		}
		if prop.ReadOnly {
			prop.SetterBody = createPropertySetReadOnly()
		} else {
			//has method
			if setterFunc, found := getMethod(sd.FuncDecl, goName, []string{"Set", "set"}); found {
				setterDecl := sd.FuncDecl[setterFunc]
				returnsError := false
				if setterDecl.Type.Results != nil && len(setterDecl.Type.Results.List) == 1 {
					if ident, ok := setterDecl.Type.Results.List[0].Type.(*ast.Ident); ok && ident.Name == "error" {
						returnsError = true
					}
				}
				if returnsError {
					prop.SetterBody = createPropertySetFunc(setterFunc)
				} else {
					prop.SetterBody = createPropertySetFuncReturnNil(setterFunc)
				}
			} else {
				if kind == 2 { // Slice
					prop.SliceElementType = strings.TrimPrefix(fieldType, "[]")
					prop.SetterBody = createPropertySetSlice(fieldName)
					prop.CommandGetterName = "get" + goName + "Entry"
					prop.CommandSetterName = "set" + goName + "Entry"
					prop.CommandGetterBody = createCommandGet(fieldName, prop.SliceElementType)
					prop.CommandSetterBody = createCommandSet(fieldName)
				} else { // Base type
					prop.SetterBody = createPropertySetPrimitive(fieldName)
				}
			}
		}
		sd.Properties = append(sd.Properties, prop)
	}
}

// Generator is responsible for parsing Go files to extract struct definitions and generate output based on their metadata.
type Generator struct {
	fileSet   *token.FileSet
	inputFile string
	output    io.Writer
	useFile   bool
}

// NewGenerator creates and initializes a new Generator instance with the given input file and file usage flag.
func NewGenerator(inputFile string, useFile bool) *Generator {
	return &Generator{
		fileSet:   token.NewFileSet(),
		inputFile: inputFile,
		useFile:   useFile,
		output:    os.Stdout,
	}
}

// SetOutput sets the output destination for the generated content, replacing the default writer with the provided io.Writer.
func (g *Generator) SetOutput(w io.Writer) {
	g.output = w
}

// getDoc processes a list of comments, removes specific prefixes/keywords, and returns a formatted string or default value.
func getDoc(comments []*ast.Comment, def string) string {
	var doc string
	for _, c := range comments {
		doc += c.Text + " "
	}
	doc = strings.Replace(doc, "//", "", -1)
	doc = strings.Replace(doc, "\t", " ", -1)
	doc = strings.Replace(doc, "\n", " ", -1)
	doc = strings.Replace(doc, "\r", " ", -1)
	doc = strings.TrimSpace(doc)
	doc = strings.TrimSpace(strings.Replace(doc, exporterPrefix, "", -1))
	doc = strings.TrimSpace(strings.Replace(doc, readonlyKeyword, "", -1))

	if len(doc) == 0 {
		return def
	}
	return doc
}

// prepareStruct analyzes an AST file, extracts struct type definitions, and returns them mapped by their names as StructData.
func (g *Generator) prepareStruct(node *ast.File) map[string]*StructData {
	structs := make(map[string]*StructData)
	ast.Inspect(node, func(n ast.Node) bool {
		if funcDecl, ok := n.(*ast.FuncDecl); ok {
			if funcDecl.Recv != nil && len(funcDecl.Recv.List) > 0 {
				var name string
				if starExpr, ok := funcDecl.Recv.List[0].Type.(*ast.StarExpr); ok {
					switch x := starExpr.X.(type) {
					case *ast.Ident:
						name = x.Name
					case *ast.SelectorExpr:
						name = x.Sel.Name
					}
					if len(name) > 0 {
						elem := structs[name]
						if elem == nil {
							elem = NewStructData(name)
							structs[name] = elem
						}
						elem.FuncDecl[funcDecl.Name.Name] = funcDecl
					}
				}
			}
		}

		if typeSpec, ok := n.(*ast.TypeSpec); ok {
			if name := typeSpec.Name.Name; len(name) > 0 {
				if structType, ok := typeSpec.Type.(*ast.StructType); ok {
					elem := structs[name]
					if elem == nil {
						elem = NewStructData(name)
						structs[name] = elem
					}
					elem.Type = structType
				}
			}
		}
		return true
	})
	return structs
}

// ParseAndGenerate parses the input Go source file, extracts struct definitions and their properties, and generates code based on them.
func (g *Generator) ParseAndGenerate() error {
	st, err := os.Stat(g.inputFile)
	if err != nil {
		return err
	}

	var files []string
	if !st.IsDir() {
		files = append(files, g.inputFile)
	} else {
		files, err = filepath.Glob(filepath.Join(g.inputFile, "*.go"))
		if err != nil {
			return err
		}
	}

	for _, input := range files {
		node, err := parser.ParseFile(g.fileSet, input, nil, parser.ParseComments)
		if err != nil {
			return fmt.Errorf("error parsing file %s: %w", g.inputFile, err)
		}

		structs := g.prepareStruct(node)

		for _, elem := range structs {
			elem.CompileMethods(g.fileSet)
			elem.CompileProperties(g.fileSet)
		}

		for _, data := range structs {
			if err = g.generateFile(node.Name.Name, data); err != nil {
				log.Printf("error generating file for struct %s: %v", data.Name, err)
			}
		}
	}

	return nil
}

// generateFile generates a Go file based on the provided `StructData` and a predefined template.
// It writes the resulting code to the specified output or creates a new file when `useFile` is true.
// Returns an error if template parsing or file operations fail.
func (g *Generator) generateFile(packageName string, data *StructData) error {
	if len(data.Properties) == 0 {
		return nil
	}
	tmpl, err := template.New("reflect").Parse(reflectTemplate)
	if err != nil {
		return fmt.Errorf("error while creating template: %w", err)
	}
	writer := g.output
	if g.useFile {
		baseName := strings.ToLower(data.Name)
		outputFilename := fmt.Sprintf("%s%s.go", baseName, exporterFileSuffix)
		outputFilepath := filepath.Join(filepath.Dir(g.inputFile), outputFilename)
		f, fErr := os.Create(outputFilepath)
		if fErr != nil {
			return fmt.Errorf("error while creating output file: %w", fErr)
		}
		defer f.Close()
		writer = f
	}
	templateData := TemplateData{
		PackageName: packageName,
		StructName:  data.Name,
		Properties:  data.Properties,
		Methods:     data.Methods,
	}
	return tmpl.Execute(writer, &templateData)
}

// createPropertyGet generates a getter body that accesses a specific field of a struct via a provided field name.
func createPropertyGet(fieldName string) string {
	return fmt.Sprintf(`return s.ref.%s`, fieldName)
}

// createPropertySetReadOnly generates a default error message indicating that a property is read-only.
func createPropertySetReadOnly() string {
	return `return errors.New("property is read-only")`
}

// createPropertySetPrimitive generates a function body string to set a struct field value and return nil.
func createPropertySetPrimitive(fieldName string) string {
	return fmt.Sprintf(`s.ref.%s = v
	return nil`, fieldName)
}

// createPropertySetSlice generates code for setting a slice property on a struct and returns the formatted string.
func createPropertySetSlice(fieldName string) string {
	return fmt.Sprintf(`copy(s.ref.%s, v)
	return nil`, fieldName)
}

// createPropertySetFunc generates the body of a setter method that assigns a value via a referenced method in the struct.
func createPropertySetFunc(setterFunc string) string {
	return fmt.Sprintf(`return s.ref.%s(v)`, setterFunc)
}

// createPropertySetFuncReturnNil generates a setter function body for a field that sets its value and always returns nil.
func createPropertySetFuncReturnNil(fieldName string) string {
	return fmt.Sprintf(`s.ref.%s(v)
	return nil`, fieldName)
}

// createCommandSet generates a template for setting a value at a specific index of a slice, ensuring safety with bound checking.
func createCommandSet(fieldName string) string {
	return fmt.Sprintf(`if idx >= 0 && idx < len(s.ref.%s) {
        s.ref.%s[idx] = v
        return nil
    }
    return errors.New("index out of bounds")`, fieldName, fieldName)
}

// createCommandGet generates a string representing a Go function to retrieve an element from a slice by index.
// It ensures bound checking and returns a zero value of the slice element type if the index is out of range.
func createCommandGet(fieldName string, elementType string) string {
	return fmt.Sprintf(`if idx >= 0 && idx < len(s.ref.%s) {
        return s.ref.%s[idx], nil
    }
    return *new(%s), errors.New("index out of bounds")`, fieldName, fieldName, elementType)
}

// typeAllowed determines if a given field type is supported as a base type or slice type.
// Returns 1 for base types, 2 for slice types, and 0 for unsupported types.
func typeAllowed(fieldType string) int {
	const slicePrefixDef = "[]"
	if _allowedBaseTypes[fieldType] {
		return 1 // Base type
	}
	if strings.HasPrefix(fieldType, slicePrefixDef) {
		if _allowedSliceElementTypes[strings.TrimPrefix(fieldType, slicePrefixDef)] {
			return 2 // Slice type
		}
	}
	return 0 // Unsupported
}

// ToType converts an AST expression into its string representation using the given token.FileSet. Returns the string type and any error encountered.
func toType(fileSet *token.FileSet, field ast.Expr) (string, error) {
	var typeNameBuf bytes.Buffer
	if err := printer.Fprint(&typeNameBuf, fileSet, field); err != nil {
		return "", err
	}
	fieldType := typeNameBuf.String()
	return fieldType, nil
}

// getMethod searches for a method name in a method map using the base name and a list of possible prefixes.
// It returns the full method name and a boolean indicating whether the method was found.
func getMethod(methods map[string]*ast.FuncDecl, baseName string, prefixes []string) (string, bool) {
	if methods == nil {
		return "", false
	}
	for _, p := range prefixes {
		completeName := p + baseName
		if _, ok := methods[completeName]; ok {
			return completeName, true
		}
	}
	return "", false
}
