package component

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"io"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// allowedBaseTypes defines a set of primitive base types that are considered valid for specific operations or checks.
var allowedBaseTypes = map[string]bool{
	"string": true, "bool": true, "int": true, "int8": true, "int16": true, "int32": true, "int64": true,
	"uint": true, "uint8": true, "uint16": true, "uint32": true, "uint64": true, "float32": true, "float64": true,
}

// allowedSliceElementTypes defines the set of data types allowed for elements within slice types.
var allowedSliceElementTypes = map[string]bool{
	"int": true, "int8": true, "int16": true, "int32": true, "int64": true,
	"byte": true, "uint": true, "uint8": true, "uint16": true, "uint32": true, "uint64": true,
}

// exporterPrefix defines the prefix used for symphony export-related operations.
// exporterFileSuffix specifies the suffix for generated reflection files.
// readonlyKeyword indicates the readonly access keyword for operations.
const (
	exporterPrefix     = "symphony:export"
	exporterFileSuffix = "_reflect_gen"
	readonlyKeyword    = "readonly"
)

// reflectTemplate is a constant template string used to generate Go code for struct reflection and property manipulation.
const reflectTemplate = `package {{.PackageName}}

// Code generated by symphony-generator. DO NOT EDIT.

import "errors"

const (
    {{- range .Properties}}
    {{.IDVarName}} = "{{.FieldName}}"
    {{- end}}
)

type {{.StructName}}Reflect struct {
    ref *{{.StructName}}
}

func New{{.StructName}}Reflect(r *{{.StructName}}) *{{.StructName}}Reflect {
    reflector := &{{.StructName}}Reflect{ref: r}
    {{- range .Properties}}
    r.PropertyAdd({{.IDVarName}}, "{{.Documentation}}", {{.ReadOnly}}, reflector.{{.GetterName}}, reflector.{{.SetterName}})
    {{if eq .Kind 2}}
    _ = r.CommandAdd("{{.CommandGetterName}}", "{{.Documentation}}", reflector.{{.CommandGetterName}})
    _ = r.CommandAdd("{{.CommandSetterName}}", "{{.Documentation}}", reflector.{{.CommandSetterName}})
    {{end}}
    {{- end}}
    return reflector
}
{{range .Properties}}
// {{.GetterName}} is the generated getter for the {{.FieldName}}.
func (s *{{$.StructName}}Reflect) {{.GetterName}}() {{.FieldType}} {
    {{.GetterBody}}
}

// {{.SetterName}} is the generated setter for the {{.FieldName}} field.{{if not .ReadOnly}}
func (s *{{$.StructName}}Reflect) {{.SetterName}}(v {{.FieldType}}) error {
    {{.SetterBody}}
}{{else}}
func (s *{{$.StructName}}Reflect) {{.SetterName}}(v {{.FieldType}}) error {
    // property {{.FieldName}} is read-only.
    return errors.New("property {{.FieldName}} is read-only")
}
{{end}}
{{if eq .Kind 2}}
// {{.CommandGetterName}} is the generated indexed getter for the {{.FieldName}}.
func (s *{{$.StructName}}Reflect) {{.CommandGetterName}}(idx int) {{.SliceElementType}} {
    {{.CommandGetterBody}}
}

// {{.CommandSetterName}} is the generated indexed setter for the {{.FieldName}}.
func (s *{{$.StructName}}Reflect) {{.CommandSetterName}}(idx int, v {{.SliceElementType}}) error {
    {{.CommandSetterBody}}
}
{{end}}
{{end}}
`

// Property represents the metadata and generated logic for a struct field to enable various code generation features.
type Property struct {
	FieldName         string
	IDVarName         string
	GetterName        string
	SetterName        string
	FieldType         string
	Documentation     string
	ReadOnly          bool
	Kind              int
	GetterBody        string
	SetterBody        string
	CommandGetterName string
	CommandSetterName string
	CommandGetterBody string
	CommandSetterBody string
	SliceElementType  string
}

// TemplateData represents the template context used during code generation.
// It contains the package name, the struct name, and the list of properties for the struct.
type TemplateData struct {
	PackageName string
	StructName  string
	Properties  []Property
}

// StructData represents metadata for a struct including its name and associated properties.
type StructData struct {
	StructName string
	Properties []Property
}

// Generator is responsible for parsing Go files to extract struct definitions and generate output based on their metadata.
type Generator struct {
	fileSet     *token.FileSet
	inputFile   string
	packageName string
	structs     map[string]*StructData
	output      io.Writer
	useFile     bool
}

// NewGenerator creates and initializes a new Generator instance with the given input file and file usage flag.
func NewGenerator(inputFile string, useFile bool) *Generator {
	return &Generator{
		fileSet:   token.NewFileSet(),
		inputFile: inputFile,
		useFile:   useFile,
		output:    os.Stdout,
		structs:   make(map[string]*StructData),
	}
}

// SetOutput sets the output destination for the generated content, replacing the default writer with the provided io.Writer.
func (g *Generator) SetOutput(w io.Writer) {
	g.output = w
}

// TypeAllowed determines if a given field type is supported as a base type or slice type.
// Returns 1 for base types, 2 for slice types, and 0 for unsupported types.
func TypeAllowed(fieldType string) int {
	const slicePrefixDef = "[]"
	if allowedBaseTypes[fieldType] {
		return 1 // Base type
	}
	if strings.HasPrefix(fieldType, slicePrefixDef) {
		if allowedSliceElementTypes[strings.TrimPrefix(fieldType, slicePrefixDef)] {
			return 2 // Slice type
		}
	}
	return 0 // Unsupported
}

// ParseAndGenerate parses the input Go source file, extracts struct definitions and their properties, and generates code based on them.
func (g *Generator) ParseAndGenerate() error {
	node, err := parser.ParseFile(g.fileSet, g.inputFile, nil, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("error parsing file %s: %w", g.inputFile, err)
	}

	g.packageName = node.Name.Name

	typeMethods := make(map[string]map[string]*ast.FuncDecl)
	ast.Inspect(node, func(n ast.Node) bool {
		funcDecl, ok := n.(*ast.FuncDecl)
		if !ok || funcDecl.Recv == nil || len(funcDecl.Recv.List) == 0 {
			return true
		}
		if starExpr, ok := funcDecl.Recv.List[0].Type.(*ast.StarExpr); ok {
			if ident, ok := starExpr.X.(*ast.Ident); ok {
				structName := ident.Name
				if typeMethods[structName] == nil {
					typeMethods[structName] = make(map[string]*ast.FuncDecl)
				}
				typeMethods[structName][funcDecl.Name.Name] = funcDecl
			}
		}
		return true
	})

	ast.Inspect(node, func(n ast.Node) bool {
		typeSpec, ok := n.(*ast.TypeSpec)
		if !ok {
			return true
		}
		structType, ok := typeSpec.Type.(*ast.StructType)
		if !ok {
			return true
		}
		structName := typeSpec.Name.Name
		if _, ok := g.structs[structName]; !ok {
			g.structs[structName] = &StructData{StructName: structName, Properties: []Property{}}
		}
		structData := g.structs[structName]
		methods := typeMethods[structName]
		for _, field := range structType.Fields.List {
			if field.Comment == nil || len(field.Names) == 0 {
				continue
			}
			commentText := field.Comment.List[0].Text
			if !strings.Contains(commentText, exporterPrefix) {
				continue
			}
			fieldName := field.Names[0].Name
			var typeNameBuf bytes.Buffer
			if err = printer.Fprint(&typeNameBuf, g.fileSet, field.Type); err != nil {
				log.Printf("warning: could not determine type for field %s: %v", fieldName, err)
				continue
			}
			fieldType := typeNameBuf.String()
			kind := TypeAllowed(fieldType)
			if kind == 0 {
				log.Printf("warning: Skipping field '%s' with unsupported type '%s'", fieldName, fieldType)
				continue
			}
			goName := strings.ToUpper(fieldName[:1]) + fieldName[1:]
			doc := strings.TrimSpace(strings.Replace(commentText, exporterPrefix, "", -1))
			doc = strings.TrimPrefix(doc, "//")
			isReadOnly := strings.Contains(doc, readonlyKeyword)
			doc = strings.TrimSpace(strings.Replace(doc, readonlyKeyword, "", -1))
			if doc == "" {
				doc = goName
			}
			getterName := "get" + goName
			getterBody := createPropertyGet(fieldName)
			if getterFunc, found := g.getMethod(methods, goName, []string{"Get", "get"}); found {
				getterBody = createPropertyGet(getterFunc)
			}
			setterName := "set" + goName
			var setterBody string

			prop := Property{
				FieldName:     fieldName,
				IDVarName:     fieldName + "Id",
				GetterName:    getterName,
				SetterName:    setterName,
				FieldType:     fieldType,
				Documentation: doc,
				ReadOnly:      isReadOnly,
				GetterBody:    getterBody,
				Kind:          kind,
			}

			if isReadOnly {
				setterBody = createPropertySetReadOnly()
			} else {
				//has method
				if setterFunc, found := g.getMethod(methods, goName, []string{"Set", "set"}); found {
					setterDecl := methods[setterFunc]
					returnsError := false
					if setterDecl.Type.Results != nil && len(setterDecl.Type.Results.List) == 1 {
						if ident, ok := setterDecl.Type.Results.List[0].Type.(*ast.Ident); ok && ident.Name == "error" {
							returnsError = true
						}
					}
					if returnsError {
						setterBody = createPropertySetFunc(setterFunc)
					} else {
						setterBody = createPropertySetFuncReturnNil(setterFunc)
					}
				} else {
					if kind == 2 { // Slice
						setterBody = createPropertySetSlice(fieldName)
						elementType := strings.TrimPrefix(fieldType, "[]")
						prop.SliceElementType = elementType
						prop.CommandGetterName = "get" + goName + "Entry"
						prop.CommandSetterName = "set" + goName + "Entry"
						prop.CommandGetterBody = createCommandGet(fieldName, elementType)
						prop.CommandSetterBody = createCommandSet(fieldName)
					} else { // Base type
						setterBody = createPropertySetPrimitive(fieldName)
					}
				}
			}
			prop.SetterBody = setterBody
			structData.Properties = append(structData.Properties, prop)
		}
		return true
	})

	for _, data := range g.structs {
		if err = g.generateFile(data); err != nil {
			log.Printf("error generating file for struct %s: %v", data.StructName, err)
		}
	}

	return nil
}

// getMethod searches for a method name in a methods map using the base name and a list of possible prefixes.
// It returns the full method name and a boolean indicating whether the method was found.
func (g *Generator) getMethod(methods map[string]*ast.FuncDecl, baseName string, prefixes []string) (string, bool) {
	for _, p := range prefixes {
		completeName := p + baseName
		if _, ok := methods[completeName]; ok {
			return completeName, true
		}
	}
	return "", false
}

// generateFile generates a Go file based on the provided `StructData` and a predefined template.
// It writes the resulting code to the specified output or creates a new file when `useFile` is true.
// Returns an error if template parsing or file operations fail.
func (g *Generator) generateFile(data *StructData) error {
	if len(data.Properties) == 0 {
		return nil
	}
	tmpl, err := template.New("reflect").Parse(reflectTemplate)
	if err != nil {
		return fmt.Errorf("error while creating template: %w", err)
	}
	writer := g.output
	if g.useFile {
		baseName := strings.ToLower(data.StructName)
		outputFilename := fmt.Sprintf("%s%s.go", baseName, exporterFileSuffix)
		outputFilepath := filepath.Join(filepath.Dir(g.inputFile), outputFilename)
		f, fErr := os.Create(outputFilepath)
		if fErr != nil {
			return fmt.Errorf("error while creating output file: %w", fErr)
		}
		defer f.Close()
		writer = f
	}
	templateData := TemplateData{
		PackageName: g.packageName,
		StructName:  data.StructName,
		Properties:  data.Properties,
	}
	return tmpl.Execute(writer, &templateData)
}

// createPropertyGet generates a getter body that accesses a specific field of a struct via a provided field name.
func createPropertyGet(fieldName string) string {
	return fmt.Sprintf(`return s.ref.%s`, fieldName)
}

// createPropertySetReadOnly generates a default error message indicating that a property is read-only.
func createPropertySetReadOnly() string {
	return `return errors.New("property is read-only")`
}

// createPropertySetPrimitive generates a function body string to set a struct field value and return nil.
func createPropertySetPrimitive(fieldName string) string {
	return fmt.Sprintf(`s.ref.%s = v
	return nil`, fieldName)
}

// createPropertySetSlice generates code for setting a slice property on a struct and returns the formatted string.
func createPropertySetSlice(fieldName string) string {
	return fmt.Sprintf(`copy(s.ref.%s, v)
	return nil`, fieldName)
}

// createPropertySetFunc generates the body of a setter method that assigns a value via a referenced method in the struct.
func createPropertySetFunc(setterFunc string) string {
	return fmt.Sprintf(`return s.ref.%s(v)`, setterFunc)
}

// createPropertySetFuncReturnNil generates a setter function body for a field that sets its value and always returns nil.
func createPropertySetFuncReturnNil(fieldName string) string {
	return fmt.Sprintf(`s.ref.%s(v)
	return nil`, fieldName)
}

// createCommandSet generates a template for setting a value at a specific index of a slice, ensuring safety with bounds checking.
func createCommandSet(fieldName string) string {
	return fmt.Sprintf(`if idx >= 0 && idx < len(s.ref.%s) {
        s.ref.%s[idx] = v
        return nil
    }
    return errors.New("index out of bounds")`, fieldName, fieldName)
}

// createCommandGet generates a string representing a Go function to retrieve an element from a slice by index.
// It ensures bounds checking and returns a zero value of the slice element type if the index is out of range.
func createCommandGet(fieldName string, elementType string) string {
	return fmt.Sprintf(`if idx >= 0 && idx < len(s.ref.%s) {
        return s.ref.%s[idx]
    }
    return *new(%s)`, fieldName, fieldName, elementType)
}
