package mos6526

// Code generated by symphony-generator. DO NOT EDIT.

import "errors"

const (
	reflectTod10thsId       = "tod10ths"
	reflectTodSecId         = "todSec"
	reflectTodMinId         = "todMin"
	reflectTodHrId          = "todHr"
	reflectTodHaltId        = "todHalt"
	reflectTodShadow10thsId = "todShadow10ths"
	reflectTodShadowSecId   = "todShadowSec"
	reflectTodShadowMinId   = "todShadowMin"
	reflectAlm10thsId       = "alm10ths"
	reflectAlmSecId         = "almSec"
	reflectAlmMinId         = "almMin"
	reflectAlmHrId          = "almHr"
)

type TODReflect struct {
	ref              *TOD
	outOfBoundsError error
	readOnlyError    error
}

func NewTODReflect(r *TOD) *TODReflect {
	reflector := &TODReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.PropertyAdd(reflectTod10thsId, "tod10ths represents the tenths of a second value for the Time-of-Day (TOD) clock.", false, reflector.getTod10ths, reflector.setTod10ths)

	r.PropertyAdd(reflectTodSecId, "todSec represents the seconds value for the Time-of-Day (TOD) clock.", false, reflector.getTodSec, reflector.setTodSec)

	r.PropertyAdd(reflectTodMinId, "todMin represents the minutes value for the Time-of-Day (TOD) clock.", false, reflector.getTodMin, reflector.setTodMin)

	r.PropertyAdd(reflectTodHrId, "todHr represents the hour value for the Time-of-Day (TOD) clock.", false, reflector.getTodHr, reflector.setTodHr)

	r.PropertyAdd(reflectTodHaltId, "todHalt indicates whether the Time-of-Day (TOD) clock is halted or running.", false, reflector.getTodHalt, reflector.setTodHalt)

	r.PropertyAdd(reflectTodShadow10thsId, "todShadow10ths holds the shadowed value of the tenth-of-a-second register used during freeze operations.", false, reflector.getTodShadow10ths, reflector.setTodShadow10ths)

	r.PropertyAdd(reflectTodShadowSecId, "todShadowSec holds the shadowed value of the seconds register used during freeze operations of the TOD clock.", false, reflector.getTodShadowSec, reflector.setTodShadowSec)

	r.PropertyAdd(reflectTodShadowMinId, "todShadowMin holds the shadowed value of the minutes register used during freeze operations of the TOD clock.", false, reflector.getTodShadowMin, reflector.setTodShadowMin)

	r.PropertyAdd(reflectAlm10thsId, "alm10ths represents the tenths of a second value for the alarm time.", false, reflector.getAlm10ths, reflector.setAlm10ths)

	r.PropertyAdd(reflectAlmSecId, "almSec represents the seconds value for the alarm time.", false, reflector.getAlmSec, reflector.setAlmSec)

	r.PropertyAdd(reflectAlmMinId, "almMin represents the minutes value for the alarm time.", false, reflector.getAlmMin, reflector.setAlmMin)

	r.PropertyAdd(reflectAlmHrId, "almHr represents the hour value for the alarm time.", false, reflector.getAlmHr, reflector.setAlmHr)

	_ = r.CommandAdd("Update", "Update() bool - Update processes the TOD counter, increments time fields, and checks if the alarm matches the current TOD time.  Returns true if an alarm match occurs, otherwise false.  The rtc parameter determines the TOD frequency divider (50Hz or 60Hz).  Automatically handles AM/PM and 24-hour format transitions.  Resets the divider when time fields are updated.", r.Update)
	_ = r.CommandAdd("GetHour", "GetHour() uint8 - GetHour retrieves the current hour value from the TOD device and freezes the shadow registers state.", r.GetHour)
	_ = r.CommandAdd("GetSec", "GetSec() uint8 - GetSec returns the current seconds value from the TOD, checking the shadow register if applicable.", r.GetSec)
	_ = r.CommandAdd("Get10ths", "Get10ths() uint8 - Get10ths retrieves the current 10ths value from the TOD (Time-of-Day) clock, using the shadow value if available.", r.Get10ths)
	_ = r.CommandAdd("Reset", "Reset() - Reset reinitializes the TOD registers, alarm registers, and control flags to their default states.", r.Reset)
	_ = r.CommandAdd("Emulate", "Emulate() - Emulate handles the emulation process for the TOD, managing operations based on the current TOD state.", r.Emulate)
	_ = r.CommandAdd("Set10ths", "Set10ths(alarm, data) - Set10ths updates the 10ths component of the time or alarm based on the `alarm` flag and provided `data`.  If updating the time and TOD is halted, it resets the divider and unhalts TOD.", r.Set10ths)
	_ = r.CommandAdd("SetHour", "SetHour(alarm, data) - SetHour sets the hour for either the alarm or the time of day based on the `alarm` flag and provided `data` input.", r.SetHour)
	_ = r.CommandAdd("GetMin", "GetMin() uint8 - GetMin retrieves the current minute value from the TOD. If a shadow minute is available, it returns the shadow value.", r.GetMin)
	_ = r.CommandAdd("SetMin", "SetMin(alarm, data) - SetMin sets the minute value for either the TOD clock or the alarm based on the alarm flag.", r.SetMin)
	_ = r.CommandAdd("SetSec", "SetSec(alarm, data) - SetSec sets the seconds value for either the TOD clock or the alarm based on the alarm flag.", r.SetSec)

	return reflector
}

// getTod10ths is the generated getter for the tod10ths.
func (s *TODReflect) getTod10ths() uint8 {
	return s.ref.tod10ths
}

// setTod10ths is the generated setter for the tod10ths field.
func (s *TODReflect) setTod10ths(v uint8) error {
	s.ref.tod10ths = v
	return nil
}

// getTodSec is the generated getter for the todSec.
func (s *TODReflect) getTodSec() uint8 {
	return s.ref.todSec
}

// setTodSec is the generated setter for the todSec field.
func (s *TODReflect) setTodSec(v uint8) error {
	s.ref.todSec = v
	return nil
}

// getTodMin is the generated getter for the todMin.
func (s *TODReflect) getTodMin() uint8 {
	return s.ref.todMin
}

// setTodMin is the generated setter for the todMin field.
func (s *TODReflect) setTodMin(v uint8) error {
	s.ref.todMin = v
	return nil
}

// getTodHr is the generated getter for the todHr.
func (s *TODReflect) getTodHr() uint8 {
	return s.ref.todHr
}

// setTodHr is the generated setter for the todHr field.
func (s *TODReflect) setTodHr(v uint8) error {
	s.ref.todHr = v
	return nil
}

// getTodHalt is the generated getter for the todHalt.
func (s *TODReflect) getTodHalt() bool {
	return s.ref.todHalt
}

// setTodHalt is the generated setter for the todHalt field.
func (s *TODReflect) setTodHalt(v bool) error {
	s.ref.todHalt = v
	return nil
}

// getTodShadow10ths is the generated getter for the todShadow10ths.
func (s *TODReflect) getTodShadow10ths() int {
	return s.ref.todShadow10ths
}

// setTodShadow10ths is the generated setter for the todShadow10ths field.
func (s *TODReflect) setTodShadow10ths(v int) error {
	s.ref.todShadow10ths = v
	return nil
}

// getTodShadowSec is the generated getter for the todShadowSec.
func (s *TODReflect) getTodShadowSec() int {
	return s.ref.todShadowSec
}

// setTodShadowSec is the generated setter for the todShadowSec field.
func (s *TODReflect) setTodShadowSec(v int) error {
	s.ref.todShadowSec = v
	return nil
}

// getTodShadowMin is the generated getter for the todShadowMin.
func (s *TODReflect) getTodShadowMin() int {
	return s.ref.todShadowMin
}

// setTodShadowMin is the generated setter for the todShadowMin field.
func (s *TODReflect) setTodShadowMin(v int) error {
	s.ref.todShadowMin = v
	return nil
}

// getAlm10ths is the generated getter for the alm10ths.
func (s *TODReflect) getAlm10ths() uint8 {
	return s.ref.alm10ths
}

// setAlm10ths is the generated setter for the alm10ths field.
func (s *TODReflect) setAlm10ths(v uint8) error {
	s.ref.alm10ths = v
	return nil
}

// getAlmSec is the generated getter for the almSec.
func (s *TODReflect) getAlmSec() uint8 {
	return s.ref.almSec
}

// setAlmSec is the generated setter for the almSec field.
func (s *TODReflect) setAlmSec(v uint8) error {
	s.ref.almSec = v
	return nil
}

// getAlmMin is the generated getter for the almMin.
func (s *TODReflect) getAlmMin() uint8 {
	return s.ref.almMin
}

// setAlmMin is the generated setter for the almMin field.
func (s *TODReflect) setAlmMin(v uint8) error {
	s.ref.almMin = v
	return nil
}

// getAlmHr is the generated getter for the almHr.
func (s *TODReflect) getAlmHr() uint8 {
	return s.ref.almHr
}

// setAlmHr is the generated setter for the almHr field.
func (s *TODReflect) setAlmHr(v uint8) error {
	s.ref.almHr = v
	return nil
}
