package mos6526

// Code generated by symphony-generator. DO NOT EDIT.

import (
	"errors"
	"github.com/markel1974/c64emu/src/references"
)

const (
	reflectPrAId             = "prA"
	reflectPrBId             = "prB"
	reflectDdrAId            = "ddrA"
	reflectDdrBId            = "ddrB"
	reflectSdrId             = "sdr"
	reflectIcrId             = "icr"
	reflectIrqMaskId         = "irqMask"
	reflectTimerAIrqCycleId  = "timerAIrqCycle"
	reflectTimerBIrqCycleId  = "timerBIrqCycle"
	reflectTodClockDividerId = "todClockDivider"
	reflectLabelId           = "label"
)

type CIAReflect struct {
	ref              *CIA
	outOfBoundsError error
	readOnlyError    error
}

func NewCIAReflect(r *CIA, factory references.IComponentFactory, parent references.IComponent, identifier string, instance int, hardwareId string) *CIAReflect {
	reflector := &CIAReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.BaseComponent.Register(factory, parent, identifier, instance, r, hardwareId)
	r.PropertyAdd(reflectPrAId, "prA represents the current state of the port A register for the CIA component.", false, reflector.getPrA, reflector.setPrA)

	r.PropertyAdd(reflectPrBId, "prB represents the current state of the port B register for the CIA component.", false, reflector.getPrB, reflector.setPrB)

	r.PropertyAdd(reflectDdrAId, "ddrA represents the Data Direction Register for port A, used to configure input/output direction of each bit.", false, reflector.getDdrA, reflector.setDdrA)

	r.PropertyAdd(reflectDdrBId, "ddrB represents the Data Direction Register for Port B, used to configure input/output for the CIA port B pins.", false, reflector.getDdrB, reflector.setDdrB)

	r.PropertyAdd(reflectSdrId, "sdr holds the contents of the Serial Data Register (SDR), used for serial communication operations in the CIA chip.", false, reflector.getSdr, reflector.setSdr)

	r.PropertyAdd(reflectIcrId, "icr holds the Interrupt Control Register value, managing interrupt flags and statuses for the CIA component.", false, reflector.getIcr, reflector.setIcr)

	r.PropertyAdd(reflectIrqMaskId, "irqMask defines the interrupt control mask used to enable or disable specific interrupt sources within the CIA.", false, reflector.getIrqMask, reflector.setIrqMask)

	r.PropertyAdd(reflectTimerAIrqCycleId, "timerAIrqCycle indicates whether an interrupt request should be triggered in the next cycle for Timer A.", false, reflector.getTimerAIrqCycle, reflector.setTimerAIrqCycle)

	r.PropertyAdd(reflectTimerBIrqCycleId, "timerBIrqCycle indicates if Timer B's interrupt request will be triggered in the next emulation cycle.", false, reflector.getTimerBIrqCycle, reflector.setTimerBIrqCycle)

	r.PropertyAdd(reflectTodClockDividerId, "todClockDivider determines the number of cycles before updating the internal Time of Day (TOD) clock.", false, reflector.getTodClockDivider, reflector.setTodClockDivider)

	r.PropertyAdd(reflectLabelId, "Label", false, reflector.getLabel, reflector.setLabel)

	_ = r.CommandAdd("WriteCNTPulse", "WriteCNTPulse() - WriteCNTPulse sends a pulse signal to Timer A's CNT line, triggering it to perform a defined operation.", r.WriteCNTPulse)
	_ = r.CommandAdd("ReadPortA", "ReadPortA() uint8 - ReadPortA reads the current state of port A by considering its data direction and peripheral registers.", r.ReadPortA)
	_ = r.CommandAdd("WriteDDRB", "WriteDDRB(data) - WriteDDRB writes an 8-bit data value to the DDRB register and triggers the socketSignalDDRB function with the updated value.", r.WriteDDRB)
	_ = r.CommandAdd("ReadPRB", "ReadPRB() uint8 - ReadPRB returns the current value of the port B register (PRB) of the CIA.", r.ReadPRB)
	_ = r.CommandAdd("ReadSDR", "ReadSDR() uint8 - ReadSDR retrieves and returns the current value of the sdr field from the CIA instance.", r.ReadSDR)
	_ = r.CommandAdd("WriteCNTLevel", "WriteCNTLevel(level) - WriteCNTLevel sets the CNT pin state for both Timer A and Timer B to the specified level.", r.WriteCNTLevel)
	_ = r.CommandAdd("WritePRB", "WritePRB(data) - WritePRB sets the prB field to the provided data value and triggers socketSignalPRB with the updated prB value.", r.WritePRB)
	_ = r.CommandAdd("WriteICR", "WriteICR(data) - WriteICR writes the given data to the Interrupt Control Register (ICR) and updates the IRQ state accordingly.", r.WriteICR)
	_ = r.CommandAdd("WriteTODSec", "WriteTODSec(data) - WriteTODSec sets the seconds value of the Time of Day (TOD) clock using the provided data parameter.", r.WriteTODSec)
	_ = r.CommandAdd("Emulate", "Emulate() - Emulate performs one emulation cycle, updating internal state, timers, and their interactions without triggering IRQs.  go:nosplit", r.Emulate)
	_ = r.CommandAdd("WriteRegister", "WriteRegister(addr, data) - WriteRegister writes data to the specified address within the CIA, updating registers or triggering system operations.", r.WriteRegister)
	_ = r.CommandAdd("ReadPortB", "ReadPortB() uint8 - ReadPortB reads and returns the current value of Port B, including modifications based on timers with PB output enabled.", r.ReadPortB)
	_ = r.CommandAdd("WriteTODMin", "WriteTODMin(data) - WriteTODMin updates the minute value of the TOD clock using the provided data and RTC configuration.", r.WriteTODMin)
	_ = r.CommandAdd("ReadDDRB", "ReadDDRB() uint8 - ReadDDRB reads and returns the current value of the data direction register B (DDRB) in the CIA.", r.ReadDDRB)
	_ = r.CommandAdd("ReadRegister", "ReadRegister(addr) uint8 - ReadRegister reads the value of the specified register from the CIA based on the provided address.", r.ReadRegister)
	_ = r.CommandAdd("WriteDDRA", "WriteDDRA(data) - WriteDDRA updates the data direction register A and triggers the associated socket signal with the new value.", r.WriteDDRA)
	_ = r.CommandAdd("WriteSDR", "WriteSDR(data) - WriteSDR writes an 8-bit value to the SDR (Serial Data Register) and updates the shift register if serial mode is active.", r.WriteSDR)
	_ = r.CommandAdd("ReadDDRA", "ReadDDRA() uint8 - ReadDDRA reads the value of the Data Direction Register A (DDRA), which determines input/output configuration for port A.", r.ReadDDRA)
	_ = r.CommandAdd("WriteControlRegisterTimerB", "WriteControlRegisterTimerB(data) - WriteControlRegisterTimerB sets the control register for timer B based on the provided data and count mode settings.", r.WriteControlRegisterTimerB)
	_ = r.CommandAdd("WriteTOD10ths", "WriteTOD10ths(data) - WriteTOD10ths writes the 10ths component of the Time-of-Day (TOD) clock using the provided data.", r.WriteTOD10ths)
	_ = r.CommandAdd("WriteTODHour", "WriteTODHour(data) - WriteTODHour updates the TOD hour value using the provided data and the RTC configuration from Timer B.", r.WriteTODHour)
	_ = r.CommandAdd("ReadICR", "ReadICR() uint8 - ReadICR reads the current ICR value, resets it, and clears the IRQ trigger if ICR is non-zero. Returns the ICR value.", r.ReadICR)
	_ = r.CommandAdd("WritePRA", "WritePRA(data) - WritePRA writes the given data to the prA register and triggers the socketSignalPRA with the updated value.", r.WritePRA)
	_ = r.CommandAdd("WriteControlRegisterTimerA", "WriteControlRegisterTimerA(data) - WriteControlRegisterTimerA sets the control register for Timer A with the given data and determines the counting mode.", r.WriteControlRegisterTimerA)
	_ = r.CommandAdd("Reset", "Reset() - Reset reinitializes the internal state of the CIA by resetting all registers, timers, and the time of day (TOD) clock.", r.Reset)
	_ = r.CommandAdd("ReadPRA", "ReadPRA() uint8 - ReadPRA returns the current value of the port A register (PRA) of the CIA.", r.ReadPRA)

	return reflector
}

// getPrA is the generated getter for the prA.
func (s *CIAReflect) getPrA() uint8 {
	return s.ref.prA
}

// setPrA is the generated setter for the prA field.
func (s *CIAReflect) setPrA(v uint8) error {
	s.ref.prA = v
	return nil
}

// getPrB is the generated getter for the prB.
func (s *CIAReflect) getPrB() uint8 {
	return s.ref.prB
}

// setPrB is the generated setter for the prB field.
func (s *CIAReflect) setPrB(v uint8) error {
	s.ref.prB = v
	return nil
}

// getDdrA is the generated getter for the ddrA.
func (s *CIAReflect) getDdrA() uint8 {
	return s.ref.ddrA
}

// setDdrA is the generated setter for the ddrA field.
func (s *CIAReflect) setDdrA(v uint8) error {
	s.ref.ddrA = v
	return nil
}

// getDdrB is the generated getter for the ddrB.
func (s *CIAReflect) getDdrB() uint8 {
	return s.ref.ddrB
}

// setDdrB is the generated setter for the ddrB field.
func (s *CIAReflect) setDdrB(v uint8) error {
	s.ref.ddrB = v
	return nil
}

// getSdr is the generated getter for the sdr.
func (s *CIAReflect) getSdr() uint8 {
	return s.ref.sdr
}

// setSdr is the generated setter for the sdr field.
func (s *CIAReflect) setSdr(v uint8) error {
	s.ref.sdr = v
	return nil
}

// getIcr is the generated getter for the icr.
func (s *CIAReflect) getIcr() uint8 {
	return s.ref.icr
}

// setIcr is the generated setter for the icr field.
func (s *CIAReflect) setIcr(v uint8) error {
	s.ref.icr = v
	return nil
}

// getIrqMask is the generated getter for the irqMask.
func (s *CIAReflect) getIrqMask() uint8 {
	return s.ref.irqMask
}

// setIrqMask is the generated setter for the irqMask field.
func (s *CIAReflect) setIrqMask(v uint8) error {
	s.ref.irqMask = v
	return nil
}

// getTimerAIrqCycle is the generated getter for the timerAIrqCycle.
func (s *CIAReflect) getTimerAIrqCycle() bool {
	return s.ref.timerAIrqCycle
}

// setTimerAIrqCycle is the generated setter for the timerAIrqCycle field.
func (s *CIAReflect) setTimerAIrqCycle(v bool) error {
	s.ref.timerAIrqCycle = v
	return nil
}

// getTimerBIrqCycle is the generated getter for the timerBIrqCycle.
func (s *CIAReflect) getTimerBIrqCycle() bool {
	return s.ref.timerBIrqCycle
}

// setTimerBIrqCycle is the generated setter for the timerBIrqCycle field.
func (s *CIAReflect) setTimerBIrqCycle(v bool) error {
	s.ref.timerBIrqCycle = v
	return nil
}

// getTodClockDivider is the generated getter for the todClockDivider.
func (s *CIAReflect) getTodClockDivider() int {
	return s.ref.todClockDivider
}

// setTodClockDivider is the generated setter for the todClockDivider field.
func (s *CIAReflect) setTodClockDivider(v int) error {
	s.ref.todClockDivider = v
	return nil
}

// getLabel is the generated getter for the label.
func (s *CIAReflect) getLabel() string {
	return s.ref.label
}

// setLabel is the generated setter for the label field.
func (s *CIAReflect) setLabel(v string) error {
	s.ref.label = v
	return nil
}
