package mos6526

// Code generated by symphony-generator. DO NOT EDIT.

import "errors"

const (
	reflectRegisterId = "register"
	reflectCounterId  = "counter"
)

type ShiftRegisterReflect struct {
	ref              *ShiftRegister
	outOfBoundsError error
	readOnlyError    error
}

func NewShiftRegisterReflect(r *ShiftRegister) *ShiftRegisterReflect {
	reflector := &ShiftRegisterReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.PropertyAdd(reflectRegisterId, "register represents the 8-bit storage of the shift register, used for data shifting and processing.", false, reflector.getRegister, reflector.setRegister)

	r.PropertyAdd(reflectCounterId, "counter represents the remaining bits to be shifted in the 8-bit shift register during operation.", false, reflector.getCounter, reflector.setCounter)

	_ = r.CommandAdd("Get", "Get() uint8 - Get returns the current value of the shift register stored in register.", r.Get)
	_ = r.CommandAdd("Counter", "Counter() uint8 - Counter returns the current value of the shift counter (counter).", r.Counter)
	_ = r.CommandAdd("Set", "Set(data) - Set updates the shift register with the provided data and resets the shift counter to 8 bits.", r.Set)
	_ = r.CommandAdd("Emulate", "Emulate() - Emulate performs the core emulation logic for the shift register, managing bit shifts and invoking communication sockets.", r.Emulate)
	_ = r.CommandAdd("Reset", "Reset() - Reset resets the shift register and its counter to their initial state (zero).", r.Reset)
	_ = r.CommandAdd("Handle", "Handle(spMode) bool - Handle processes a single bit in the shift register based on the SP mode and decrements the shift counter.  It returns true if all bits have been processed; otherwise, it returns false.", r.Handle)

	return reflector
}

// getRegister is the generated getter for the register.
func (s *ShiftRegisterReflect) getRegister() uint8 {
	return s.ref.register
}

// setRegister is the generated setter for the register field.
func (s *ShiftRegisterReflect) setRegister(v uint8) error {
	s.ref.register = v
	return nil
}

// getCounter is the generated getter for the counter.
func (s *ShiftRegisterReflect) getCounter() uint8 {
	return s.ref.counter
}

// setCounter is the generated setter for the counter field.
func (s *ShiftRegisterReflect) setCounter(v uint8) error {
	s.ref.counter = v
	return nil
}
