package mos6526

// Code generated by symphony-generator. DO NOT EDIT.

import "errors"

const (
	reflectCrId            = "cr"
	reflectCrNewId         = "crNew"
	reflectCrNewPendingId  = "crNewPending"
	reflectTimerId         = "timer"
	reflectTimerLatchId    = "timerLatch"
	reflectTimerStateId    = "timerState"
	reflectCountModeId     = "countMode"
	reflectToggleModeId    = "toggleMode"
	reflectTimerLatchLowId = "timerLatchLow"
	reflectCntPulseId      = "cntPulse"
	reflectCntLevelId      = "cntLevel"
	reflectUnderflowInId   = "underflowIn"
	reflectUnderflowOutId  = "underflowOut"
)

type TimerReflect struct {
	ref              *Timer
	outOfBoundsError error
	readOnlyError    error
}

func NewTimerReflect(r *Timer) *TimerReflect {
	reflector := &TimerReflect{
		ref:              r,
		outOfBoundsError: errors.New("index out of bounds"),
		readOnlyError:    errors.New("property is read-only"),
	}
	r.PropertyAdd(reflectCrId, "cr represents a configuration register or a control register as an unsigned 8-bit integer.", false, reflector.getCr, reflector.setCr)

	r.PropertyAdd(reflectCrNewId, "crNew represents a new configuration register with an 8-bit unsigned integer value.", false, reflector.getCrNew, reflector.setCrNew)

	r.PropertyAdd(reflectCrNewPendingId, "crNewPending indicates whether a new change request is in a pending state.", false, reflector.getCrNewPending, reflector.setCrNewPending)

	r.PropertyAdd(reflectTimerId, "timer represents a 16-bit unsigned integer used for timing or count-related operations.", false, reflector.getTimer, reflector.setTimer)

	r.PropertyAdd(reflectTimerLatchId, "timerLatch is a 16-bit value used to store the latch for a timer mechanism.", false, reflector.getTimerLatch, reflector.setTimerLatch)

	r.PropertyAdd(reflectTimerStateId, "timerState represents the current state of a timer, encoded as an unsigned 8-bit integer.", false, reflector.getTimerState, reflector.setTimerState)

	r.PropertyAdd(reflectCountModeId, "countMode represents the mode or operation type for counting, defined as an unsigned 8-bit integer.", false, reflector.getCountMode, reflector.setCountMode)

	r.PropertyAdd(reflectToggleModeId, "toggleMode indicates whether the current mode is toggled on or off.", false, reflector.getToggleMode, reflector.setToggleMode)

	r.PropertyAdd(reflectTimerLatchLowId, "timerLatchLow stores the lower 16 bits of the timer latch value used for timing or counting operations.", false, reflector.getTimerLatchLow, reflector.setTimerLatchLow)

	r.PropertyAdd(reflectCntPulseId, "cntPulse indicates whether the pulse counter is enabled or active.", false, reflector.getCntPulse, reflector.setCntPulse)

	r.PropertyAdd(reflectCntLevelId, "cntLevel indicates whether the current level is active or enabled as a boolean value.", false, reflector.getCntLevel, reflector.setCntLevel)

	r.PropertyAdd(reflectUnderflowInId, "underflowIn indicates whether the timer underflow input signal is active or not.", false, reflector.getUnderflowIn, reflector.setUnderflowIn)

	r.PropertyAdd(reflectUnderflowOutId, "underflowOut indicates the current state of the underflow output signal for the Timer instance.", false, reflector.getUnderflowOut, reflector.setUnderflowOut)

	_ = r.CommandAdd("GetTimerLow", "GetTimerLow() uint8 - GetTimerLow retrieves the lower 8 bits of the timer's current value and returns it as an unsigned 8-bit integer.", r.GetTimerLow)
	_ = r.CommandAdd("SetTimerHigh", "SetTimerHigh(prescaler) - SetTimerHigh configures the high byte of the timer latch using the given prescaler and updates the timer if not started.", r.SetTimerHigh)
	_ = r.CommandAdd("SetCNTLevel", "SetCNTLevel(level) - SetCNTLevel sets the CNT (counter) level for the Timer instance based on the provided boolean value.", r.SetCNTLevel)
	_ = r.CommandAdd("GetUnderflowOut", "GetUnderflowOut() bool - GetUnderflowOut retrieves the current state of the underflow output signal from the timer instance.", r.GetUnderflowOut)
	_ = r.CommandAdd("SetControlRegister", "SetControlRegister(data, countMode) - SetControlRegister updates the control register with new data and sets the count mode for the timer.", r.SetControlRegister)
	_ = r.CommandAdd("SetCNTPulse", "SetCNTPulse() - SetCNTPulse enables the CNT pulse by setting the cntPulse field to true.", r.SetCNTPulse)
	_ = r.CommandAdd("Reset", "Reset() - Reset reinitializes the Timer's internal state to its default values and clears any pending or current configurations.", r.Reset)
	_ = r.CommandAdd("SetUnderflowIn", "SetUnderflowIn(u) - SetUnderflowIn sets the underflow input signal state for the timer instance to the specified boolean value.", r.SetUnderflowIn)
	_ = r.CommandAdd("HasPBOn", "HasPBOn() bool - HasPBOn checks whether bit `crBitPBOn` is set in the control register `cr`. Returns true if set, otherwise false.", r.HasPBOn)
	_ = r.CommandAdd("GetRTC", "GetRTC() bool - GetRTC checks if the RTC (Real-Time Clock) bit is set in the control register and returns true if it is.", r.GetRTC)
	_ = r.CommandAdd("SetTimerLow", "SetTimerLow(prescaler) - SetTimerLow sets the lower 8 bits of the timer latch value by converting the given prescaler to a uint16.", r.SetTimerLow)
	_ = r.CommandAdd("Emulate", "Emulate() - Emulate processes the current timer state and performs actions such as counting or toggling based on the timer configuration.", r.Emulate)
	_ = r.CommandAdd("ToggleModeApply", "ToggleModeApply(d) bool - ToggleModeApply applies the toggle mode state based on the control register flags and returns the updated boolean value.", r.ToggleModeApply)
	_ = r.CommandAdd("GetCR", "GetCR() uint8 - GetCR retrieves the current value of the control register (CR) for the Timer instance.", r.GetCR)
	_ = r.CommandAdd("GetTimerHigh", "GetTimerHigh() uint8 - GetTimerHigh returns the high byte (upper 8 bits) of the timer value by shifting the timer's value 8 bits to the right.", r.GetTimerHigh)

	return reflector
}

// getCr is the generated getter for the cr.
func (s *TimerReflect) getCr() uint8 {
	return s.ref.cr
}

// setCr is the generated setter for the cr field.
func (s *TimerReflect) setCr(v uint8) error {
	s.ref.cr = v
	return nil
}

// getCrNew is the generated getter for the crNew.
func (s *TimerReflect) getCrNew() uint8 {
	return s.ref.crNew
}

// setCrNew is the generated setter for the crNew field.
func (s *TimerReflect) setCrNew(v uint8) error {
	s.ref.crNew = v
	return nil
}

// getCrNewPending is the generated getter for the crNewPending.
func (s *TimerReflect) getCrNewPending() bool {
	return s.ref.crNewPending
}

// setCrNewPending is the generated setter for the crNewPending field.
func (s *TimerReflect) setCrNewPending(v bool) error {
	s.ref.crNewPending = v
	return nil
}

// getTimer is the generated getter for the timer.
func (s *TimerReflect) getTimer() uint16 {
	return s.ref.timer
}

// setTimer is the generated setter for the timer field.
func (s *TimerReflect) setTimer(v uint16) error {
	s.ref.timer = v
	return nil
}

// getTimerLatch is the generated getter for the timerLatch.
func (s *TimerReflect) getTimerLatch() uint16 {
	return s.ref.timerLatch
}

// setTimerLatch is the generated setter for the timerLatch field.
func (s *TimerReflect) setTimerLatch(v uint16) error {
	s.ref.timerLatch = v
	return nil
}

// getTimerState is the generated getter for the timerState.
func (s *TimerReflect) getTimerState() uint8 {
	return s.ref.timerState
}

// setTimerState is the generated setter for the timerState field.
func (s *TimerReflect) setTimerState(v uint8) error {
	s.ref.timerState = v
	return nil
}

// getCountMode is the generated getter for the countMode.
func (s *TimerReflect) getCountMode() uint8 {
	return s.ref.countMode
}

// setCountMode is the generated setter for the countMode field.
func (s *TimerReflect) setCountMode(v uint8) error {
	s.ref.setCountMode(v)
	return nil
}

// getToggleMode is the generated getter for the toggleMode.
func (s *TimerReflect) getToggleMode() bool {
	return s.ref.toggleMode
}

// setToggleMode is the generated setter for the toggleMode field.
func (s *TimerReflect) setToggleMode(v bool) error {
	s.ref.toggleMode = v
	return nil
}

// getTimerLatchLow is the generated getter for the timerLatchLow.
func (s *TimerReflect) getTimerLatchLow() uint16 {
	return s.ref.timerLatchLow
}

// setTimerLatchLow is the generated setter for the timerLatchLow field.
func (s *TimerReflect) setTimerLatchLow(v uint16) error {
	s.ref.timerLatchLow = v
	return nil
}

// getCntPulse is the generated getter for the cntPulse.
func (s *TimerReflect) getCntPulse() bool {
	return s.ref.cntPulse
}

// setCntPulse is the generated setter for the cntPulse field.
func (s *TimerReflect) setCntPulse(v bool) error {
	s.ref.cntPulse = v
	return nil
}

// getCntLevel is the generated getter for the cntLevel.
func (s *TimerReflect) getCntLevel() bool {
	return s.ref.cntLevel
}

// setCntLevel is the generated setter for the cntLevel field.
func (s *TimerReflect) setCntLevel(v bool) error {
	s.ref.cntLevel = v
	return nil
}

// getUnderflowIn is the generated getter for the underflowIn.
func (s *TimerReflect) getUnderflowIn() bool {
	return s.ref.underflowIn
}

// setUnderflowIn is the generated setter for the underflowIn field.
func (s *TimerReflect) setUnderflowIn(v bool) error {
	s.ref.SetUnderflowIn(v)
	return nil
}

// getUnderflowOut is the generated getter for the underflowOut.
func (s *TimerReflect) getUnderflowOut() bool {
	return s.ref.GetUnderflowOut()
}

// setUnderflowOut is the generated setter for the underflowOut field.
func (s *TimerReflect) setUnderflowOut(v bool) error {
	s.ref.underflowOut = v
	return nil
}
