package mos6526

// Code generated by symphony-generator. DO NOT EDIT.

const (
	registerId = "register"
	counterId  = "counter"
)

type ShiftRegisterReflect struct {
	ref *ShiftRegister
}

func NewShiftRegisterReflect(r *ShiftRegister) *ShiftRegisterReflect {
	reflector := &ShiftRegisterReflect{ref: r}
	r.PropertyAdd(registerId, "register represents the 8-bit storage of the shift register, used for data shifting and processing.", false, reflector.getRegister, reflector.setRegister)
	r.PropertyAdd(counterId, "counter represents the remaining bits to be shifted in the 8-bit shift register during operation.", false, reflector.getCounter, reflector.setCounter)
	return reflector
}

// getRegister is the generated getter for the  register.
func (s *ShiftRegisterReflect) getRegister() uint8 {
	return s.ref.register
}

// setRegister is the generated setter for the register field.
func (s *ShiftRegisterReflect) setRegister(v uint8) error {
	s.ref.register = v
	return nil
}

// getCounter is the generated getter for the  counter.
func (s *ShiftRegisterReflect) getCounter() uint8 {
	return s.ref.counter
}

// setCounter is the generated setter for the counter field.
func (s *ShiftRegisterReflect) setCounter(v uint8) error {
	s.ref.counter = v
	return nil
}
