package mos6526

// Code generated by symphony-generator. DO NOT EDIT.

const (
	crId            = "cr"
	crNewId         = "crNew"
	crNewPendingId  = "crNewPending"
	timerId         = "timer"
	timerLatchId    = "timerLatch"
	timerStateId    = "timerState"
	countModeId     = "countMode"
	toggleModeId    = "toggleMode"
	timerLatchLowId = "timerLatchLow"
	cntPulseId      = "cntPulse"
	cntLevelId      = "cntLevel"
	underflowInId   = "underflowIn"
	underflowOutId  = "underflowOut"
)

type TimerReflect struct {
	ref *Timer
}

func NewTimerReflect(r *Timer) *TimerReflect {
	reflector := &TimerReflect{ref: r}
	r.PropertyAdd(crId, "cr represents a configuration register or a control register as an unsigned 8-bit integer.", false, reflector.getCr, reflector.setCr)
	r.PropertyAdd(crNewId, "crNew represents a new configuration register with an 8-bit unsigned integer value.", false, reflector.getCrNew, reflector.setCrNew)
	r.PropertyAdd(crNewPendingId, "crNewPending indicates whether a new change request is in a pending state.", false, reflector.getCrNewPending, reflector.setCrNewPending)
	r.PropertyAdd(timerId, "timer represents a 16-bit unsigned integer used for timing or count-related operations.", false, reflector.getTimer, reflector.setTimer)
	r.PropertyAdd(timerLatchId, "timerLatch is a 16-bit value used to store the latch for a timer mechanism.", false, reflector.getTimerLatch, reflector.setTimerLatch)
	r.PropertyAdd(timerStateId, "timerState represents the current state of a timer, encoded as an unsigned 8-bit integer.", false, reflector.getTimerState, reflector.setTimerState)
	r.PropertyAdd(countModeId, "countMode represents the mode or operation type for counting, defined as an unsigned 8-bit integer.", false, reflector.getCountMode, reflector.setCountMode)
	r.PropertyAdd(toggleModeId, "toggleMode indicates whether the current mode is toggled on or off.", false, reflector.getToggleMode, reflector.setToggleMode)
	r.PropertyAdd(timerLatchLowId, "timerLatchLow stores the lower 16 bits of the timer latch value used for timing or counting operations.", false, reflector.getTimerLatchLow, reflector.setTimerLatchLow)
	r.PropertyAdd(cntPulseId, "cntPulse indicates whether the pulse counter is enabled or active.", false, reflector.getCntPulse, reflector.setCntPulse)
	r.PropertyAdd(cntLevelId, "cntLevel indicates whether the current level is active or enabled as a boolean value.", false, reflector.getCntLevel, reflector.setCntLevel)
	r.PropertyAdd(underflowInId, "underflowIn indicates whether the timer underflow input signal is active or not.", false, reflector.getUnderflowIn, reflector.setUnderflowIn)
	r.PropertyAdd(underflowOutId, "underflowOut indicates the current state of the underflow output signal for the Timer instance.", false, reflector.getUnderflowOut, reflector.setUnderflowOut)
	return reflector
}

// getCr is the generated getter for the  cr.
func (s *TimerReflect) getCr() uint8 {
	return s.ref.cr
}

// setCr is the generated setter for the cr field.
func (s *TimerReflect) setCr(v uint8) error {
	s.ref.cr = v
	return nil
}

// getCrNew is the generated getter for the  crNew.
func (s *TimerReflect) getCrNew() uint8 {
	return s.ref.crNew
}

// setCrNew is the generated setter for the crNew field.
func (s *TimerReflect) setCrNew(v uint8) error {
	s.ref.crNew = v
	return nil
}

// getCrNewPending is the generated getter for the  crNewPending.
func (s *TimerReflect) getCrNewPending() bool {
	return s.ref.crNewPending
}

// setCrNewPending is the generated setter for the crNewPending field.
func (s *TimerReflect) setCrNewPending(v bool) error {
	s.ref.crNewPending = v
	return nil
}

// getTimer is the generated getter for the  timer.
func (s *TimerReflect) getTimer() uint16 {
	return s.ref.timer
}

// setTimer is the generated setter for the timer field.
func (s *TimerReflect) setTimer(v uint16) error {
	s.ref.timer = v
	return nil
}

// getTimerLatch is the generated getter for the  timerLatch.
func (s *TimerReflect) getTimerLatch() uint16 {
	return s.ref.timerLatch
}

// setTimerLatch is the generated setter for the timerLatch field.
func (s *TimerReflect) setTimerLatch(v uint16) error {
	s.ref.timerLatch = v
	return nil
}

// getTimerState is the generated getter for the  timerState.
func (s *TimerReflect) getTimerState() uint8 {
	return s.ref.timerState
}

// setTimerState is the generated setter for the timerState field.
func (s *TimerReflect) setTimerState(v uint8) error {
	s.ref.timerState = v
	return nil
}

// getCountMode is the generated getter for the  countMode.
func (s *TimerReflect) getCountMode() uint8 {
	return s.ref.countMode
}

// setCountMode is the generated setter for the countMode field.
func (s *TimerReflect) setCountMode(v uint8) error {
	s.ref.setCountMode(v)
	return nil
}

// getToggleMode is the generated getter for the  toggleMode.
func (s *TimerReflect) getToggleMode() bool {
	return s.ref.toggleMode
}

// setToggleMode is the generated setter for the toggleMode field.
func (s *TimerReflect) setToggleMode(v bool) error {
	s.ref.toggleMode = v
	return nil
}

// getTimerLatchLow is the generated getter for the  timerLatchLow.
func (s *TimerReflect) getTimerLatchLow() uint16 {
	return s.ref.timerLatchLow
}

// setTimerLatchLow is the generated setter for the timerLatchLow field.
func (s *TimerReflect) setTimerLatchLow(v uint16) error {
	s.ref.timerLatchLow = v
	return nil
}

// getCntPulse is the generated getter for the  cntPulse.
func (s *TimerReflect) getCntPulse() bool {
	return s.ref.cntPulse
}

// setCntPulse is the generated setter for the cntPulse field.
func (s *TimerReflect) setCntPulse(v bool) error {
	s.ref.cntPulse = v
	return nil
}

// getCntLevel is the generated getter for the  cntLevel.
func (s *TimerReflect) getCntLevel() bool {
	return s.ref.cntLevel
}

// setCntLevel is the generated setter for the cntLevel field.
func (s *TimerReflect) setCntLevel(v bool) error {
	s.ref.cntLevel = v
	return nil
}

// getUnderflowIn is the generated getter for the  underflowIn.
func (s *TimerReflect) getUnderflowIn() bool {
	return s.ref.underflowIn
}

// setUnderflowIn is the generated setter for the underflowIn field.
func (s *TimerReflect) setUnderflowIn(v bool) error {
	s.ref.SetUnderflowIn(v)
	return nil
}

// getUnderflowOut is the generated getter for the  underflowOut.
func (s *TimerReflect) getUnderflowOut() bool {
	return s.ref.GetUnderflowOut()
}

// setUnderflowOut is the generated setter for the underflowOut field.
func (s *TimerReflect) setUnderflowOut(v bool) error {
	s.ref.underflowOut = v
	return nil
}
