package mos6526

// Code generated by symphony-generator. DO NOT EDIT.

const (
	tod10thsId       = "tod10ths"
	todSecId         = "todSec"
	todMinId         = "todMin"
	todHrId          = "todHr"
	todHaltId        = "todHalt"
	todShadow10thsId = "todShadow10ths"
	todShadowSecId   = "todShadowSec"
	todShadowMinId   = "todShadowMin"
	alm10thsId       = "alm10ths"
	almSecId         = "almSec"
	almMinId         = "almMin"
	almHrId          = "almHr"
)

type TODReflect struct {
	ref *TOD
}

func NewTODReflect(r *TOD) *TODReflect {
	reflector := &TODReflect{ref: r}
	r.PropertyAdd(tod10thsId, "tod10ths represents the tenths of a second value for the Time-of-Day (TOD) clock.", false, reflector.getTod10ths, reflector.setTod10ths)
	r.PropertyAdd(todSecId, "todSec represents the seconds value for the Time-of-Day (TOD) clock.", false, reflector.getTodSec, reflector.setTodSec)
	r.PropertyAdd(todMinId, "todMin represents the minutes value for the Time-of-Day (TOD) clock.", false, reflector.getTodMin, reflector.setTodMin)
	r.PropertyAdd(todHrId, "todHr represents the hour value for the Time-of-Day (TOD) clock.", false, reflector.getTodHr, reflector.setTodHr)
	r.PropertyAdd(todHaltId, "todHalt indicates whether the Time-of-Day (TOD) clock is halted or running.", false, reflector.getTodHalt, reflector.setTodHalt)
	r.PropertyAdd(todShadow10thsId, "todShadow10ths holds the shadowed value of the tenth-of-a-second register used during freeze operations.", false, reflector.getTodShadow10ths, reflector.setTodShadow10ths)
	r.PropertyAdd(todShadowSecId, "todShadowSec holds the shadowed value of the seconds register used during freeze operations of the TOD clock.", false, reflector.getTodShadowSec, reflector.setTodShadowSec)
	r.PropertyAdd(todShadowMinId, "todShadowMin holds the shadowed value of the minutes register used during freeze operations of the TOD clock.", false, reflector.getTodShadowMin, reflector.setTodShadowMin)
	r.PropertyAdd(alm10thsId, "alm10ths represents the tenths of a second value for the alarm time.", false, reflector.getAlm10ths, reflector.setAlm10ths)
	r.PropertyAdd(almSecId, "almSec represents the seconds value for the alarm time.", false, reflector.getAlmSec, reflector.setAlmSec)
	r.PropertyAdd(almMinId, "almMin represents the minutes value for the alarm time.", false, reflector.getAlmMin, reflector.setAlmMin)
	r.PropertyAdd(almHrId, "almHr represents the hour value for the alarm time.", false, reflector.getAlmHr, reflector.setAlmHr)
	return reflector
}

// getTod10ths is the generated getter for the  tod10ths.
func (s *TODReflect) getTod10ths() uint8 {
	return s.ref.tod10ths
}

// setTod10ths is the generated setter for the tod10ths field.
func (s *TODReflect) setTod10ths(v uint8) error {
	s.ref.tod10ths = v
	return nil
}

// getTodSec is the generated getter for the  todSec.
func (s *TODReflect) getTodSec() uint8 {
	return s.ref.todSec
}

// setTodSec is the generated setter for the todSec field.
func (s *TODReflect) setTodSec(v uint8) error {
	s.ref.todSec = v
	return nil
}

// getTodMin is the generated getter for the  todMin.
func (s *TODReflect) getTodMin() uint8 {
	return s.ref.todMin
}

// setTodMin is the generated setter for the todMin field.
func (s *TODReflect) setTodMin(v uint8) error {
	s.ref.todMin = v
	return nil
}

// getTodHr is the generated getter for the  todHr.
func (s *TODReflect) getTodHr() uint8 {
	return s.ref.todHr
}

// setTodHr is the generated setter for the todHr field.
func (s *TODReflect) setTodHr(v uint8) error {
	s.ref.todHr = v
	return nil
}

// getTodHalt is the generated getter for the  todHalt.
func (s *TODReflect) getTodHalt() bool {
	return s.ref.todHalt
}

// setTodHalt is the generated setter for the todHalt field.
func (s *TODReflect) setTodHalt(v bool) error {
	s.ref.todHalt = v
	return nil
}

// getTodShadow10ths is the generated getter for the  todShadow10ths.
func (s *TODReflect) getTodShadow10ths() int {
	return s.ref.todShadow10ths
}

// setTodShadow10ths is the generated setter for the todShadow10ths field.
func (s *TODReflect) setTodShadow10ths(v int) error {
	s.ref.todShadow10ths = v
	return nil
}

// getTodShadowSec is the generated getter for the  todShadowSec.
func (s *TODReflect) getTodShadowSec() int {
	return s.ref.todShadowSec
}

// setTodShadowSec is the generated setter for the todShadowSec field.
func (s *TODReflect) setTodShadowSec(v int) error {
	s.ref.todShadowSec = v
	return nil
}

// getTodShadowMin is the generated getter for the  todShadowMin.
func (s *TODReflect) getTodShadowMin() int {
	return s.ref.todShadowMin
}

// setTodShadowMin is the generated setter for the todShadowMin field.
func (s *TODReflect) setTodShadowMin(v int) error {
	s.ref.todShadowMin = v
	return nil
}

// getAlm10ths is the generated getter for the  alm10ths.
func (s *TODReflect) getAlm10ths() uint8 {
	return s.ref.alm10ths
}

// setAlm10ths is the generated setter for the alm10ths field.
func (s *TODReflect) setAlm10ths(v uint8) error {
	s.ref.alm10ths = v
	return nil
}

// getAlmSec is the generated getter for the  almSec.
func (s *TODReflect) getAlmSec() uint8 {
	return s.ref.almSec
}

// setAlmSec is the generated setter for the almSec field.
func (s *TODReflect) setAlmSec(v uint8) error {
	s.ref.almSec = v
	return nil
}

// getAlmMin is the generated getter for the  almMin.
func (s *TODReflect) getAlmMin() uint8 {
	return s.ref.almMin
}

// setAlmMin is the generated setter for the almMin field.
func (s *TODReflect) setAlmMin(v uint8) error {
	s.ref.almMin = v
	return nil
}

// getAlmHr is the generated getter for the  almHr.
func (s *TODReflect) getAlmHr() uint8 {
	return s.ref.almHr
}

// setAlmHr is the generated setter for the almHr field.
func (s *TODReflect) setAlmHr(v uint8) error {
	s.ref.almHr = v
	return nil
}
